#Project generated by Animated Java (https://animated-java.dev/)

execute if score @s aj.sully_boss.attack.loopMode matches 0 run function sully_boss:animations/attack/stop
execute if score @s aj.sully_boss.attack.loopMode matches 1 run function sully_boss:animations/attack/pause
execute if score @s aj.sully_boss.attack.loopMode matches 2 run function sully_boss:animations/attack/zzz/execute/37