#Project generated by Animated Java (https://animated-java.dev/)

schedule function sully_boss:animation_loop 1t
scoreboard players set .aj.anim_loop aj.sully_boss.animating 1
scoreboard players set .aj.animation aj.sully_boss.animating 0
execute as @e[type=minecraft:marker,tag=aj.sully_boss.root] run function sully_boss:zzz/execute/32
execute if score .aj.animation aj.sully_boss.animating matches 0 run function sully_boss:zzz/execute/33