#Project generated by Animated Java (https://animated-java.dev/)

scoreboard players set #execute aj.i 0
execute if entity @s[tag=aj.sully_boss.root] rotated ~ 0 run function sully_boss:zzz/conditional/4
execute if score #execute aj.i matches 0 run function sully_boss:zzz/conditional/5