#Project generated by Animated Java (https://animated-java.dev/)

execute if score @s aj.sully_boss.walk.loopMode matches 0 run function sully_boss:animations/walk/stop
execute if score @s aj.sully_boss.walk.loopMode matches 1 run function sully_boss:animations/walk/pause
execute if score @s aj.sully_boss.walk.loopMode matches 2 run function sully_boss:animations/walk/zzz/execute/34