#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [0.8f,0f,-0.8f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [0.9f,0f,-0.9f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [1f,0f,-1f]
execute if score .this aj.frame matches 11 run data modify entity @s Pose.Head set value [0.975f,0f,-0.825f]
execute if score .this aj.frame matches 12 run data modify entity @s Pose.Head set value [0.95f,0f,-0.65f]
execute if score .this aj.frame matches 13 run data modify entity @s Pose.Head set value [0.925f,0f,-0.475f]
execute if score .this aj.frame matches 14 run data modify entity @s Pose.Head set value [0.9f,0f,-0.3f]
execute if score .this aj.frame matches 15 run data modify entity @s Pose.Head set value [0.875f,0f,-0.125f]