#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 1 run data modify entity @s Pose.Head set value [0.1f,0f,-0.1f]
execute if score .this aj.frame matches 2 run data modify entity @s Pose.Head set value [0.2f,0f,-0.2f]
execute if score .this aj.frame matches 3 run data modify entity @s Pose.Head set value [0.3f,0f,-0.3f]
execute if score .this aj.frame matches 4 run data modify entity @s Pose.Head set value [0.4f,0f,-0.4f]
execute if score .this aj.frame matches 5 run data modify entity @s Pose.Head set value [0.5f,0f,-0.5f]
execute if score .this aj.frame matches 6 run data modify entity @s Pose.Head set value [0.6f,0f,-0.6f]
execute if score .this aj.frame matches 7 run data modify entity @s Pose.Head set value [0.7f,0f,-0.7f]