#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [11.1395f,0f,0.05f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [11.2724f,0f,0.225f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [11.4053f,0f,0.4f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [11.5382f,0f,0.575f]
execute if score .this aj.frame matches 20 run data modify entity @s Pose.Head set value [11.6711f,0f,0.75f]
execute if score .this aj.frame matches 21 run data modify entity @s Pose.Head set value [11.7539f,0f,0.675f]
execute if score .this aj.frame matches 22 run data modify entity @s Pose.Head set value [11.8368f,0f,0.6f]
execute if score .this aj.frame matches 23 run data modify entity @s Pose.Head set value [11.9197f,0f,0.525f]