#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [12.5f,0f,0f]
execute if score .this aj.frame matches 1 run data modify entity @s Pose.Head set value [12.4235f,0f,-0.1f]
execute if score .this aj.frame matches 2 run data modify entity @s Pose.Head set value [12.3471f,0f,-0.2f]
execute if score .this aj.frame matches 3 run data modify entity @s Pose.Head set value [12.2706f,0f,-0.3f]
execute if score .this aj.frame matches 4 run data modify entity @s Pose.Head set value [12.1941f,0f,-0.4f]
execute if score .this aj.frame matches 5 run data modify entity @s Pose.Head set value [12.1176f,0f,-0.5f]
execute if score .this aj.frame matches 6 run data modify entity @s Pose.Head set value [12.0412f,0f,-0.6f]
execute if score .this aj.frame matches 7 run data modify entity @s Pose.Head set value [11.9647f,0f,-0.7f]