#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run data modify entity @s Pose.Head set value [12.0026f,0f,0.45f]
execute if score .this aj.frame matches 25 run data modify entity @s Pose.Head set value [12.0855f,0f,0.375f]
execute if score .this aj.frame matches 26 run data modify entity @s Pose.Head set value [12.1684f,0f,0.3f]
execute if score .this aj.frame matches 27 run data modify entity @s Pose.Head set value [12.2513f,0f,0.225f]
execute if score .this aj.frame matches 28 run data modify entity @s Pose.Head set value [12.3342f,0f,0.15f]
execute if score .this aj.frame matches 29 run data modify entity @s Pose.Head set value [12.4171f,0f,0.075f]