#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [11.8882f,0f,-0.8f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [11.8118f,0f,-0.9f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [11.7353f,0f,-1f]
execute if score .this aj.frame matches 11 run data modify entity @s Pose.Head set value [11.5338f,0f,-0.825f]
execute if score .this aj.frame matches 12 run data modify entity @s Pose.Head set value [11.3324f,0f,-0.65f]
execute if score .this aj.frame matches 13 run data modify entity @s Pose.Head set value [11.1309f,0f,-0.475f]
execute if score .this aj.frame matches 14 run data modify entity @s Pose.Head set value [10.9294f,0f,-0.3f]
execute if score .this aj.frame matches 15 run data modify entity @s Pose.Head set value [11.0066f,0f,-0.125f]