#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run tp @s ^0.688 ^0.125 ^0.063 ~ ~
execute if score .this aj.frame matches 25 run tp @s ^0.688 ^0.125 ^0.063 ~ ~
execute if score .this aj.frame matches 26 run tp @s ^0.688 ^0.125 ^0.063 ~ ~
execute if score .this aj.frame matches 27 run tp @s ^0.688 ^0.125 ^0.063 ~ ~
execute if score .this aj.frame matches 28 run tp @s ^0.688 ^0.125 ^0.063 ~ ~
execute if score .this aj.frame matches 29 run tp @s ^0.688 ^0.125 ^0.063 ~ ~