#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [0.8f,0.8f,0f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [0.9f,0.9f,0f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [1f,1f,0f]
execute if score .this aj.frame matches 11 run data modify entity @s Pose.Head set value [0.8f,1f,0f]
execute if score .this aj.frame matches 12 run data modify entity @s Pose.Head set value [0.6f,1f,0f]
execute if score .this aj.frame matches 13 run data modify entity @s Pose.Head set value [0.4f,1f,0f]
execute if score .this aj.frame matches 14 run data modify entity @s Pose.Head set value [0.2f,1f,0f]
execute if score .this aj.frame matches 15 run data modify entity @s Pose.Head set value [0f,1f,0f]