#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [-0.2f,1f,0f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [-0.4f,1f,0f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [-0.6f,1f,0f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [-0.8f,1f,0f]
execute if score .this aj.frame matches 20 run data modify entity @s Pose.Head set value [-1f,1f,0f]
execute if score .this aj.frame matches 21 run data modify entity @s Pose.Head set value [-0.9f,0.9f,0f]
execute if score .this aj.frame matches 22 run data modify entity @s Pose.Head set value [-0.8f,0.8f,0f]
execute if score .this aj.frame matches 23 run data modify entity @s Pose.Head set value [-0.7f,0.7f,0f]