#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run data modify entity @s Pose.Head set value [-0.6f,0.6f,0f]
execute if score .this aj.frame matches 25 run data modify entity @s Pose.Head set value [-0.5f,0.5f,0f]
execute if score .this aj.frame matches 26 run data modify entity @s Pose.Head set value [-0.4f,0.4f,0f]
execute if score .this aj.frame matches 27 run data modify entity @s Pose.Head set value [-0.3f,0.3f,0f]
execute if score .this aj.frame matches 28 run data modify entity @s Pose.Head set value [-0.2f,0.2f,0f]
execute if score .this aj.frame matches 29 run data modify entity @s Pose.Head set value [-0.1f,0.1f,0f]