#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^-0.25 ^-1.315 ^-0.116 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^-0.25 ^-1.315 ^-0.117 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^-0.25 ^-1.314 ^-0.118 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^-0.25 ^-1.314 ^-0.119 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^-0.25 ^-1.314 ^-0.12 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^-0.25 ^-1.314 ^-0.122 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^-0.25 ^-1.313 ^-0.123 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^-0.25 ^-1.313 ^-0.124 ~ ~