#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [0.575f,1.094f,0.9376f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [1.025f,1.2222f,0.7104f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [1.475f,1.3504f,0.4831f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [1.925f,1.4786f,0.2559f]
execute if score .this aj.frame matches 20 run data modify entity @s Pose.Head set value [1.8462f,1.3846f,0.2013f]
execute if score .this aj.frame matches 21 run data modify entity @s Pose.Head set value [1.6615f,1.2462f,0.1811f]
execute if score .this aj.frame matches 22 run data modify entity @s Pose.Head set value [1.4769f,1.1077f,0.161f]
execute if score .this aj.frame matches 23 run data modify entity @s Pose.Head set value [1.2923f,0.9692f,0.1409f]