#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run data modify entity @s Pose.Head set value [0.775f,0f,0f]
execute if score .this aj.frame matches 25 run data modify entity @s Pose.Head set value [0.625f,0f,0f]
execute if score .this aj.frame matches 26 run data modify entity @s Pose.Head set value [0.475f,0f,0f]
execute if score .this aj.frame matches 27 run data modify entity @s Pose.Head set value [0.325f,0f,0f]
execute if score .this aj.frame matches 28 run data modify entity @s Pose.Head set value [0.175f,0f,0f]
execute if score .this aj.frame matches 29 run data modify entity @s Pose.Head set value [0.025f,0f,0f]