#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run tp @s ^-0.25 ^-1.311 ^-0.133 ~ ~
execute if score .this aj.frame matches 25 run tp @s ^-0.25 ^-1.312 ^-0.131 ~ ~
execute if score .this aj.frame matches 26 run tp @s ^-0.25 ^-1.312 ^-0.13 ~ ~
execute if score .this aj.frame matches 27 run tp @s ^-0.25 ^-1.312 ^-0.128 ~ ~
execute if score .this aj.frame matches 28 run tp @s ^-0.25 ^-1.313 ^-0.127 ~ ~
execute if score .this aj.frame matches 29 run tp @s ^-0.25 ^-1.313 ^-0.125 ~ ~