#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 1 run data modify entity @s Pose.Head set value [-0.2727f,0.0238f,0.2717f]
execute if score .this aj.frame matches 2 run data modify entity @s Pose.Head set value [-0.5455f,0.0475f,0.5434f]
execute if score .this aj.frame matches 3 run data modify entity @s Pose.Head set value [-0.8182f,0.0713f,0.8151f]
execute if score .this aj.frame matches 4 run data modify entity @s Pose.Head set value [-1.0909f,0.095f,1.0868f]
execute if score .this aj.frame matches 5 run data modify entity @s Pose.Head set value [-1.3636f,0.1188f,1.3585f]
execute if score .this aj.frame matches 6 run data modify entity @s Pose.Head set value [-1.6364f,0.1426f,1.6301f]
execute if score .this aj.frame matches 7 run data modify entity @s Pose.Head set value [-1.9091f,0.1663f,1.9018f]