#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run data modify entity @s Pose.Head set value [1.1077f,0.8308f,0.1208f]
execute if score .this aj.frame matches 25 run data modify entity @s Pose.Head set value [0.9231f,0.6923f,0.1006f]
execute if score .this aj.frame matches 26 run data modify entity @s Pose.Head set value [0.7385f,0.5538f,0.0805f]
execute if score .this aj.frame matches 27 run data modify entity @s Pose.Head set value [0.5538f,0.4154f,0.0604f]
execute if score .this aj.frame matches 28 run data modify entity @s Pose.Head set value [0.3692f,0.2769f,0.0403f]
execute if score .this aj.frame matches 29 run data modify entity @s Pose.Head set value [0.1846f,0.1385f,0.0201f]