#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [-0.94f,0f,0f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [-0.82f,0f,0f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [-0.7f,0f,0f]
execute if score .this aj.frame matches 11 run data modify entity @s Pose.Head set value [-0.58f,0f,0f]
execute if score .this aj.frame matches 12 run data modify entity @s Pose.Head set value [-0.46f,0f,0f]
execute if score .this aj.frame matches 13 run data modify entity @s Pose.Head set value [-0.34f,0f,0f]
execute if score .this aj.frame matches 14 run data modify entity @s Pose.Head set value [-0.22f,0f,0f]
execute if score .this aj.frame matches 15 run data modify entity @s Pose.Head set value [-0.1f,0f,0f]