#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^-0.25 ^-1.313 ^-0.125 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^-0.25 ^-1.313 ^-0.124 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^-0.25 ^-1.314 ^-0.122 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^-0.25 ^-1.314 ^-0.121 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^-0.25 ^-1.314 ^-0.12 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^-0.25 ^-1.314 ^-0.118 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^-0.25 ^-1.315 ^-0.117 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^-0.25 ^-1.315 ^-0.116 ~ ~