#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [-2.1818f,0.1901f,2.1735f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [-2.4545f,0.2139f,2.4452f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [-2.125f,0.3247f,2.3011f]
execute if score .this aj.frame matches 11 run data modify entity @s Pose.Head set value [-1.675f,0.4529f,2.0739f]
execute if score .this aj.frame matches 12 run data modify entity @s Pose.Head set value [-1.225f,0.5811f,1.8466f]
execute if score .this aj.frame matches 13 run data modify entity @s Pose.Head set value [-0.775f,0.7093f,1.6194f]
execute if score .this aj.frame matches 14 run data modify entity @s Pose.Head set value [-0.325f,0.8375f,1.3921f]
execute if score .this aj.frame matches 15 run data modify entity @s Pose.Head set value [0.125f,0.9658f,1.1649f]