#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function sully_boss:animations/attack/tree/left_leg_down_root_0-7
execute if score .this aj.frame matches 8..15 run function sully_boss:animations/attack/tree/left_leg_down_root_8-15
execute if score .this aj.frame matches 16 run tp @s ^0.313 ^-1.313 ^-0.125 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^0.313 ^-1.313 ^-0.125 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^0.313 ^-1.313 ^-0.125 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^0.313 ^-1.313 ^-0.125 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^0.313 ^-1.313 ^-0.125 ~ ~