#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function sully_boss:animations/attack/tree/left_arm_display_0-7
execute if score .this aj.frame matches 8..15 run function sully_boss:animations/attack/tree/left_arm_display_8-15
execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [-29f,0f,0f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [-21.75f,0f,0f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [-14.5f,0f,0f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [-7.25f,0f,0f]
execute if score .this aj.frame matches 20 run data modify entity @s Pose.Head set value [0f,0f,0f]