#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 1 run data modify entity @s Pose.Head set value [-7f,0f,0f]
execute if score .this aj.frame matches 2 run data modify entity @s Pose.Head set value [-14f,0f,0f]
execute if score .this aj.frame matches 3 run data modify entity @s Pose.Head set value [-21f,0f,0f]
execute if score .this aj.frame matches 4 run data modify entity @s Pose.Head set value [-28f,0f,0f]
execute if score .this aj.frame matches 5 run data modify entity @s Pose.Head set value [-35f,0f,0f]
execute if score .this aj.frame matches 6 run data modify entity @s Pose.Head set value [-42f,0f,0f]
execute if score .this aj.frame matches 7 run data modify entity @s Pose.Head set value [-49f,0f,0f]