#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..63 run function sully_boss:animations/sleep/tree/jaw_display_0-63
execute if score .this aj.frame matches 70 run data modify entity @s Pose.Head set value [-122.5f,0f,0f]