#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run data modify entity @s Pose.Head set value [-103f,0f,0f]
execute if score .this aj.frame matches 49 run data modify entity @s Pose.Head set value [-104.625f,0f,0f]
execute if score .this aj.frame matches 50 run data modify entity @s Pose.Head set value [-106.25f,0f,0f]
execute if score .this aj.frame matches 51 run data modify entity @s Pose.Head set value [-107.875f,0f,0f]
execute if score .this aj.frame matches 52 run data modify entity @s Pose.Head set value [-109.5f,0f,0f]
execute if score .this aj.frame matches 53 run data modify entity @s Pose.Head set value [-111.125f,0f,0f]
execute if score .this aj.frame matches 54 run data modify entity @s Pose.Head set value [-112.75f,0f,0f]
execute if score .this aj.frame matches 55 run data modify entity @s Pose.Head set value [-114.375f,0f,0f]