#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run data modify entity @s Pose.Head set value [-91f,0f,0f]
execute if score .this aj.frame matches 25 run data modify entity @s Pose.Head set value [-91.25f,0f,0f]
execute if score .this aj.frame matches 26 run data modify entity @s Pose.Head set value [-91.5f,0f,0f]
execute if score .this aj.frame matches 27 run data modify entity @s Pose.Head set value [-91.75f,0f,0f]
execute if score .this aj.frame matches 28 run data modify entity @s Pose.Head set value [-92f,0f,0f]
execute if score .this aj.frame matches 29 run data modify entity @s Pose.Head set value [-92.25f,0f,0f]
execute if score .this aj.frame matches 30 run data modify entity @s Pose.Head set value [-92.5f,0f,0f]
execute if score .this aj.frame matches 31 run data modify entity @s Pose.Head set value [-92.25f,0f,0f]