#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 56 run data modify entity @s Pose.Head set value [-116f,0f,0f]
execute if score .this aj.frame matches 57 run data modify entity @s Pose.Head set value [-117.625f,0f,0f]
execute if score .this aj.frame matches 58 run data modify entity @s Pose.Head set value [-119.25f,0f,0f]
execute if score .this aj.frame matches 59 run data modify entity @s Pose.Head set value [-120.875f,0f,0f]
execute if score .this aj.frame matches 60 run data modify entity @s Pose.Head set value [-122.5f,0f,0f]