#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 64 run tp @s ^-0.125 ^-1.427 ^-1.402 ~ ~
execute if score .this aj.frame matches 65 run tp @s ^-0.125 ^-1.427 ^-1.402 ~ ~
execute if score .this aj.frame matches 66 run tp @s ^-0.125 ^-1.427 ^-1.402 ~ ~
execute if score .this aj.frame matches 67 run tp @s ^-0.125 ^-1.427 ^-1.402 ~ ~
execute if score .this aj.frame matches 68 run tp @s ^-0.125 ^-1.427 ^-1.402 ~ ~
execute if score .this aj.frame matches 69 run tp @s ^-0.125 ^-1.427 ^-1.402 ~ ~
execute if score .this aj.frame matches 70 run tp @s ^-0.125 ^-1.427 ^-1.402 ~ ~