#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [-109.5f,0f,0f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [-107.875f,0f,0f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [-106.25f,0f,0f]
execute if score .this aj.frame matches 11 run data modify entity @s Pose.Head set value [-104.625f,0f,0f]
execute if score .this aj.frame matches 12 run data modify entity @s Pose.Head set value [-103f,0f,0f]
execute if score .this aj.frame matches 13 run data modify entity @s Pose.Head set value [-101.375f,0f,0f]
execute if score .this aj.frame matches 14 run data modify entity @s Pose.Head set value [-99.75f,0f,0f]
execute if score .this aj.frame matches 15 run data modify entity @s Pose.Head set value [-98.125f,0f,0f]