#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..63 run function sully_boss:animations/sleep/tree/left_leg_root_0-63
execute if score .this aj.frame matches 64..70 run function sully_boss:animations/sleep/tree/left_leg_root_64-70