#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run tp @s ^0 ^-1.6 ^-0.812 ~ ~
execute if score .this aj.frame matches 49 run tp @s ^0 ^-1.602 ^-0.812 ~ ~
execute if score .this aj.frame matches 50 run tp @s ^0 ^-1.604 ^-0.812 ~ ~
execute if score .this aj.frame matches 51 run tp @s ^0 ^-1.606 ^-0.812 ~ ~
execute if score .this aj.frame matches 52 run tp @s ^0 ^-1.608 ^-0.812 ~ ~
execute if score .this aj.frame matches 53 run tp @s ^0 ^-1.61 ^-0.812 ~ ~
execute if score .this aj.frame matches 54 run tp @s ^0 ^-1.613 ^-0.812 ~ ~
execute if score .this aj.frame matches 55 run tp @s ^0 ^-1.615 ^-0.812 ~ ~