#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run tp @s ^0 ^-1.583 ^-0.812 ~ ~
execute if score .this aj.frame matches 41 run tp @s ^0 ^-1.585 ^-0.812 ~ ~
execute if score .this aj.frame matches 42 run tp @s ^0 ^-1.587 ^-0.812 ~ ~
execute if score .this aj.frame matches 43 run tp @s ^0 ^-1.589 ^-0.812 ~ ~
execute if score .this aj.frame matches 44 run tp @s ^0 ^-1.591 ^-0.812 ~ ~
execute if score .this aj.frame matches 45 run tp @s ^0 ^-1.593 ^-0.812 ~ ~
execute if score .this aj.frame matches 46 run tp @s ^0 ^-1.595 ^-0.812 ~ ~
execute if score .this aj.frame matches 47 run tp @s ^0 ^-1.598 ^-0.812 ~ ~