#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^0 ^-1.625 ^-0.812 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^0 ^-1.623 ^-0.812 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^0 ^-1.621 ^-0.812 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^0 ^-1.619 ^-0.812 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^0 ^-1.617 ^-0.812 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^0 ^-1.615 ^-0.812 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^0 ^-1.613 ^-0.812 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^0 ^-1.611 ^-0.812 ~ ~