#Project generated by Animated Java (https://animated-java.dev/)

schedule function christophe:animation_loop 1t
scoreboard players set .aj.anim_loop aj.christophe.animating 1
scoreboard players set .aj.animation aj.christophe.animating 0
execute as @e[type=minecraft:marker,tag=aj.christophe.root] run function christophe:zzz/execute/11
execute if score .aj.animation aj.christophe.animating matches 0 run function christophe:zzz/execute/12