#Project generated by Animated Java (https://animated-java.dev/)

execute if score @s aj.christophe.idle.loopMode matches 0 run function christophe:animations/idle/stop
execute if score @s aj.christophe.idle.loopMode matches 1 run function christophe:animations/idle/pause
execute if score @s aj.christophe.idle.loopMode matches 2 run function christophe:animations/idle/zzz/execute/13