#Project generated by Animated Java (https://animated-java.dev/)

scoreboard players operation .this aj.id = @s aj.id
scoreboard players operation .this aj.frame = @s aj.frame
execute rotated ~ 0 as @e[type=#christophe:bone_entities,tag=aj.christophe.bone,distance=..2.6] if score @s aj.id = .this aj.id run function christophe:animations/idle/tree/trunk
scoreboard players operation @s aj.frame += .aj.christophe.framerate aj.i
scoreboard players set .aj.animation aj.christophe.animating 1
execute unless score @s aj.frame matches 0..40 run function christophe:animations/idle/edge