#Project generated by Animated Java (https://animated-java.dev/)

execute if entity @s[tag=aj.sully_boss.bone.h_head] run function sully_boss:animations/death/tree/h_head_display_top
execute if entity @s[tag=aj.sully_boss.bone.jaw] run function sully_boss:animations/death/tree/jaw_display_top
execute if entity @s[tag=aj.sully_boss.bone.left_leg] run function sully_boss:animations/death/tree/left_leg_display_top
execute if entity @s[tag=aj.sully_boss.bone.right_leg] run function sully_boss:animations/death/tree/right_leg_display_top
execute if entity @s[tag=aj.sully_boss.bone.right_leg_down] run function sully_boss:animations/death/tree/right_leg_down_display_top
execute if entity @s[tag=aj.sully_boss.bone.left_arm] run function sully_boss:animations/death/tree/left_arm_display_top
execute if entity @s[tag=aj.sully_boss.bone.right_arm] run function sully_boss:animations/death/tree/right_arm_display_top
execute if entity @s[tag=aj.sully_boss.bone.torso] run function sully_boss:animations/death/tree/torso_display_top
execute if entity @s[tag=aj.sully_boss.bone.left_leg_down] run function sully_boss:animations/death/tree/left_leg_down_display_top
execute positioned as @s run tp @s ~ ~ ~ ~ ~