#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run tp @s ^0 ^-1.625 ^0.659 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^0 ^-1.625 ^0.716 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^0 ^-1.625 ^0.774 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^0 ^-1.625 ^0.832 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^0 ^-1.625 ^0.889 ~ ~
execute if score .this aj.frame matches 21 run tp @s ^0 ^-1.625 ^0.938 ~ ~
execute if score .this aj.frame matches 22 run tp @s ^0 ^-1.625 ^0.938 ~ ~
execute if score .this aj.frame matches 23 run tp @s ^0 ^-1.625 ^0.938 ~ ~