#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^0 ^0.312 ^0.188 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^0 ^0.282 ^0.203 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^0 ^0.252 ^0.218 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^0 ^0.222 ^0.233 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^0 ^0.192 ^0.248 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^0 ^-0.072 ^0.259 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^0 ^-0.383 ^0.27 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^0 ^-0.693 ^0.28 ~ ~