#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^0 ^-1.004 ^0.291 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^0 ^-1.315 ^0.302 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^0 ^-1.625 ^0.313 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^0 ^-1.625 ^0.37 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^0 ^-1.625 ^0.428 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^0 ^-1.625 ^0.486 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^0 ^-1.625 ^0.543 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^0 ^-1.625 ^0.601 ~ ~