#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [171.84f,0f,0f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [-166.68f,0f,0f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [-145.2f,0f,0f]
execute if score .this aj.frame matches 11 run data modify entity @s Pose.Head set value [-123.72f,0f,0f]
execute if score .this aj.frame matches 12 run data modify entity @s Pose.Head set value [-102.24f,0f,0f]
execute if score .this aj.frame matches 13 run data modify entity @s Pose.Head set value [-80.76f,0f,0f]
execute if score .this aj.frame matches 14 run data modify entity @s Pose.Head set value [-59.28f,0f,0f]
execute if score .this aj.frame matches 15 run data modify entity @s Pose.Head set value [-37.8f,0f,0f]