#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 1 run data modify entity @s Pose.Head set value [21.48f,0f,0f]
execute if score .this aj.frame matches 2 run data modify entity @s Pose.Head set value [42.96f,0f,0f]
execute if score .this aj.frame matches 3 run data modify entity @s Pose.Head set value [64.44f,0f,0f]
execute if score .this aj.frame matches 4 run data modify entity @s Pose.Head set value [85.92f,0f,0f]
execute if score .this aj.frame matches 5 run data modify entity @s Pose.Head set value [107.4f,0f,0f]
execute if score .this aj.frame matches 6 run data modify entity @s Pose.Head set value [128.88f,0f,0f]
execute if score .this aj.frame matches 7 run data modify entity @s Pose.Head set value [150.36f,0f,0f]