#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [-16.32f,0f,0f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [5.16f,0f,0f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [26.64f,0f,0f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [48.12f,0f,0f]
execute if score .this aj.frame matches 20 run data modify entity @s Pose.Head set value [69.6f,0f,0f]
execute if score .this aj.frame matches 21 run data modify entity @s Pose.Head set value [87.5f,0f,0f]