#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [-3.82f,0f,0f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [17.66f,0f,0f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [39.14f,0f,0f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [60.62f,0f,0f]
execute if score .this aj.frame matches 20 run data modify entity @s Pose.Head set value [82.1f,0f,0f]
execute if score .this aj.frame matches 21 run data modify entity @s Pose.Head set value [100f,0f,0f]