#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^-0.125 ^-0.992 ^0.353 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^-0.125 ^-1.327 ^0.363 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^-0.125 ^-1.659 ^0.365 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^-0.125 ^-1.676 ^0.407 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^-0.125 ^-1.686 ^0.444 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^-0.125 ^-1.688 ^0.478 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^-0.125 ^-1.681 ^0.514 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^-0.125 ^-1.666 ^0.553 ~ ~