#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run tp @s ^-0.125 ^-1.646 ^0.599 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^-0.125 ^-1.623 ^0.654 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^-0.125 ^-1.6 ^0.717 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^-0.125 ^-1.581 ^0.788 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^-0.125 ^-1.568 ^0.865 ~ ~
execute if score .this aj.frame matches 21 run tp @s ^-0.125 ^-1.563 ^0.932 ~ ~
execute if score .this aj.frame matches 22 run tp @s ^-0.125 ^-1.563 ^0.932 ~ ~
execute if score .this aj.frame matches 23 run tp @s ^-0.125 ^-1.563 ^0.932 ~ ~