#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [-175.66f,0f,0f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [-154.18f,0f,0f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [-132.7f,0f,0f]
execute if score .this aj.frame matches 11 run data modify entity @s Pose.Head set value [-111.22f,0f,0f]
execute if score .this aj.frame matches 12 run data modify entity @s Pose.Head set value [-89.74f,0f,0f]
execute if score .this aj.frame matches 13 run data modify entity @s Pose.Head set value [-68.26f,0f,0f]
execute if score .this aj.frame matches 14 run data modify entity @s Pose.Head set value [-46.78f,0f,0f]
execute if score .this aj.frame matches 15 run data modify entity @s Pose.Head set value [-25.3f,0f,0f]