#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^-0.125 ^0.309 ^0.125 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^-0.125 ^0.302 ^0.143 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^-0.125 ^0.293 ^0.17 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^-0.125 ^0.277 ^0.203 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^-0.125 ^0.254 ^0.24 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^-0.125 ^-0.011 ^0.275 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^-0.125 ^-0.332 ^0.307 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^-0.125 ^-0.66 ^0.333 ~ ~