#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [12.5f,0f,0f]
execute if score .this aj.frame matches 1 run data modify entity @s Pose.Head set value [33.98f,0f,0f]
execute if score .this aj.frame matches 2 run data modify entity @s Pose.Head set value [55.46f,0f,0f]
execute if score .this aj.frame matches 3 run data modify entity @s Pose.Head set value [76.94f,0f,0f]
execute if score .this aj.frame matches 4 run data modify entity @s Pose.Head set value [98.42f,0f,0f]
execute if score .this aj.frame matches 5 run data modify entity @s Pose.Head set value [119.9f,0f,0f]
execute if score .this aj.frame matches 6 run data modify entity @s Pose.Head set value [141.38f,0f,0f]
execute if score .this aj.frame matches 7 run data modify entity @s Pose.Head set value [162.86f,0f,0f]