#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function sully_boss:animations/death/tree/left_leg_down_display_0-7
execute if score .this aj.frame matches 8..15 run function sully_boss:animations/death/tree/left_leg_down_display_8-15
execute if score .this aj.frame matches 16..23 run function sully_boss:animations/death/tree/left_leg_down_display_16-23
execute if score .this aj.frame matches 24..31 run function sully_boss:animations/death/tree/left_leg_down_display_24-31
execute if score .this aj.frame matches 40 run data modify entity @s Pose.Head set value [90f,0f,0f]