#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^0.313 ^-1.321 ^-0.125 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^0.313 ^-1.32 ^-0.125 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^0.313 ^-1.319 ^-0.125 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^0.313 ^-1.318 ^-0.125 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^0.313 ^-1.317 ^-0.125 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^0.313 ^-1.316 ^-0.125 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^0.313 ^-1.315 ^-0.125 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^0.313 ^-1.314 ^-0.125 ~ ~