#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 24..31 run function sully_boss:animations/death/tree/left_leg_display_24-31
execute if score .this aj.frame matches 32..39 run function sully_boss:animations/death/tree/left_leg_display_32-39
execute if score .this aj.frame matches 40 run data modify entity @s Pose.Head set value [65f,0f,0f]