#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run tp @s ^0.306 ^-1.304 ^0.309 ~ ~
execute if score .this aj.frame matches 33 run tp @s ^0.306 ^-1.322 ^0.345 ~ ~
execute if score .this aj.frame matches 34 run tp @s ^0.306 ^-1.344 ^0.379 ~ ~
execute if score .this aj.frame matches 35 run tp @s ^0.306 ^-1.368 ^0.412 ~ ~
execute if score .this aj.frame matches 36 run tp @s ^0.306 ^-1.394 ^0.443 ~ ~
execute if score .this aj.frame matches 37 run tp @s ^0.306 ^-1.422 ^0.472 ~ ~
execute if score .this aj.frame matches 38 run tp @s ^0.306 ^-1.453 ^0.499 ~ ~
execute if score .this aj.frame matches 39 run tp @s ^0.306 ^-1.485 ^0.524 ~ ~