#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run tp @s ^0.306 ^-1.24 ^0 ~ ~
execute if score .this aj.frame matches 25 run tp @s ^0.306 ^-1.248 ^0.034 ~ ~
execute if score .this aj.frame matches 26 run tp @s ^0.306 ^-1.247 ^0.074 ~ ~
execute if score .this aj.frame matches 27 run tp @s ^0.306 ^-1.249 ^0.115 ~ ~
execute if score .this aj.frame matches 28 run tp @s ^0.306 ^-1.255 ^0.155 ~ ~
execute if score .this aj.frame matches 29 run tp @s ^0.306 ^-1.263 ^0.195 ~ ~
execute if score .this aj.frame matches 30 run tp @s ^0.306 ^-1.274 ^0.234 ~ ~
execute if score .this aj.frame matches 31 run tp @s ^0.306 ^-1.287 ^0.272 ~ ~