#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run tp @s ^0.688 ^-0.365 ^0.063 ~ ~
execute if score .this aj.frame matches 25 run tp @s ^0.688 ^-0.378 ^0.148 ~ ~
execute if score .this aj.frame matches 26 run tp @s ^0.688 ^-0.388 ^0.251 ~ ~
execute if score .this aj.frame matches 27 run tp @s ^0.688 ^-0.405 ^0.352 ~ ~
execute if score .this aj.frame matches 28 run tp @s ^0.688 ^-0.429 ^0.452 ~ ~
execute if score .this aj.frame matches 29 run tp @s ^0.688 ^-0.461 ^0.55 ~ ~
execute if score .this aj.frame matches 30 run tp @s ^0.688 ^-0.499 ^0.646 ~ ~
execute if score .this aj.frame matches 31 run tp @s ^0.688 ^-0.544 ^0.739 ~ ~