#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [-2.346f,0.0498f,0.1257f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [-2.0466f,0.0435f,0.1097f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [-1.7471f,0.0371f,0.0936f]
execute if score .this aj.frame matches 11 run data modify entity @s Pose.Head set value [-1.4476f,0.0307f,0.0776f]
execute if score .this aj.frame matches 12 run data modify entity @s Pose.Head set value [-1.1481f,0.0244f,0.0615f]
execute if score .this aj.frame matches 13 run data modify entity @s Pose.Head set value [-0.8486f,0.018f,0.0455f]
execute if score .this aj.frame matches 14 run data modify entity @s Pose.Head set value [-0.5491f,0.0117f,0.0294f]
execute if score .this aj.frame matches 15 run data modify entity @s Pose.Head set value [-0.2496f,0.0053f,0.0134f]