#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run tp @s ^0.313 ^-1.317 ^-0.125 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^0.313 ^-1.342 ^-0.12 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^0.313 ^-1.369 ^-0.11 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^0.313 ^-1.398 ^-0.093 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^0.313 ^-1.43 ^-0.07 ~ ~
execute if score .this aj.frame matches 21 run tp @s ^0.313 ^-1.468 ^-0.043 ~ ~
execute if score .this aj.frame matches 22 run tp @s ^0.313 ^-1.511 ^-0.012 ~ ~
execute if score .this aj.frame matches 23 run tp @s ^0.313 ^-1.56 ^0.022 ~ ~