#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [1.8f,0f,0f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [12.6f,0f,0f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [23.4f,0f,0f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [34.2f,0f,0f]
execute if score .this aj.frame matches 20 run data modify entity @s Pose.Head set value [45f,0f,0f]
execute if score .this aj.frame matches 21 run data modify entity @s Pose.Head set value [55.8f,0f,0f]
execute if score .this aj.frame matches 22 run data modify entity @s Pose.Head set value [66.6f,0f,0f]
execute if score .this aj.frame matches 23 run data modify entity @s Pose.Head set value [77.4f,0f,0f]