#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run tp @s ^-0.25 ^-0.76 ^0 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^-0.25 ^-0.82 ^0 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^-0.25 ^-0.88 ^0 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^-0.25 ^-0.94 ^0 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^-0.25 ^-1 ^0 ~ ~
execute if score .this aj.frame matches 21 run tp @s ^-0.25 ^-1.06 ^0 ~ ~
execute if score .this aj.frame matches 22 run tp @s ^-0.25 ^-1.12 ^0 ~ ~
execute if score .this aj.frame matches 23 run tp @s ^-0.25 ^-1.18 ^0 ~ ~