#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run tp @s ^-0.812 ^0.115 ^0.063 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^-0.812 ^0.054 ^0.063 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^-0.812 ^-0.005 ^0.063 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^-0.812 ^-0.065 ^0.063 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^-0.812 ^-0.125 ^0.063 ~ ~
execute if score .this aj.frame matches 21 run tp @s ^-0.812 ^-0.185 ^0.063 ~ ~
execute if score .this aj.frame matches 22 run tp @s ^-0.812 ^-0.246 ^0.063 ~ ~
execute if score .this aj.frame matches 23 run tp @s ^-0.812 ^-0.305 ^0.063 ~ ~