#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run tp @s ^-0.812 ^-0.596 ^0.828 ~ ~
execute if score .this aj.frame matches 33 run tp @s ^-0.812 ^-0.654 ^0.913 ~ ~
execute if score .this aj.frame matches 34 run tp @s ^-0.812 ^-0.718 ^0.994 ~ ~
execute if score .this aj.frame matches 35 run tp @s ^-0.812 ^-0.787 ^1.07 ~ ~
execute if score .this aj.frame matches 36 run tp @s ^-0.812 ^-0.862 ^1.14 ~ ~
execute if score .this aj.frame matches 37 run tp @s ^-0.812 ^-0.942 ^1.206 ~ ~
execute if score .this aj.frame matches 38 run tp @s ^-0.812 ^-1.026 ^1.265 ~ ~
execute if score .this aj.frame matches 39 run tp @s ^-0.812 ^-1.114 ^1.318 ~ ~