#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run tp @s ^0 ^-0.323 ^-0.062 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^0 ^-0.383 ^-0.062 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^0 ^-0.443 ^-0.062 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^0 ^-0.503 ^-0.062 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^0 ^-0.563 ^-0.062 ~ ~
execute if score .this aj.frame matches 21 run tp @s ^0 ^-0.623 ^-0.062 ~ ~
execute if score .this aj.frame matches 22 run tp @s ^0 ^-0.683 ^-0.062 ~ ~
execute if score .this aj.frame matches 23 run tp @s ^0 ^-0.743 ^-0.062 ~ ~