#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run tp @s ^0 ^-0.9 ^0.489 ~ ~
execute if score .this aj.frame matches 33 run tp @s ^0 ^-0.933 ^0.553 ~ ~
execute if score .this aj.frame matches 34 run tp @s ^0 ^-0.97 ^0.615 ~ ~
execute if score .this aj.frame matches 35 run tp @s ^0 ^-1.012 ^0.674 ~ ~
execute if score .this aj.frame matches 36 run tp @s ^0 ^-1.058 ^0.73 ~ ~
execute if score .this aj.frame matches 37 run tp @s ^0 ^-1.107 ^0.782 ~ ~
execute if score .this aj.frame matches 38 run tp @s ^0 ^-1.161 ^0.831 ~ ~
execute if score .this aj.frame matches 39 run tp @s ^0 ^-1.217 ^0.875 ~ ~