#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run data modify entity @s Pose.Head set value [32.1579f,0f,0f]
execute if score .this aj.frame matches 33 run data modify entity @s Pose.Head set value [36.2632f,0f,0f]
execute if score .this aj.frame matches 34 run data modify entity @s Pose.Head set value [40.3684f,0f,0f]
execute if score .this aj.frame matches 35 run data modify entity @s Pose.Head set value [44.4737f,0f,0f]
execute if score .this aj.frame matches 36 run data modify entity @s Pose.Head set value [48.5789f,0f,0f]
execute if score .this aj.frame matches 37 run data modify entity @s Pose.Head set value [52.6842f,0f,0f]
execute if score .this aj.frame matches 38 run data modify entity @s Pose.Head set value [56.7895f,0f,0f]
execute if score .this aj.frame matches 39 run data modify entity @s Pose.Head set value [60.8947f,0f,0f]