#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run tp @s ^0 ^-0.803 ^-0.062 ~ ~
execute if score .this aj.frame matches 25 run tp @s ^0 ^-0.807 ^-0.003 ~ ~
execute if score .this aj.frame matches 26 run tp @s ^0 ^-0.805 ^0.07 ~ ~
execute if score .this aj.frame matches 27 run tp @s ^0 ^-0.808 ^0.142 ~ ~
execute if score .this aj.frame matches 28 run tp @s ^0 ^-0.817 ^0.213 ~ ~
execute if score .this aj.frame matches 29 run tp @s ^0 ^-0.83 ^0.284 ~ ~
execute if score .this aj.frame matches 30 run tp @s ^0 ^-0.848 ^0.354 ~ ~
execute if score .this aj.frame matches 31 run tp @s ^0 ^-0.872 ^0.422 ~ ~