#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 25 run data modify entity @s Pose.Head set value [3.4211f,0f,0f]
execute if score .this aj.frame matches 26 run data modify entity @s Pose.Head set value [7.5263f,0f,0f]
execute if score .this aj.frame matches 27 run data modify entity @s Pose.Head set value [11.6316f,0f,0f]
execute if score .this aj.frame matches 28 run data modify entity @s Pose.Head set value [15.7368f,0f,0f]
execute if score .this aj.frame matches 29 run data modify entity @s Pose.Head set value [19.8421f,0f,0f]
execute if score .this aj.frame matches 30 run data modify entity @s Pose.Head set value [23.9474f,0f,0f]
execute if score .this aj.frame matches 31 run data modify entity @s Pose.Head set value [28.0526f,0f,0f]