#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [2.5f,0f,0f]
execute if score .this aj.frame matches 1 run data modify entity @s Pose.Head set value [2.25f,0f,0f]
execute if score .this aj.frame matches 2 run data modify entity @s Pose.Head set value [2f,0f,0f]
execute if score .this aj.frame matches 3 run data modify entity @s Pose.Head set value [1.75f,0f,0f]
execute if score .this aj.frame matches 4 run data modify entity @s Pose.Head set value [1.5f,0f,0f]
execute if score .this aj.frame matches 5 run data modify entity @s Pose.Head set value [1.25f,0f,0f]
execute if score .this aj.frame matches 6 run data modify entity @s Pose.Head set value [1f,0f,0f]
execute if score .this aj.frame matches 7 run data modify entity @s Pose.Head set value [0.75f,0f,0f]