#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^0 ^0.312 ^0.188 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^0 ^0.293 ^0.244 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^0 ^0.274 ^0.3 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^0 ^0.256 ^0.356 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^0 ^0.237 ^0.413 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^0 ^0.218 ^0.469 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^0 ^0.2 ^0.525 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^0 ^0.181 ^0.581 ~ ~