#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run tp @s ^0 ^0.197 ^0.531 ~ ~
execute if score .this aj.frame matches 25 run tp @s ^0 ^0.203 ^0.516 ~ ~
execute if score .this aj.frame matches 26 run tp @s ^0 ^0.208 ^0.5 ~ ~
execute if score .this aj.frame matches 27 run tp @s ^0 ^0.213 ^0.484 ~ ~
execute if score .this aj.frame matches 28 run tp @s ^0 ^0.218 ^0.469 ~ ~
execute if score .this aj.frame matches 29 run tp @s ^0 ^0.223 ^0.453 ~ ~
execute if score .this aj.frame matches 30 run tp @s ^0 ^0.229 ^0.438 ~ ~
execute if score .this aj.frame matches 31 run tp @s ^0 ^0.234 ^0.422 ~ ~