#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [-13.125f,0f,0f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [-13.75f,0f,0f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [-14.375f,0f,0f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [-15f,0f,0f]
execute if score .this aj.frame matches 20 run data modify entity @s Pose.Head set value [-15.625f,0f,0f]
execute if score .this aj.frame matches 21 run data modify entity @s Pose.Head set value [-16.25f,0f,0f]
execute if score .this aj.frame matches 22 run data modify entity @s Pose.Head set value [-16.875f,0f,0f]
execute if score .this aj.frame matches 23 run data modify entity @s Pose.Head set value [-17.5f,0f,0f]