#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^0 ^0.162 ^0.638 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^0 ^0.143 ^0.694 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^0 ^0.125 ^0.75 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^0 ^0.13 ^0.734 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^0 ^0.135 ^0.719 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^0 ^0.14 ^0.703 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^0 ^0.145 ^0.688 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^0 ^0.151 ^0.672 ~ ~