#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run tp @s ^0 ^0.239 ^0.406 ~ ~
execute if score .this aj.frame matches 33 run tp @s ^0 ^0.244 ^0.391 ~ ~
execute if score .this aj.frame matches 34 run tp @s ^0 ^0.25 ^0.375 ~ ~
execute if score .this aj.frame matches 35 run tp @s ^0 ^0.255 ^0.359 ~ ~
execute if score .this aj.frame matches 36 run tp @s ^0 ^0.26 ^0.344 ~ ~
execute if score .this aj.frame matches 37 run tp @s ^0 ^0.265 ^0.328 ~ ~
execute if score .this aj.frame matches 38 run tp @s ^0 ^0.27 ^0.313 ~ ~
execute if score .this aj.frame matches 39 run tp @s ^0 ^0.276 ^0.297 ~ ~