#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run data modify entity @s Pose.Head set value [-16.25f,0f,0f]
execute if score .this aj.frame matches 25 run data modify entity @s Pose.Head set value [-15f,0f,0f]
execute if score .this aj.frame matches 26 run data modify entity @s Pose.Head set value [-13.75f,0f,0f]
execute if score .this aj.frame matches 27 run data modify entity @s Pose.Head set value [-12.5f,0f,0f]
execute if score .this aj.frame matches 28 run data modify entity @s Pose.Head set value [-11.25f,0f,0f]
execute if score .this aj.frame matches 29 run data modify entity @s Pose.Head set value [-10f,0f,0f]
execute if score .this aj.frame matches 30 run data modify entity @s Pose.Head set value [-9.4118f,0f,0f]
execute if score .this aj.frame matches 31 run data modify entity @s Pose.Head set value [-8.8235f,0f,0f]