#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run tp @s ^0 ^0.281 ^0.281 ~ ~
execute if score .this aj.frame matches 41 run tp @s ^0 ^0.286 ^0.266 ~ ~
execute if score .this aj.frame matches 42 run tp @s ^0 ^0.291 ^0.25 ~ ~
execute if score .this aj.frame matches 43 run tp @s ^0 ^0.296 ^0.234 ~ ~
execute if score .this aj.frame matches 44 run tp @s ^0 ^0.302 ^0.219 ~ ~
execute if score .this aj.frame matches 45 run tp @s ^0 ^0.307 ^0.203 ~ ~
execute if score .this aj.frame matches 46 run tp @s ^0 ^0.312 ^0.188 ~ ~
execute if score .this aj.frame matches 47 run tp @s ^0 ^0.312 ^0.188 ~ ~