#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run data modify entity @s Pose.Head set value [-3.5294f,0f,0f]
execute if score .this aj.frame matches 41 run data modify entity @s Pose.Head set value [-2.9412f,0f,0f]
execute if score .this aj.frame matches 42 run data modify entity @s Pose.Head set value [-2.3529f,0f,0f]
execute if score .this aj.frame matches 43 run data modify entity @s Pose.Head set value [-1.7647f,0f,0f]
execute if score .this aj.frame matches 44 run data modify entity @s Pose.Head set value [-1.1765f,0f,0f]
execute if score .this aj.frame matches 45 run data modify entity @s Pose.Head set value [-0.5882f,0f,0f]
execute if score .this aj.frame matches 46 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 47 run data modify entity @s Pose.Head set value [0f,0f,0f]