#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run data modify entity @s Pose.Head set value [-8.2353f,0f,0f]
execute if score .this aj.frame matches 33 run data modify entity @s Pose.Head set value [-7.6471f,0f,0f]
execute if score .this aj.frame matches 34 run data modify entity @s Pose.Head set value [-7.0588f,0f,0f]
execute if score .this aj.frame matches 35 run data modify entity @s Pose.Head set value [-6.4706f,0f,0f]
execute if score .this aj.frame matches 36 run data modify entity @s Pose.Head set value [-5.8824f,0f,0f]
execute if score .this aj.frame matches 37 run data modify entity @s Pose.Head set value [-5.2941f,0f,0f]
execute if score .this aj.frame matches 38 run data modify entity @s Pose.Head set value [-4.7059f,0f,0f]
execute if score .this aj.frame matches 39 run data modify entity @s Pose.Head set value [-4.1176f,0f,0f]