#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run tp @s ^0 ^0.156 ^0.656 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^0 ^0.161 ^0.641 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^0 ^0.166 ^0.625 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^0 ^0.171 ^0.609 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^0 ^0.177 ^0.594 ~ ~
execute if score .this aj.frame matches 21 run tp @s ^0 ^0.182 ^0.578 ~ ~
execute if score .this aj.frame matches 22 run tp @s ^0 ^0.187 ^0.563 ~ ~
execute if score .this aj.frame matches 23 run tp @s ^0 ^0.192 ^0.547 ~ ~