#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run tp @s ^-0.125 ^0.177 ^0.472 ~ ~
execute if score .this aj.frame matches 25 run tp @s ^-0.125 ^0.184 ^0.456 ~ ~
execute if score .this aj.frame matches 26 run tp @s ^-0.125 ^0.19 ^0.44 ~ ~
execute if score .this aj.frame matches 27 run tp @s ^-0.125 ^0.197 ^0.424 ~ ~
execute if score .this aj.frame matches 28 run tp @s ^-0.125 ^0.203 ^0.408 ~ ~
execute if score .this aj.frame matches 29 run tp @s ^-0.125 ^0.21 ^0.392 ~ ~
execute if score .this aj.frame matches 30 run tp @s ^-0.125 ^0.216 ^0.376 ~ ~
execute if score .this aj.frame matches 31 run tp @s ^-0.125 ^0.222 ^0.36 ~ ~