#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run tp @s ^-0.125 ^0.139 ^0.596 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^-0.125 ^0.143 ^0.581 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^-0.125 ^0.148 ^0.565 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^-0.125 ^0.153 ^0.55 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^-0.125 ^0.157 ^0.534 ~ ~
execute if score .this aj.frame matches 21 run tp @s ^-0.125 ^0.162 ^0.519 ~ ~
execute if score .this aj.frame matches 22 run tp @s ^-0.125 ^0.166 ^0.503 ~ ~
execute if score .this aj.frame matches 23 run tp @s ^-0.125 ^0.171 ^0.488 ~ ~