#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run tp @s ^-0.125 ^0.274 ^0.219 ~ ~
execute if score .this aj.frame matches 41 run tp @s ^-0.125 ^0.28 ^0.203 ~ ~
execute if score .this aj.frame matches 42 run tp @s ^-0.125 ^0.286 ^0.188 ~ ~
execute if score .this aj.frame matches 43 run tp @s ^-0.125 ^0.292 ^0.172 ~ ~
execute if score .this aj.frame matches 44 run tp @s ^-0.125 ^0.298 ^0.156 ~ ~
execute if score .this aj.frame matches 45 run tp @s ^-0.125 ^0.303 ^0.141 ~ ~
execute if score .this aj.frame matches 46 run tp @s ^-0.125 ^0.309 ^0.125 ~ ~
execute if score .this aj.frame matches 47 run tp @s ^-0.125 ^0.309 ^0.125 ~ ~