#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run data modify entity @s Pose.Head set value [15.5331f,0f,0f]
execute if score .this aj.frame matches 41 run data modify entity @s Pose.Head set value [15.0276f,0f,0f]
execute if score .this aj.frame matches 42 run data modify entity @s Pose.Head set value [14.5221f,0f,0f]
execute if score .this aj.frame matches 43 run data modify entity @s Pose.Head set value [14.0165f,0f,0f]
execute if score .this aj.frame matches 44 run data modify entity @s Pose.Head set value [13.511f,0f,0f]
execute if score .this aj.frame matches 45 run data modify entity @s Pose.Head set value [13.0055f,0f,0f]
execute if score .this aj.frame matches 46 run data modify entity @s Pose.Head set value [12.5f,0f,0f]
execute if score .this aj.frame matches 47 run data modify entity @s Pose.Head set value [12.5f,0f,0f]