#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^-0.125 ^0.16 ^0.575 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^-0.125 ^0.141 ^0.631 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^-0.125 ^0.122 ^0.687 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^-0.125 ^0.124 ^0.672 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^-0.125 ^0.127 ^0.657 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^-0.125 ^0.129 ^0.641 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^-0.125 ^0.132 ^0.626 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^-0.125 ^0.134 ^0.611 ~ ~