#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run tp @s ^-0.125 ^0.227 ^0.345 ~ ~
execute if score .this aj.frame matches 33 run tp @s ^-0.125 ^0.233 ^0.329 ~ ~
execute if score .this aj.frame matches 34 run tp @s ^-0.125 ^0.239 ^0.313 ~ ~
execute if score .this aj.frame matches 35 run tp @s ^-0.125 ^0.245 ^0.298 ~ ~
execute if score .this aj.frame matches 36 run tp @s ^-0.125 ^0.251 ^0.282 ~ ~
execute if score .this aj.frame matches 37 run tp @s ^-0.125 ^0.257 ^0.266 ~ ~
execute if score .this aj.frame matches 38 run tp @s ^-0.125 ^0.262 ^0.25 ~ ~
execute if score .this aj.frame matches 39 run tp @s ^-0.125 ^0.268 ^0.235 ~ ~