#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run data modify entity @s Pose.Head set value [19.5772f,0f,0f]
execute if score .this aj.frame matches 33 run data modify entity @s Pose.Head set value [19.0717f,0f,0f]
execute if score .this aj.frame matches 34 run data modify entity @s Pose.Head set value [18.5662f,0f,0f]
execute if score .this aj.frame matches 35 run data modify entity @s Pose.Head set value [18.0607f,0f,0f]
execute if score .this aj.frame matches 36 run data modify entity @s Pose.Head set value [17.5551f,0f,0f]
execute if score .this aj.frame matches 37 run data modify entity @s Pose.Head set value [17.0496f,0f,0f]
execute if score .this aj.frame matches 38 run data modify entity @s Pose.Head set value [16.5441f,0f,0f]
execute if score .this aj.frame matches 39 run data modify entity @s Pose.Head set value [16.0386f,0f,0f]