#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^-0.125 ^0.312 ^0.125 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^-0.125 ^0.293 ^0.181 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^-0.125 ^0.274 ^0.237 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^-0.125 ^0.255 ^0.294 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^-0.125 ^0.236 ^0.35 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^-0.125 ^0.217 ^0.406 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^-0.125 ^0.198 ^0.462 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^-0.125 ^0.179 ^0.519 ~ ~