#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run data modify entity @s Pose.Head set value [-148.75f,0f,0f]
execute if score .this aj.frame matches 33 run data modify entity @s Pose.Head set value [-138.125f,0f,0f]
execute if score .this aj.frame matches 34 run data modify entity @s Pose.Head set value [-127.5f,0f,0f]
execute if score .this aj.frame matches 35 run data modify entity @s Pose.Head set value [-116.875f,0f,0f]
execute if score .this aj.frame matches 36 run data modify entity @s Pose.Head set value [-106.25f,0f,0f]
execute if score .this aj.frame matches 37 run data modify entity @s Pose.Head set value [-95.625f,0f,0f]
execute if score .this aj.frame matches 38 run data modify entity @s Pose.Head set value [-85f,0f,0f]
execute if score .this aj.frame matches 39 run data modify entity @s Pose.Head set value [-74.375f,0f,0f]