#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [-169.375f,0f,0f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [-171.25f,0f,0f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [-173.125f,0f,0f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [-175f,0f,0f]
execute if score .this aj.frame matches 20 run data modify entity @s Pose.Head set value [-176.875f,0f,0f]
execute if score .this aj.frame matches 21 run data modify entity @s Pose.Head set value [-178.75f,0f,0f]
execute if score .this aj.frame matches 22 run data modify entity @s Pose.Head set value [179.375f,0f,0f]
execute if score .this aj.frame matches 23 run data modify entity @s Pose.Head set value [177.5f,0f,0f]