#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run data modify entity @s Pose.Head set value [179.2857f,0f,0f]
execute if score .this aj.frame matches 25 run data modify entity @s Pose.Head set value [-178.9286f,0f,0f]
execute if score .this aj.frame matches 26 run data modify entity @s Pose.Head set value [-177.1429f,0f,0f]
execute if score .this aj.frame matches 27 run data modify entity @s Pose.Head set value [-175.3571f,0f,0f]
execute if score .this aj.frame matches 28 run data modify entity @s Pose.Head set value [-173.5714f,0f,0f]
execute if score .this aj.frame matches 29 run data modify entity @s Pose.Head set value [-171.7857f,0f,0f]
execute if score .this aj.frame matches 30 run data modify entity @s Pose.Head set value [-170f,0f,0f]
execute if score .this aj.frame matches 31 run data modify entity @s Pose.Head set value [-159.375f,0f,0f]