#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^0.688 ^0.125 ^0.063 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^0.688 ^0.125 ^0.106 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^0.688 ^0.125 ^0.15 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^0.688 ^0.125 ^0.194 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^0.688 ^0.125 ^0.238 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^0.688 ^0.125 ^0.281 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^0.688 ^0.125 ^0.325 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^0.688 ^0.125 ^0.369 ~ ~