#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run tp @s ^0.688 ^0.125 ^0.445 ~ ~
execute if score .this aj.frame matches 33 run tp @s ^0.688 ^0.125 ^0.418 ~ ~
execute if score .this aj.frame matches 34 run tp @s ^0.688 ^0.125 ^0.391 ~ ~
execute if score .this aj.frame matches 35 run tp @s ^0.688 ^0.125 ^0.363 ~ ~
execute if score .this aj.frame matches 36 run tp @s ^0.688 ^0.125 ^0.336 ~ ~
execute if score .this aj.frame matches 37 run tp @s ^0.688 ^0.125 ^0.309 ~ ~
execute if score .this aj.frame matches 38 run tp @s ^0.688 ^0.125 ^0.281 ~ ~
execute if score .this aj.frame matches 39 run tp @s ^0.688 ^0.125 ^0.254 ~ ~