#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [-89.3333f,0f,0f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [-100.5f,0f,0f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [-111.6667f,0f,0f]
execute if score .this aj.frame matches 11 run data modify entity @s Pose.Head set value [-122.8333f,0f,0f]
execute if score .this aj.frame matches 12 run data modify entity @s Pose.Head set value [-134f,0f,0f]
execute if score .this aj.frame matches 13 run data modify entity @s Pose.Head set value [-145.1667f,0f,0f]
execute if score .this aj.frame matches 14 run data modify entity @s Pose.Head set value [-156.3333f,0f,0f]
execute if score .this aj.frame matches 15 run data modify entity @s Pose.Head set value [-167.5f,0f,0f]