#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run tp @s ^0.688 ^0.125 ^0.227 ~ ~
execute if score .this aj.frame matches 41 run tp @s ^0.688 ^0.125 ^0.199 ~ ~
execute if score .this aj.frame matches 42 run tp @s ^0.688 ^0.125 ^0.172 ~ ~
execute if score .this aj.frame matches 43 run tp @s ^0.688 ^0.125 ^0.145 ~ ~
execute if score .this aj.frame matches 44 run tp @s ^0.688 ^0.125 ^0.117 ~ ~
execute if score .this aj.frame matches 45 run tp @s ^0.688 ^0.125 ^0.09 ~ ~
execute if score .this aj.frame matches 46 run tp @s ^0.688 ^0.125 ^0.063 ~ ~
execute if score .this aj.frame matches 47 run tp @s ^0.688 ^0.125 ^0.063 ~ ~