#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run tp @s ^-0.812 ^0.125 ^0.18 ~ ~
execute if score .this aj.frame matches 41 run tp @s ^-0.812 ^0.125 ^0.16 ~ ~
execute if score .this aj.frame matches 42 run tp @s ^-0.812 ^0.125 ^0.141 ~ ~
execute if score .this aj.frame matches 43 run tp @s ^-0.812 ^0.125 ^0.121 ~ ~
execute if score .this aj.frame matches 44 run tp @s ^-0.812 ^0.125 ^0.102 ~ ~
execute if score .this aj.frame matches 45 run tp @s ^-0.812 ^0.125 ^0.082 ~ ~
execute if score .this aj.frame matches 46 run tp @s ^-0.812 ^0.125 ^0.063 ~ ~
execute if score .this aj.frame matches 47 run tp @s ^-0.812 ^0.125 ^0.063 ~ ~