#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [-90.6667f,0f,0f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [-102f,0f,0f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [-113.3333f,0f,0f]
execute if score .this aj.frame matches 11 run data modify entity @s Pose.Head set value [-124.6667f,0f,0f]
execute if score .this aj.frame matches 12 run data modify entity @s Pose.Head set value [-136f,0f,0f]
execute if score .this aj.frame matches 13 run data modify entity @s Pose.Head set value [-147.3333f,0f,0f]
execute if score .this aj.frame matches 14 run data modify entity @s Pose.Head set value [-158.6667f,0f,0f]
execute if score .this aj.frame matches 15 run data modify entity @s Pose.Head set value [-170f,0f,0f]