#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run data modify entity @s Pose.Head set value [-113.3333f,0f,0f]
execute if score .this aj.frame matches 33 run data modify entity @s Pose.Head set value [-105.2381f,0f,0f]
execute if score .this aj.frame matches 34 run data modify entity @s Pose.Head set value [-97.1429f,0f,0f]
execute if score .this aj.frame matches 35 run data modify entity @s Pose.Head set value [-89.0476f,0f,0f]
execute if score .this aj.frame matches 36 run data modify entity @s Pose.Head set value [-80.9524f,0f,0f]
execute if score .this aj.frame matches 37 run data modify entity @s Pose.Head set value [-72.8571f,0f,0f]
execute if score .this aj.frame matches 38 run data modify entity @s Pose.Head set value [-64.7619f,0f,0f]
execute if score .this aj.frame matches 39 run data modify entity @s Pose.Head set value [-56.6667f,0f,0f]