#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run tp @s ^-0.812 ^0.125 ^0.336 ~ ~
execute if score .this aj.frame matches 33 run tp @s ^-0.812 ^0.125 ^0.316 ~ ~
execute if score .this aj.frame matches 34 run tp @s ^-0.812 ^0.125 ^0.297 ~ ~
execute if score .this aj.frame matches 35 run tp @s ^-0.812 ^0.125 ^0.277 ~ ~
execute if score .this aj.frame matches 36 run tp @s ^-0.812 ^0.125 ^0.258 ~ ~
execute if score .this aj.frame matches 37 run tp @s ^-0.812 ^0.125 ^0.238 ~ ~
execute if score .this aj.frame matches 38 run tp @s ^-0.812 ^0.125 ^0.219 ~ ~
execute if score .this aj.frame matches 39 run tp @s ^-0.812 ^0.125 ^0.199 ~ ~