#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run data modify entity @s Pose.Head set value [-48.5714f,0f,0f]
execute if score .this aj.frame matches 41 run data modify entity @s Pose.Head set value [-40.4762f,0f,0f]
execute if score .this aj.frame matches 42 run data modify entity @s Pose.Head set value [-32.381f,0f,0f]
execute if score .this aj.frame matches 43 run data modify entity @s Pose.Head set value [-24.2857f,0f,0f]
execute if score .this aj.frame matches 44 run data modify entity @s Pose.Head set value [-16.1905f,0f,0f]
execute if score .this aj.frame matches 45 run data modify entity @s Pose.Head set value [-8.0952f,0f,0f]
execute if score .this aj.frame matches 46 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 47 run data modify entity @s Pose.Head set value [0f,0f,0f]