#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run data modify entity @s Pose.Head set value [-172.5f,0f,0f]
execute if score .this aj.frame matches 25 run data modify entity @s Pose.Head set value [-170f,0f,0f]
execute if score .this aj.frame matches 26 run data modify entity @s Pose.Head set value [-161.9048f,0f,0f]
execute if score .this aj.frame matches 27 run data modify entity @s Pose.Head set value [-153.8095f,0f,0f]
execute if score .this aj.frame matches 28 run data modify entity @s Pose.Head set value [-145.7143f,0f,0f]
execute if score .this aj.frame matches 29 run data modify entity @s Pose.Head set value [-137.619f,0f,0f]
execute if score .this aj.frame matches 30 run data modify entity @s Pose.Head set value [-129.5238f,0f,0f]
execute if score .this aj.frame matches 31 run data modify entity @s Pose.Head set value [-121.4286f,0f,0f]