#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [28f,0f,0f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [31.5f,0f,0f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [35f,0f,0f]