#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run tp @s ^0 ^-0.313 ^-0.021 ~ ~
execute if score .this aj.frame matches 41 run tp @s ^0 ^-0.313 ^-0.028 ~ ~
execute if score .this aj.frame matches 42 run tp @s ^0 ^-0.313 ^-0.035 ~ ~
execute if score .this aj.frame matches 43 run tp @s ^0 ^-0.313 ^-0.042 ~ ~
execute if score .this aj.frame matches 44 run tp @s ^0 ^-0.313 ^-0.049 ~ ~
execute if score .this aj.frame matches 45 run tp @s ^0 ^-0.313 ^-0.056 ~ ~
execute if score .this aj.frame matches 46 run tp @s ^0 ^-0.313 ^-0.062 ~ ~
execute if score .this aj.frame matches 47 run tp @s ^0 ^-0.313 ^-0.062 ~ ~