#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run tp @s ^0 ^-0.313 ^0.09 ~ ~
execute if score .this aj.frame matches 25 run tp @s ^0 ^-0.313 ^0.083 ~ ~
execute if score .this aj.frame matches 26 run tp @s ^0 ^-0.313 ^0.076 ~ ~
execute if score .this aj.frame matches 27 run tp @s ^0 ^-0.313 ^0.069 ~ ~
execute if score .this aj.frame matches 28 run tp @s ^0 ^-0.313 ^0.063 ~ ~
execute if score .this aj.frame matches 29 run tp @s ^0 ^-0.313 ^0.056 ~ ~
execute if score .this aj.frame matches 30 run tp @s ^0 ^-0.313 ^0.049 ~ ~
execute if score .this aj.frame matches 31 run tp @s ^0 ^-0.313 ^0.042 ~ ~