#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 29 run data modify entity @s Pose.Head set value [35f,0f,0f]
execute if score .this aj.frame matches 30 run data modify entity @s Pose.Head set value [32.9412f,0f,0f]
execute if score .this aj.frame matches 31 run data modify entity @s Pose.Head set value [30.8824f,0f,0f]