#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run data modify entity @s Pose.Head set value [12.3529f,0f,0f]
execute if score .this aj.frame matches 41 run data modify entity @s Pose.Head set value [10.2941f,0f,0f]
execute if score .this aj.frame matches 42 run data modify entity @s Pose.Head set value [8.2353f,0f,0f]
execute if score .this aj.frame matches 43 run data modify entity @s Pose.Head set value [6.1765f,0f,0f]
execute if score .this aj.frame matches 44 run data modify entity @s Pose.Head set value [4.1176f,0f,0f]
execute if score .this aj.frame matches 45 run data modify entity @s Pose.Head set value [2.0588f,0f,0f]
execute if score .this aj.frame matches 46 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 47 run data modify entity @s Pose.Head set value [0f,0f,0f]