#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run tp @s ^0 ^-0.313 ^0.035 ~ ~
execute if score .this aj.frame matches 33 run tp @s ^0 ^-0.313 ^0.028 ~ ~
execute if score .this aj.frame matches 34 run tp @s ^0 ^-0.313 ^0.021 ~ ~
execute if score .this aj.frame matches 35 run tp @s ^0 ^-0.313 ^0.014 ~ ~
execute if score .this aj.frame matches 36 run tp @s ^0 ^-0.313 ^0.007 ~ ~
execute if score .this aj.frame matches 37 run tp @s ^0 ^-0.313 ^0 ~ ~
execute if score .this aj.frame matches 38 run tp @s ^0 ^-0.313 ^-0.007 ~ ~
execute if score .this aj.frame matches 39 run tp @s ^0 ^-0.313 ^-0.014 ~ ~