#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run tp @s ^0 ^-0.313 ^0.146 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^0 ^-0.313 ^0.139 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^0 ^-0.313 ^0.132 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^0 ^-0.313 ^0.125 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^0 ^-0.313 ^0.118 ~ ~
execute if score .this aj.frame matches 21 run tp @s ^0 ^-0.313 ^0.111 ~ ~
execute if score .this aj.frame matches 22 run tp @s ^0 ^-0.313 ^0.104 ~ ~
execute if score .this aj.frame matches 23 run tp @s ^0 ^-0.313 ^0.097 ~ ~