#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run data modify entity @s Pose.Head set value [28.8235f,0f,0f]
execute if score .this aj.frame matches 33 run data modify entity @s Pose.Head set value [26.7647f,0f,0f]
execute if score .this aj.frame matches 34 run data modify entity @s Pose.Head set value [24.7059f,0f,0f]
execute if score .this aj.frame matches 35 run data modify entity @s Pose.Head set value [22.6471f,0f,0f]
execute if score .this aj.frame matches 36 run data modify entity @s Pose.Head set value [20.5882f,0f,0f]
execute if score .this aj.frame matches 37 run data modify entity @s Pose.Head set value [18.5294f,0f,0f]
execute if score .this aj.frame matches 38 run data modify entity @s Pose.Head set value [16.4706f,0f,0f]
execute if score .this aj.frame matches 39 run data modify entity @s Pose.Head set value [14.4118f,0f,0f]