#Project generated by Animated Java (https://animated-java.dev/)

scoreboard players set # aj.i 1
execute at @s as @e[type=#sully_boss:bone_entities,tag=aj.sully_boss.bone] if score @s aj.id = .this aj.id run function sully_boss:zzz/execute/20