#Project generated by Animated Java (https://animated-java.dev/)

execute if entity @s[tag=aj.sully_boss.anim.walk] at @s run function sully_boss:animations/walk/next_frame
execute if entity @s[tag=aj.sully_boss.anim.idle] at @s run function sully_boss:animations/idle/next_frame
execute if entity @s[tag=aj.sully_boss.anim.death] at @s run function sully_boss:animations/death/next_frame
execute if entity @s[tag=aj.sully_boss.anim.attack] at @s run function sully_boss:animations/attack/next_frame
execute if entity @s[tag=aj.sully_boss.anim.ground_stomp] at @s run function sully_boss:animations/ground_stomp/next_frame
execute if entity @s[tag=aj.sully_boss.anim.roar] at @s run function sully_boss:animations/roar/next_frame
execute if entity @s[tag=aj.sully_boss.anim.sleep] at @s run function sully_boss:animations/sleep/next_frame
execute if entity @s[tag=aj.sully_boss.anim.wake] at @s run function sully_boss:animations/wake/next_frame
scoreboard players operation @s aj.sully_boss.animating = .aj.animation aj.sully_boss.animating