#Project generated by Animated Java (https://animated-java.dev/)

tp @s[tag=aj.sully_boss.bone.h_head] ^0 ^0.312 ^0.188
tp @s[tag=aj.sully_boss.bone.jaw] ^-0.125 ^0.309 ^0.125
tp @s[tag=aj.sully_boss.bone.left_leg] ^0.306 ^-0.75 ^0
tp @s[tag=aj.sully_boss.bone.left_leg_down] ^0.313 ^-1.313 ^-0.125
tp @s[tag=aj.sully_boss.bone.right_leg] ^-0.25 ^-0.75 ^0
tp @s[tag=aj.sully_boss.bone.right_leg_down] ^-0.25 ^-1.313 ^-0.125
tp @s[tag=aj.sully_boss.bone.left_arm] ^0.688 ^0.125 ^0.063
tp @s[tag=aj.sully_boss.bone.right_arm] ^-0.812 ^0.125 ^0.063
tp @s[tag=aj.sully_boss.bone.torso] ^0 ^-0.313 ^-0.062
execute store result score .calc aj.i run data get entity @s Air
execute store result entity @s Air short 1 run scoreboard players add .calc aj.i 2