#Project generated by Animated Java (https://animated-java.dev/)

data modify entity @s[tag=aj.sully_boss.bone.h_head] Pose.Head set value [0f,0f,0f]
data modify entity @s[tag=aj.sully_boss.bone.jaw] Pose.Head set value [12.5f,0f,0f]
data modify entity @s[tag=aj.sully_boss.bone.left_leg] Pose.Head set value [0f,0f,0f]
data modify entity @s[tag=aj.sully_boss.bone.left_leg_down] Pose.Head set value [0f,0f,0f]
data modify entity @s[tag=aj.sully_boss.bone.right_leg] Pose.Head set value [0f,0f,0f]
data modify entity @s[tag=aj.sully_boss.bone.right_leg_down] Pose.Head set value [0f,0f,0f]
data modify entity @s[tag=aj.sully_boss.bone.left_arm] Pose.Head set value [0f,0f,0f]
data modify entity @s[tag=aj.sully_boss.bone.right_arm] Pose.Head set value [0f,0f,0f]
data modify entity @s[tag=aj.sully_boss.bone.torso] Pose.Head set value [0f,0f,0f]
tp @s ~ ~ ~ ~ ~