#Project generated by Animated Java (https://animated-java.dev/)

execute if score @s aj.sully_boss.ground_stomp.loopMode matches 0 run function sully_boss:animations/ground_stomp/stop
execute if score @s aj.sully_boss.ground_stomp.loopMode matches 1 run function sully_boss:animations/ground_stomp/pause
execute if score @s aj.sully_boss.ground_stomp.loopMode matches 2 run function sully_boss:animations/ground_stomp/zzz/execute/38