#Project generated by Animated Java (https://animated-java.dev/)

execute if score @s aj.sully_boss.death.loopMode matches 0 run function sully_boss:animations/death/stop
execute if score @s aj.sully_boss.death.loopMode matches 1 run function sully_boss:animations/death/pause
execute if score @s aj.sully_boss.death.loopMode matches 2 run function sully_boss:animations/death/zzz/execute/36