#Project generated by Animated Java (https://animated-java.dev/)

scoreboard players operation .this aj.id = @s aj.id
scoreboard players operation .this aj.frame = @s aj.frame
execute rotated ~ 0 as @e[type=#sully_boss:bone_entities,tag=aj.sully_boss.bone,distance=..5.233] if score @s aj.id = .this aj.id run function sully_boss:animations/death/tree/trunk
scoreboard players operation @s aj.frame += .aj.sully_boss.framerate aj.i
scoreboard players set .aj.animation aj.sully_boss.animating 1
execute unless score @s aj.frame matches 0..41 run function sully_boss:animations/death/edge