#Project generated by Animated Java (https://animated-java.dev/)

scoreboard players set #execute aj.i 0
execute if entity @s[tag=aj.sully_boss.root] run function sully_boss:animations/death/zzz/conditional/32
execute if score #execute aj.i matches 0 run function sully_boss:animations/death/zzz/conditional/33