#Project generated by Animated Java (https://animated-java.dev/)

tag @s add aj.sully_boss.anim.death
execute if score .aj.anim_loop aj.sully_boss.animating matches 0 run function sully_boss:animation_loop
scoreboard players set #execute aj.i 1