#Project generated by Animated Java (https://animated-java.dev/)

execute if score @s aj.sully_boss.sleep.loopMode matches 0 run function sully_boss:animations/sleep/stop
execute if score @s aj.sully_boss.sleep.loopMode matches 1 run function sully_boss:animations/sleep/pause
execute if score @s aj.sully_boss.sleep.loopMode matches 2 run function sully_boss:animations/sleep/zzz/execute/40