#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run tp @s ^0 ^-0.435 ^-0.052 ~ ~
execute if score .this aj.frame matches 49 run tp @s ^0 ^-0.381 ^-0.045 ~ ~
execute if score .this aj.frame matches 50 run tp @s ^0 ^-0.319 ^-0.034 ~ ~
execute if score .this aj.frame matches 51 run tp @s ^0 ^-0.286 ^-0.023 ~ ~
execute if score .this aj.frame matches 52 run tp @s ^0 ^-0.244 ^-0.011 ~ ~
execute if score .this aj.frame matches 53 run tp @s ^0 ^-0.196 ^0.001 ~ ~
execute if score .this aj.frame matches 54 run tp @s ^0 ^-0.141 ^0.016 ~ ~
execute if score .this aj.frame matches 55 run tp @s ^0 ^-0.079 ^0.033 ~ ~