#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run tp @s ^0 ^-0.588 ^-0.125 ~ ~
execute if score .this aj.frame matches 33 run tp @s ^0 ^-0.585 ^-0.125 ~ ~
execute if score .this aj.frame matches 34 run tp @s ^0 ^-0.582 ^-0.125 ~ ~
execute if score .this aj.frame matches 35 run tp @s ^0 ^-0.579 ^-0.125 ~ ~
execute if score .this aj.frame matches 36 run tp @s ^0 ^-0.575 ^-0.125 ~ ~
execute if score .this aj.frame matches 37 run tp @s ^0 ^-0.572 ^-0.125 ~ ~
execute if score .this aj.frame matches 38 run tp @s ^0 ^-0.569 ^-0.125 ~ ~
execute if score .this aj.frame matches 39 run tp @s ^0 ^-0.566 ^-0.125 ~ ~