#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run tp @s ^0 ^-0.775 ^-0.787 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^0 ^-0.738 ^-0.747 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^0 ^-0.7 ^-0.706 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^0 ^-0.663 ^-0.666 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^0 ^-0.625 ^-0.625 ~ ~
execute if score .this aj.frame matches 21 run tp @s ^0 ^-0.622 ^-0.575 ~ ~
execute if score .this aj.frame matches 22 run tp @s ^0 ^-0.619 ^-0.525 ~ ~
execute if score .this aj.frame matches 23 run tp @s ^0 ^-0.616 ^-0.475 ~ ~