#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^0 ^-1.075 ^-1.112 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^0 ^-1.038 ^-1.072 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^0 ^-1 ^-1.031 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^0 ^-0.963 ^-0.991 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^0 ^-0.925 ^-0.95 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^0 ^-0.888 ^-0.909 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^0 ^-0.85 ^-0.869 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^0 ^-0.813 ^-0.828 ~ ~