#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 56 run tp @s ^0 ^-0.011 ^0.053 ~ ~
execute if score .this aj.frame matches 57 run tp @s ^0 ^0.063 ^0.078 ~ ~
execute if score .this aj.frame matches 58 run tp @s ^0 ^0.142 ^0.108 ~ ~
execute if score .this aj.frame matches 59 run tp @s ^0 ^0.225 ^0.145 ~ ~
execute if score .this aj.frame matches 60 run tp @s ^0 ^0.312 ^0.188 ~ ~
execute if score .this aj.frame matches 61 run tp @s ^0 ^0.312 ^0.188 ~ ~
execute if score .this aj.frame matches 62 run tp @s ^0 ^0.312 ^0.188 ~ ~
execute if score .this aj.frame matches 63 run tp @s ^0 ^0.312 ^0.188 ~ ~