#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^0 ^-1.375 ^-1.437 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^0 ^-1.338 ^-1.397 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^0 ^-1.3 ^-1.356 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^0 ^-1.263 ^-1.316 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^0 ^-1.225 ^-1.275 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^0 ^-1.188 ^-1.234 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^0 ^-1.15 ^-1.194 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^0 ^-1.113 ^-1.153 ~ ~