#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [-99.5f,0f,0f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [-96.625f,0f,0f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [-93.75f,0f,0f]
execute if score .this aj.frame matches 11 run data modify entity @s Pose.Head set value [-90.875f,0f,0f]
execute if score .this aj.frame matches 12 run data modify entity @s Pose.Head set value [-88f,0f,0f]
execute if score .this aj.frame matches 13 run data modify entity @s Pose.Head set value [-85.125f,0f,0f]
execute if score .this aj.frame matches 14 run data modify entity @s Pose.Head set value [-82.25f,0f,0f]
execute if score .this aj.frame matches 15 run data modify entity @s Pose.Head set value [-79.375f,0f,0f]