#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run tp @s ^0 ^-0.563 ^-0.125 ~ ~
execute if score .this aj.frame matches 41 run tp @s ^0 ^-0.576 ^-0.103 ~ ~
execute if score .this aj.frame matches 42 run tp @s ^0 ^-0.581 ^-0.087 ~ ~
execute if score .this aj.frame matches 43 run tp @s ^0 ^-0.578 ^-0.076 ~ ~
execute if score .this aj.frame matches 44 run tp @s ^0 ^-0.566 ^-0.069 ~ ~
execute if score .this aj.frame matches 45 run tp @s ^0 ^-0.546 ^-0.064 ~ ~
execute if score .this aj.frame matches 46 run tp @s ^0 ^-0.518 ^-0.06 ~ ~
execute if score .this aj.frame matches 47 run tp @s ^0 ^-0.481 ^-0.056 ~ ~