#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run tp @s ^0 ^-0.613 ^-0.425 ~ ~
execute if score .this aj.frame matches 25 run tp @s ^0 ^-0.61 ^-0.375 ~ ~
execute if score .this aj.frame matches 26 run tp @s ^0 ^-0.607 ^-0.325 ~ ~
execute if score .this aj.frame matches 27 run tp @s ^0 ^-0.604 ^-0.275 ~ ~
execute if score .this aj.frame matches 28 run tp @s ^0 ^-0.6 ^-0.225 ~ ~
execute if score .this aj.frame matches 29 run tp @s ^0 ^-0.597 ^-0.175 ~ ~
execute if score .this aj.frame matches 30 run tp @s ^0 ^-0.594 ^-0.125 ~ ~
execute if score .this aj.frame matches 31 run tp @s ^0 ^-0.591 ^-0.125 ~ ~