#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [-70.6667f,0f,0f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [-68.2083f,0f,0f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [-65.75f,0f,0f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [-63.2917f,0f,0f]
execute if score .this aj.frame matches 20 run data modify entity @s Pose.Head set value [-60.8333f,0f,0f]
execute if score .this aj.frame matches 21 run data modify entity @s Pose.Head set value [-54.75f,0f,0f]
execute if score .this aj.frame matches 22 run data modify entity @s Pose.Head set value [-48.6667f,0f,0f]
execute if score .this aj.frame matches 23 run data modify entity @s Pose.Head set value [-42.5833f,0f,0f]