#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run tp @s ^-0.125 ^-0.566 ^-0.188 ~ ~
execute if score .this aj.frame matches 41 run tp @s ^-0.125 ^-0.578 ^-0.166 ~ ~
execute if score .this aj.frame matches 42 run tp @s ^-0.125 ^-0.583 ^-0.15 ~ ~
execute if score .this aj.frame matches 43 run tp @s ^-0.125 ^-0.58 ^-0.139 ~ ~
execute if score .this aj.frame matches 44 run tp @s ^-0.125 ^-0.569 ^-0.131 ~ ~
execute if score .this aj.frame matches 45 run tp @s ^-0.125 ^-0.549 ^-0.126 ~ ~
execute if score .this aj.frame matches 46 run tp @s ^-0.125 ^-0.521 ^-0.123 ~ ~
execute if score .this aj.frame matches 47 run tp @s ^-0.125 ^-0.483 ^-0.119 ~ ~