#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run tp @s ^-0.125 ^-0.837 ^-0.799 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^-0.125 ^-0.799 ^-0.762 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^-0.125 ^-0.76 ^-0.724 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^-0.125 ^-0.722 ^-0.687 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^-0.125 ^-0.683 ^-0.649 ~ ~
execute if score .this aj.frame matches 21 run tp @s ^-0.125 ^-0.677 ^-0.605 ~ ~
execute if score .this aj.frame matches 22 run tp @s ^-0.125 ^-0.67 ^-0.561 ~ ~
execute if score .this aj.frame matches 23 run tp @s ^-0.125 ^-0.663 ^-0.517 ~ ~