#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [-90.3333f,0f,0f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [-87.875f,0f,0f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [-85.4167f,0f,0f]
execute if score .this aj.frame matches 11 run data modify entity @s Pose.Head set value [-82.9583f,0f,0f]
execute if score .this aj.frame matches 12 run data modify entity @s Pose.Head set value [-80.5f,0f,0f]
execute if score .this aj.frame matches 13 run data modify entity @s Pose.Head set value [-78.0417f,0f,0f]
execute if score .this aj.frame matches 14 run data modify entity @s Pose.Head set value [-75.5833f,0f,0f]
execute if score .this aj.frame matches 15 run data modify entity @s Pose.Head set value [-73.125f,0f,0f]