#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^-0.125 ^-1.427 ^-1.402 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^-0.125 ^-1.391 ^-1.364 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^-0.125 ^-1.355 ^-1.326 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^-0.125 ^-1.319 ^-1.288 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^-0.125 ^-1.283 ^-1.25 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^-0.125 ^-1.247 ^-1.212 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^-0.125 ^-1.21 ^-1.175 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^-0.125 ^-1.174 ^-1.137 ~ ~