#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run data modify entity @s Pose.Head set value [-36.5f,0f,0f]
execute if score .this aj.frame matches 25 run data modify entity @s Pose.Head set value [-30.4167f,0f,0f]
execute if score .this aj.frame matches 26 run data modify entity @s Pose.Head set value [-24.3333f,0f,0f]
execute if score .this aj.frame matches 27 run data modify entity @s Pose.Head set value [-18.25f,0f,0f]
execute if score .this aj.frame matches 28 run data modify entity @s Pose.Head set value [-12.1667f,0f,0f]
execute if score .this aj.frame matches 29 run data modify entity @s Pose.Head set value [-6.0833f,0f,0f]
execute if score .this aj.frame matches 30 run data modify entity @s Pose.Head set value [0f,0f,0f]