#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run tp @s ^-0.125 ^-0.654 ^-0.472 ~ ~
execute if score .this aj.frame matches 25 run tp @s ^-0.125 ^-0.646 ^-0.426 ~ ~
execute if score .this aj.frame matches 26 run tp @s ^-0.125 ^-0.637 ^-0.38 ~ ~
execute if score .this aj.frame matches 27 run tp @s ^-0.125 ^-0.627 ^-0.333 ~ ~
execute if score .this aj.frame matches 28 run tp @s ^-0.125 ^-0.617 ^-0.285 ~ ~
execute if score .this aj.frame matches 29 run tp @s ^-0.125 ^-0.607 ^-0.237 ~ ~
execute if score .this aj.frame matches 30 run tp @s ^-0.125 ^-0.597 ^-0.188 ~ ~
execute if score .this aj.frame matches 31 run tp @s ^-0.125 ^-0.594 ^-0.188 ~ ~