#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 56 run tp @s ^-0.125 ^-0.014 ^-0.01 ~ ~
execute if score .this aj.frame matches 57 run tp @s ^-0.125 ^0.06 ^0.016 ~ ~
execute if score .this aj.frame matches 58 run tp @s ^-0.125 ^0.139 ^0.046 ~ ~
execute if score .this aj.frame matches 59 run tp @s ^-0.125 ^0.222 ^0.082 ~ ~
execute if score .this aj.frame matches 60 run tp @s ^-0.125 ^0.309 ^0.125 ~ ~
execute if score .this aj.frame matches 61 run tp @s ^-0.125 ^0.309 ^0.125 ~ ~
execute if score .this aj.frame matches 62 run tp @s ^-0.125 ^0.309 ^0.125 ~ ~
execute if score .this aj.frame matches 63 run tp @s ^-0.125 ^0.309 ^0.125 ~ ~