#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [-110f,0f,0f]
execute if score .this aj.frame matches 1 run data modify entity @s Pose.Head set value [-107.5417f,0f,0f]
execute if score .this aj.frame matches 2 run data modify entity @s Pose.Head set value [-105.0833f,0f,0f]
execute if score .this aj.frame matches 3 run data modify entity @s Pose.Head set value [-102.625f,0f,0f]
execute if score .this aj.frame matches 4 run data modify entity @s Pose.Head set value [-100.1667f,0f,0f]
execute if score .this aj.frame matches 5 run data modify entity @s Pose.Head set value [-97.7083f,0f,0f]
execute if score .this aj.frame matches 6 run data modify entity @s Pose.Head set value [-95.25f,0f,0f]
execute if score .this aj.frame matches 7 run data modify entity @s Pose.Head set value [-92.7917f,0f,0f]