#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 64 run data modify entity @s Pose.Head set value [5f,0f,0f]
execute if score .this aj.frame matches 65 run data modify entity @s Pose.Head set value [6.25f,0f,0f]
execute if score .this aj.frame matches 66 run data modify entity @s Pose.Head set value [7.5f,0f,0f]
execute if score .this aj.frame matches 67 run data modify entity @s Pose.Head set value [8.75f,0f,0f]
execute if score .this aj.frame matches 68 run data modify entity @s Pose.Head set value [10f,0f,0f]
execute if score .this aj.frame matches 69 run data modify entity @s Pose.Head set value [11.25f,0f,0f]
execute if score .this aj.frame matches 70 run data modify entity @s Pose.Head set value [12.5f,0f,0f]
execute if score .this aj.frame matches 71 run data modify entity @s Pose.Head set value [12.5f,0f,0f]