#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run tp @s ^-0.125 ^-0.438 ^-0.114 ~ ~
execute if score .this aj.frame matches 49 run tp @s ^-0.125 ^-0.384 ^-0.107 ~ ~
execute if score .this aj.frame matches 50 run tp @s ^-0.125 ^-0.322 ^-0.097 ~ ~
execute if score .this aj.frame matches 51 run tp @s ^-0.125 ^-0.288 ^-0.085 ~ ~
execute if score .this aj.frame matches 52 run tp @s ^-0.125 ^-0.247 ^-0.074 ~ ~
execute if score .this aj.frame matches 53 run tp @s ^-0.125 ^-0.199 ^-0.061 ~ ~
execute if score .this aj.frame matches 54 run tp @s ^-0.125 ^-0.144 ^-0.047 ~ ~
execute if score .this aj.frame matches 55 run tp @s ^-0.125 ^-0.082 ^-0.03 ~ ~