#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^-0.125 ^-1.137 ^-1.099 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^-0.125 ^-1.1 ^-1.062 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^-0.125 ^-1.063 ^-1.024 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^-0.125 ^-1.026 ^-0.987 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^-0.125 ^-0.988 ^-0.949 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^-0.125 ^-0.951 ^-0.912 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^-0.125 ^-0.913 ^-0.874 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^-0.125 ^-0.875 ^-0.837 ~ ~