#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..63 run function sully_boss:animations/wake/tree/left_leg_down_root_0-63
execute if score .this aj.frame matches 64..71 run function sully_boss:animations/wake/tree/left_leg_down_root_64-71