#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run data modify entity @s Pose.Head set value [-20f,0f,0f]
execute if score .this aj.frame matches 41 run data modify entity @s Pose.Head set value [-14.6f,0f,0f]
execute if score .this aj.frame matches 42 run data modify entity @s Pose.Head set value [-9.2f,0f,0f]
execute if score .this aj.frame matches 43 run data modify entity @s Pose.Head set value [-3.8f,0f,0f]
execute if score .this aj.frame matches 44 run data modify entity @s Pose.Head set value [1.6f,0f,0f]
execute if score .this aj.frame matches 45 run data modify entity @s Pose.Head set value [7f,0f,0f]
execute if score .this aj.frame matches 46 run data modify entity @s Pose.Head set value [6.5333f,0f,0f]
execute if score .this aj.frame matches 47 run data modify entity @s Pose.Head set value [6.0667f,0f,0f]