#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run data modify entity @s Pose.Head set value [-77.5f,0f,0f]
execute if score .this aj.frame matches 41 run data modify entity @s Pose.Head set value [-75.875f,0f,0f]
execute if score .this aj.frame matches 42 run data modify entity @s Pose.Head set value [-74.25f,0f,0f]
execute if score .this aj.frame matches 43 run data modify entity @s Pose.Head set value [-72.625f,0f,0f]
execute if score .this aj.frame matches 44 run data modify entity @s Pose.Head set value [-71f,0f,0f]
execute if score .this aj.frame matches 45 run data modify entity @s Pose.Head set value [-69.375f,0f,0f]
execute if score .this aj.frame matches 46 run data modify entity @s Pose.Head set value [-67.75f,0f,0f]
execute if score .this aj.frame matches 47 run data modify entity @s Pose.Head set value [-66.125f,0f,0f]