#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [-85f,0f,0f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [-84.6875f,0f,0f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [-84.375f,0f,0f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [-84.0625f,0f,0f]
execute if score .this aj.frame matches 20 run data modify entity @s Pose.Head set value [-83.75f,0f,0f]
execute if score .this aj.frame matches 21 run data modify entity @s Pose.Head set value [-83.4375f,0f,0f]
execute if score .this aj.frame matches 22 run data modify entity @s Pose.Head set value [-83.125f,0f,0f]
execute if score .this aj.frame matches 23 run data modify entity @s Pose.Head set value [-82.8125f,0f,0f]