#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 56 run data modify entity @s Pose.Head set value [-10.5f,0f,0f]
execute if score .this aj.frame matches 57 run data modify entity @s Pose.Head set value [-7.875f,0f,0f]
execute if score .this aj.frame matches 58 run data modify entity @s Pose.Head set value [-5.25f,0f,0f]
execute if score .this aj.frame matches 59 run data modify entity @s Pose.Head set value [-2.625f,0f,0f]
execute if score .this aj.frame matches 60 run data modify entity @s Pose.Head set value [0f,0f,0f]