#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^0.313 ^-1.812 ^0.179 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^0.313 ^-1.812 ^0.178 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^0.313 ^-1.812 ^0.176 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^0.313 ^-1.812 ^0.175 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^0.313 ^-1.812 ^0.174 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^0.313 ^-1.812 ^0.173 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^0.313 ^-1.812 ^0.172 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^0.313 ^-1.811 ^0.17 ~ ~