#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 56 run tp @s ^0.313 ^-1.471 ^-0.008 ~ ~
execute if score .this aj.frame matches 57 run tp @s ^0.313 ^-1.442 ^-0.05 ~ ~
execute if score .this aj.frame matches 58 run tp @s ^0.313 ^-1.407 ^-0.095 ~ ~
execute if score .this aj.frame matches 59 run tp @s ^0.313 ^-1.364 ^-0.141 ~ ~
execute if score .this aj.frame matches 60 run tp @s ^0.313 ^-1.313 ^-0.187 ~ ~
execute if score .this aj.frame matches 61 run tp @s ^0.313 ^-1.313 ^-0.187 ~ ~
execute if score .this aj.frame matches 62 run tp @s ^0.313 ^-1.313 ^-0.187 ~ ~
execute if score .this aj.frame matches 63 run tp @s ^0.313 ^-1.313 ^-0.187 ~ ~