#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run tp @s ^0.313 ^-1.586 ^0.152 ~ ~
execute if score .this aj.frame matches 49 run tp @s ^0.313 ^-1.548 ^0.153 ~ ~
execute if score .this aj.frame matches 50 run tp @s ^0.313 ^-1.507 ^0.154 ~ ~
execute if score .this aj.frame matches 51 run tp @s ^0.313 ^-1.514 ^0.14 ~ ~
execute if score .this aj.frame matches 52 run tp @s ^0.313 ^-1.517 ^0.121 ~ ~
execute if score .this aj.frame matches 53 run tp @s ^0.313 ^-1.514 ^0.095 ~ ~
execute if score .this aj.frame matches 54 run tp @s ^0.313 ^-1.506 ^0.065 ~ ~
execute if score .this aj.frame matches 55 run tp @s ^0.313 ^-1.492 ^0.03 ~ ~