#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run tp @s ^0.313 ^-1.811 ^0.169 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^0.313 ^-1.811 ^0.168 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^0.313 ^-1.811 ^0.166 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^0.313 ^-1.811 ^0.165 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^0.313 ^-1.811 ^0.164 ~ ~
execute if score .this aj.frame matches 21 run tp @s ^0.313 ^-1.81 ^0.162 ~ ~
execute if score .this aj.frame matches 22 run tp @s ^0.313 ^-1.81 ^0.161 ~ ~
execute if score .this aj.frame matches 23 run tp @s ^0.313 ^-1.81 ^0.16 ~ ~