#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run tp @s ^0.688 ^-0.75 ^-0.187 ~ ~
execute if score .this aj.frame matches 41 run tp @s ^0.688 ^-0.761 ^-0.171 ~ ~
execute if score .this aj.frame matches 42 run tp @s ^0.688 ^-0.765 ^-0.16 ~ ~
execute if score .this aj.frame matches 43 run tp @s ^0.688 ^-0.761 ^-0.154 ~ ~
execute if score .this aj.frame matches 44 run tp @s ^0.688 ^-0.75 ^-0.152 ~ ~
execute if score .this aj.frame matches 45 run tp @s ^0.688 ^-0.729 ^-0.153 ~ ~
execute if score .this aj.frame matches 46 run tp @s ^0.688 ^-0.675 ^-0.151 ~ ~
execute if score .this aj.frame matches 47 run tp @s ^0.688 ^-0.613 ^-0.146 ~ ~