#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 56 run data modify entity @s Pose.Head set value [1.8667f,0f,0f]
execute if score .this aj.frame matches 57 run data modify entity @s Pose.Head set value [1.4f,0f,0f]
execute if score .this aj.frame matches 58 run data modify entity @s Pose.Head set value [0.9333f,0f,0f]
execute if score .this aj.frame matches 59 run data modify entity @s Pose.Head set value [0.4667f,0f,0f]
execute if score .this aj.frame matches 60 run data modify entity @s Pose.Head set value [0f,0f,0f]