#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^0.688 ^-1.263 ^-1 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^0.688 ^-1.225 ^-0.969 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^0.688 ^-1.188 ^-0.937 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^0.688 ^-1.15 ^-0.906 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^0.688 ^-1.113 ^-0.875 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^0.688 ^-1.075 ^-0.844 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^0.688 ^-1.038 ^-0.812 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^0.688 ^-1 ^-0.781 ~ ~