#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run data modify entity @s Pose.Head set value [-36f,0f,0f]
execute if score .this aj.frame matches 33 run data modify entity @s Pose.Head set value [-34f,0f,0f]
execute if score .this aj.frame matches 34 run data modify entity @s Pose.Head set value [-32f,0f,0f]
execute if score .this aj.frame matches 35 run data modify entity @s Pose.Head set value [-30f,0f,0f]
execute if score .this aj.frame matches 36 run data modify entity @s Pose.Head set value [-28f,0f,0f]
execute if score .this aj.frame matches 37 run data modify entity @s Pose.Head set value [-26f,0f,0f]
execute if score .this aj.frame matches 38 run data modify entity @s Pose.Head set value [-24f,0f,0f]
execute if score .this aj.frame matches 39 run data modify entity @s Pose.Head set value [-22f,0f,0f]