#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run tp @s ^0.688 ^-0.963 ^-0.75 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^0.688 ^-0.925 ^-0.719 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^0.688 ^-0.888 ^-0.687 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^0.688 ^-0.85 ^-0.656 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^0.688 ^-0.813 ^-0.625 ~ ~
execute if score .this aj.frame matches 21 run tp @s ^0.688 ^-0.81 ^-0.594 ~ ~
execute if score .this aj.frame matches 22 run tp @s ^0.688 ^-0.807 ^-0.562 ~ ~
execute if score .this aj.frame matches 23 run tp @s ^0.688 ^-0.804 ^-0.531 ~ ~