#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run tp @s ^0.313 ^-1.805 ^0.134 ~ ~
execute if score .this aj.frame matches 41 run tp @s ^0.313 ^-1.787 ^0.139 ~ ~
execute if score .this aj.frame matches 42 run tp @s ^0.313 ^-1.766 ^0.143 ~ ~
execute if score .this aj.frame matches 43 run tp @s ^0.313 ^-1.742 ^0.146 ~ ~
execute if score .this aj.frame matches 44 run tp @s ^0.313 ^-1.716 ^0.148 ~ ~
execute if score .this aj.frame matches 45 run tp @s ^0.313 ^-1.687 ^0.149 ~ ~
execute if score .this aj.frame matches 46 run tp @s ^0.313 ^-1.656 ^0.15 ~ ~
execute if score .this aj.frame matches 47 run tp @s ^0.313 ^-1.622 ^0.151 ~ ~