#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run tp @s ^0.688 ^-0.8 ^-0.5 ~ ~
execute if score .this aj.frame matches 25 run tp @s ^0.688 ^-0.797 ^-0.469 ~ ~
execute if score .this aj.frame matches 26 run tp @s ^0.688 ^-0.794 ^-0.437 ~ ~
execute if score .this aj.frame matches 27 run tp @s ^0.688 ^-0.791 ^-0.406 ~ ~
execute if score .this aj.frame matches 28 run tp @s ^0.688 ^-0.788 ^-0.375 ~ ~
execute if score .this aj.frame matches 29 run tp @s ^0.688 ^-0.785 ^-0.344 ~ ~
execute if score .this aj.frame matches 30 run tp @s ^0.688 ^-0.782 ^-0.312 ~ ~
execute if score .this aj.frame matches 31 run tp @s ^0.688 ^-0.779 ^-0.3 ~ ~