#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run data modify entity @s Pose.Head set value [-82.5f,0f,0f]
execute if score .this aj.frame matches 25 run data modify entity @s Pose.Head set value [-82.1875f,0f,0f]
execute if score .this aj.frame matches 26 run data modify entity @s Pose.Head set value [-81.875f,0f,0f]
execute if score .this aj.frame matches 27 run data modify entity @s Pose.Head set value [-81.5625f,0f,0f]
execute if score .this aj.frame matches 28 run data modify entity @s Pose.Head set value [-81.25f,0f,0f]
execute if score .this aj.frame matches 29 run data modify entity @s Pose.Head set value [-80.9375f,0f,0f]
execute if score .this aj.frame matches 30 run data modify entity @s Pose.Head set value [-80.625f,0f,0f]
execute if score .this aj.frame matches 31 run data modify entity @s Pose.Head set value [-80.3125f,0f,0f]