#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [-90f,0f,0f]
execute if score .this aj.frame matches 1 run data modify entity @s Pose.Head set value [-88.25f,0f,0f]
execute if score .this aj.frame matches 2 run data modify entity @s Pose.Head set value [-86.5f,0f,0f]
execute if score .this aj.frame matches 3 run data modify entity @s Pose.Head set value [-84.75f,0f,0f]
execute if score .this aj.frame matches 4 run data modify entity @s Pose.Head set value [-83f,0f,0f]
execute if score .this aj.frame matches 5 run data modify entity @s Pose.Head set value [-81.25f,0f,0f]
execute if score .this aj.frame matches 6 run data modify entity @s Pose.Head set value [-79.5f,0f,0f]
execute if score .this aj.frame matches 7 run data modify entity @s Pose.Head set value [-77.75f,0f,0f]