#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run tp @s ^0.313 ^-1.81 ^0.158 ~ ~
execute if score .this aj.frame matches 25 run tp @s ^0.313 ^-1.81 ^0.157 ~ ~
execute if score .this aj.frame matches 26 run tp @s ^0.313 ^-1.809 ^0.155 ~ ~
execute if score .this aj.frame matches 27 run tp @s ^0.313 ^-1.809 ^0.154 ~ ~
execute if score .this aj.frame matches 28 run tp @s ^0.313 ^-1.809 ^0.152 ~ ~
execute if score .this aj.frame matches 29 run tp @s ^0.313 ^-1.809 ^0.151 ~ ~
execute if score .this aj.frame matches 30 run tp @s ^0.313 ^-1.808 ^0.149 ~ ~
execute if score .this aj.frame matches 31 run tp @s ^0.313 ^-1.808 ^0.148 ~ ~