#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^0.306 ^-1.6 ^-0.375 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^0.306 ^-1.597 ^-0.375 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^0.306 ^-1.594 ^-0.375 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^0.306 ^-1.591 ^-0.375 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^0.306 ^-1.588 ^-0.375 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^0.306 ^-1.585 ^-0.375 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^0.306 ^-1.582 ^-0.375 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^0.306 ^-1.579 ^-0.375 ~ ~