#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run data modify entity @s Pose.Head set value [-64.5f,0f,0f]
execute if score .this aj.frame matches 49 run data modify entity @s Pose.Head set value [-62.875f,0f,0f]
execute if score .this aj.frame matches 50 run data modify entity @s Pose.Head set value [-61.25f,0f,0f]
execute if score .this aj.frame matches 51 run data modify entity @s Pose.Head set value [-55.125f,0f,0f]
execute if score .this aj.frame matches 52 run data modify entity @s Pose.Head set value [-49f,0f,0f]
execute if score .this aj.frame matches 53 run data modify entity @s Pose.Head set value [-42.875f,0f,0f]
execute if score .this aj.frame matches 54 run data modify entity @s Pose.Head set value [-36.75f,0f,0f]
execute if score .this aj.frame matches 55 run data modify entity @s Pose.Head set value [-30.625f,0f,0f]