#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run data modify entity @s Pose.Head set value [-80f,0f,0f]
execute if score .this aj.frame matches 33 run data modify entity @s Pose.Head set value [-79.6875f,0f,0f]
execute if score .this aj.frame matches 34 run data modify entity @s Pose.Head set value [-79.375f,0f,0f]
execute if score .this aj.frame matches 35 run data modify entity @s Pose.Head set value [-79.0625f,0f,0f]
execute if score .this aj.frame matches 36 run data modify entity @s Pose.Head set value [-78.75f,0f,0f]
execute if score .this aj.frame matches 37 run data modify entity @s Pose.Head set value [-78.4375f,0f,0f]
execute if score .this aj.frame matches 38 run data modify entity @s Pose.Head set value [-78.125f,0f,0f]
execute if score .this aj.frame matches 39 run data modify entity @s Pose.Head set value [-77.8125f,0f,0f]