#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run tp @s ^0.306 ^-1.252 ^-0.182 ~ ~
execute if score .this aj.frame matches 49 run tp @s ^0.306 ^-1.217 ^-0.163 ~ ~
execute if score .this aj.frame matches 50 run tp @s ^0.306 ^-1.181 ^-0.145 ~ ~
execute if score .this aj.frame matches 51 run tp @s ^0.306 ^-1.144 ^-0.128 ~ ~
execute if score .this aj.frame matches 52 run tp @s ^0.306 ^-1.106 ^-0.112 ~ ~
execute if score .this aj.frame matches 53 run tp @s ^0.306 ^-1.066 ^-0.096 ~ ~
execute if score .this aj.frame matches 54 run tp @s ^0.306 ^-1.025 ^-0.081 ~ ~
execute if score .this aj.frame matches 55 run tp @s ^0.306 ^-0.983 ^-0.067 ~ ~