#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run data modify entity @s Pose.Head set value [5.6f,0f,0f]
execute if score .this aj.frame matches 49 run data modify entity @s Pose.Head set value [5.1333f,0f,0f]
execute if score .this aj.frame matches 50 run data modify entity @s Pose.Head set value [4.6667f,0f,0f]
execute if score .this aj.frame matches 51 run data modify entity @s Pose.Head set value [4.2f,0f,0f]
execute if score .this aj.frame matches 52 run data modify entity @s Pose.Head set value [3.7333f,0f,0f]
execute if score .this aj.frame matches 53 run data modify entity @s Pose.Head set value [3.2667f,0f,0f]
execute if score .this aj.frame matches 54 run data modify entity @s Pose.Head set value [2.8f,0f,0f]
execute if score .this aj.frame matches 55 run data modify entity @s Pose.Head set value [2.3333f,0f,0f]