#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run tp @s ^0.313 ^-1.808 ^0.146 ~ ~
execute if score .this aj.frame matches 33 run tp @s ^0.313 ^-1.808 ^0.145 ~ ~
execute if score .this aj.frame matches 34 run tp @s ^0.313 ^-1.807 ^0.143 ~ ~
execute if score .this aj.frame matches 35 run tp @s ^0.313 ^-1.807 ^0.142 ~ ~
execute if score .this aj.frame matches 36 run tp @s ^0.313 ^-1.807 ^0.14 ~ ~
execute if score .this aj.frame matches 37 run tp @s ^0.313 ^-1.806 ^0.139 ~ ~
execute if score .this aj.frame matches 38 run tp @s ^0.313 ^-1.806 ^0.137 ~ ~
execute if score .this aj.frame matches 39 run tp @s ^0.313 ^-1.806 ^0.135 ~ ~