#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^0.688 ^-1.563 ^-1.25 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^0.688 ^-1.525 ^-1.219 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^0.688 ^-1.488 ^-1.187 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^0.688 ^-1.45 ^-1.156 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^0.688 ^-1.413 ^-1.125 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^0.688 ^-1.375 ^-1.094 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^0.688 ^-1.338 ^-1.062 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^0.688 ^-1.3 ^-1.031 ~ ~