#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run tp @s ^0.688 ^-0.543 ^-0.136 ~ ~
execute if score .this aj.frame matches 49 run tp @s ^0.688 ^-0.467 ^-0.122 ~ ~
execute if score .this aj.frame matches 50 run tp @s ^0.688 ^-0.386 ^-0.101 ~ ~
execute if score .this aj.frame matches 51 run tp @s ^0.688 ^-0.363 ^-0.084 ~ ~
execute if score .this aj.frame matches 52 run tp @s ^0.688 ^-0.334 ^-0.07 ~ ~
execute if score .this aj.frame matches 53 run tp @s ^0.688 ^-0.298 ^-0.057 ~ ~
execute if score .this aj.frame matches 54 run tp @s ^0.688 ^-0.256 ^-0.045 ~ ~
execute if score .this aj.frame matches 55 run tp @s ^0.688 ^-0.208 ^-0.033 ~ ~