#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run tp @s ^0.306 ^-1.5 ^-0.375 ~ ~
execute if score .this aj.frame matches 41 run tp @s ^0.306 ^-1.472 ^-0.346 ~ ~
execute if score .this aj.frame matches 42 run tp @s ^0.306 ^-1.442 ^-0.319 ~ ~
execute if score .this aj.frame matches 43 run tp @s ^0.306 ^-1.413 ^-0.293 ~ ~
execute if score .this aj.frame matches 44 run tp @s ^0.306 ^-1.382 ^-0.268 ~ ~
execute if score .this aj.frame matches 45 run tp @s ^0.306 ^-1.351 ^-0.245 ~ ~
execute if score .this aj.frame matches 46 run tp @s ^0.306 ^-1.319 ^-0.223 ~ ~
execute if score .this aj.frame matches 47 run tp @s ^0.306 ^-1.286 ^-0.202 ~ ~