#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run data modify entity @s Pose.Head set value [-36.5f,0f,0f]
execute if score .this aj.frame matches 49 run data modify entity @s Pose.Head set value [-31.375f,0f,0f]
execute if score .this aj.frame matches 50 run data modify entity @s Pose.Head set value [-26.25f,0f,0f]
execute if score .this aj.frame matches 51 run data modify entity @s Pose.Head set value [-23.625f,0f,0f]
execute if score .this aj.frame matches 52 run data modify entity @s Pose.Head set value [-21f,0f,0f]
execute if score .this aj.frame matches 53 run data modify entity @s Pose.Head set value [-18.375f,0f,0f]
execute if score .this aj.frame matches 54 run data modify entity @s Pose.Head set value [-15.75f,0f,0f]
execute if score .this aj.frame matches 55 run data modify entity @s Pose.Head set value [-13.125f,0f,0f]