#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run tp @s ^0.306 ^-1.525 ^-0.375 ~ ~
execute if score .this aj.frame matches 33 run tp @s ^0.306 ^-1.522 ^-0.375 ~ ~
execute if score .this aj.frame matches 34 run tp @s ^0.306 ^-1.519 ^-0.375 ~ ~
execute if score .this aj.frame matches 35 run tp @s ^0.306 ^-1.516 ^-0.375 ~ ~
execute if score .this aj.frame matches 36 run tp @s ^0.306 ^-1.513 ^-0.375 ~ ~
execute if score .this aj.frame matches 37 run tp @s ^0.306 ^-1.51 ^-0.375 ~ ~
execute if score .this aj.frame matches 38 run tp @s ^0.306 ^-1.507 ^-0.375 ~ ~
execute if score .this aj.frame matches 39 run tp @s ^0.306 ^-1.504 ^-0.375 ~ ~