#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run tp @s ^0.688 ^-0.775 ^-0.287 ~ ~
execute if score .this aj.frame matches 33 run tp @s ^0.688 ^-0.772 ^-0.275 ~ ~
execute if score .this aj.frame matches 34 run tp @s ^0.688 ^-0.769 ^-0.262 ~ ~
execute if score .this aj.frame matches 35 run tp @s ^0.688 ^-0.766 ^-0.25 ~ ~
execute if score .this aj.frame matches 36 run tp @s ^0.688 ^-0.763 ^-0.237 ~ ~
execute if score .this aj.frame matches 37 run tp @s ^0.688 ^-0.76 ^-0.225 ~ ~
execute if score .this aj.frame matches 38 run tp @s ^0.688 ^-0.757 ^-0.212 ~ ~
execute if score .this aj.frame matches 39 run tp @s ^0.688 ^-0.754 ^-0.2 ~ ~