#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run tp @s ^-0.25 ^-1.783 ^0.146 ~ ~
execute if score .this aj.frame matches 41 run tp @s ^-0.25 ^-1.765 ^0.149 ~ ~
execute if score .this aj.frame matches 42 run tp @s ^-0.25 ^-1.744 ^0.151 ~ ~
execute if score .this aj.frame matches 43 run tp @s ^-0.25 ^-1.72 ^0.152 ~ ~
execute if score .this aj.frame matches 44 run tp @s ^-0.25 ^-1.693 ^0.153 ~ ~
execute if score .this aj.frame matches 45 run tp @s ^-0.25 ^-1.664 ^0.154 ~ ~
execute if score .this aj.frame matches 46 run tp @s ^-0.25 ^-1.632 ^0.156 ~ ~
execute if score .this aj.frame matches 47 run tp @s ^-0.25 ^-1.598 ^0.158 ~ ~