#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run data modify entity @s Pose.Head set value [-82f,0f,0f]
execute if score .this aj.frame matches 33 run data modify entity @s Pose.Head set value [-81.75f,0f,0f]
execute if score .this aj.frame matches 34 run data modify entity @s Pose.Head set value [-81.5f,0f,0f]
execute if score .this aj.frame matches 35 run data modify entity @s Pose.Head set value [-81.25f,0f,0f]
execute if score .this aj.frame matches 36 run data modify entity @s Pose.Head set value [-81f,0f,0f]
execute if score .this aj.frame matches 37 run data modify entity @s Pose.Head set value [-80.75f,0f,0f]
execute if score .this aj.frame matches 38 run data modify entity @s Pose.Head set value [-80.5f,0f,0f]
execute if score .this aj.frame matches 39 run data modify entity @s Pose.Head set value [-80.25f,0f,0f]