#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [-88f,0f,0f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [-87.75f,0f,0f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [-87.5f,0f,0f]
execute if score .this aj.frame matches 11 run data modify entity @s Pose.Head set value [-87.25f,0f,0f]
execute if score .this aj.frame matches 12 run data modify entity @s Pose.Head set value [-87f,0f,0f]
execute if score .this aj.frame matches 13 run data modify entity @s Pose.Head set value [-86.75f,0f,0f]
execute if score .this aj.frame matches 14 run data modify entity @s Pose.Head set value [-86.5f,0f,0f]
execute if score .this aj.frame matches 15 run data modify entity @s Pose.Head set value [-86.25f,0f,0f]