#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run tp @s ^-0.25 ^-1.796 ^0.165 ~ ~
execute if score .this aj.frame matches 25 run tp @s ^-0.25 ^-1.795 ^0.164 ~ ~
execute if score .this aj.frame matches 26 run tp @s ^-0.25 ^-1.794 ^0.163 ~ ~
execute if score .this aj.frame matches 27 run tp @s ^-0.25 ^-1.793 ^0.162 ~ ~
execute if score .this aj.frame matches 28 run tp @s ^-0.25 ^-1.793 ^0.16 ~ ~
execute if score .this aj.frame matches 29 run tp @s ^-0.25 ^-1.792 ^0.159 ~ ~
execute if score .this aj.frame matches 30 run tp @s ^-0.25 ^-1.791 ^0.158 ~ ~
execute if score .this aj.frame matches 31 run tp @s ^-0.25 ^-1.79 ^0.157 ~ ~