#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run tp @s ^-0.25 ^-1.802 ^0.173 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^-0.25 ^-1.801 ^0.172 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^-0.25 ^-1.8 ^0.171 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^-0.25 ^-1.8 ^0.17 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^-0.25 ^-1.799 ^0.169 ~ ~
execute if score .this aj.frame matches 21 run tp @s ^-0.25 ^-1.798 ^0.168 ~ ~
execute if score .this aj.frame matches 22 run tp @s ^-0.25 ^-1.797 ^0.167 ~ ~
execute if score .this aj.frame matches 23 run tp @s ^-0.25 ^-1.797 ^0.166 ~ ~