#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run tp @s ^-0.25 ^-1.575 ^-0.375 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^-0.25 ^-1.572 ^-0.375 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^-0.25 ^-1.569 ^-0.375 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^-0.25 ^-1.566 ^-0.375 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^-0.25 ^-1.563 ^-0.375 ~ ~
execute if score .this aj.frame matches 21 run tp @s ^-0.25 ^-1.56 ^-0.375 ~ ~
execute if score .this aj.frame matches 22 run tp @s ^-0.25 ^-1.557 ^-0.375 ~ ~
execute if score .this aj.frame matches 23 run tp @s ^-0.25 ^-1.554 ^-0.375 ~ ~