#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run data modify entity @s Pose.Head set value [-49f,0f,0f]
execute if score .this aj.frame matches 25 run data modify entity @s Pose.Head set value [-48.75f,0f,0f]
execute if score .this aj.frame matches 26 run data modify entity @s Pose.Head set value [-48.5f,0f,0f]
execute if score .this aj.frame matches 27 run data modify entity @s Pose.Head set value [-48.25f,0f,0f]
execute if score .this aj.frame matches 28 run data modify entity @s Pose.Head set value [-48f,0f,0f]
execute if score .this aj.frame matches 29 run data modify entity @s Pose.Head set value [-47.75f,0f,0f]
execute if score .this aj.frame matches 30 run data modify entity @s Pose.Head set value [-47.5f,0f,0f]
execute if score .this aj.frame matches 31 run data modify entity @s Pose.Head set value [-45.25f,0f,0f]