#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run tp @s ^-0.25 ^-1.55 ^-0.375 ~ ~
execute if score .this aj.frame matches 25 run tp @s ^-0.25 ^-1.547 ^-0.375 ~ ~
execute if score .this aj.frame matches 26 run tp @s ^-0.25 ^-1.544 ^-0.375 ~ ~
execute if score .this aj.frame matches 27 run tp @s ^-0.25 ^-1.541 ^-0.375 ~ ~
execute if score .this aj.frame matches 28 run tp @s ^-0.25 ^-1.538 ^-0.375 ~ ~
execute if score .this aj.frame matches 29 run tp @s ^-0.25 ^-1.535 ^-0.375 ~ ~
execute if score .this aj.frame matches 30 run tp @s ^-0.25 ^-1.532 ^-0.375 ~ ~
execute if score .this aj.frame matches 31 run tp @s ^-0.25 ^-1.529 ^-0.375 ~ ~