#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run tp @s ^-0.812 ^-0.543 ^-0.222 ~ ~
execute if score .this aj.frame matches 49 run tp @s ^-0.812 ^-0.477 ^-0.197 ~ ~
execute if score .this aj.frame matches 50 run tp @s ^-0.812 ^-0.408 ^-0.167 ~ ~
execute if score .this aj.frame matches 51 run tp @s ^-0.812 ^-0.378 ^-0.145 ~ ~
execute if score .this aj.frame matches 52 run tp @s ^-0.812 ^-0.343 ^-0.125 ~ ~
execute if score .this aj.frame matches 53 run tp @s ^-0.812 ^-0.302 ^-0.106 ~ ~
execute if score .this aj.frame matches 54 run tp @s ^-0.812 ^-0.256 ^-0.087 ~ ~
execute if score .this aj.frame matches 55 run tp @s ^-0.812 ^-0.205 ^-0.067 ~ ~