#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run data modify entity @s Pose.Head set value [-84f,0f,0f]
execute if score .this aj.frame matches 25 run data modify entity @s Pose.Head set value [-83.75f,0f,0f]
execute if score .this aj.frame matches 26 run data modify entity @s Pose.Head set value [-83.5f,0f,0f]
execute if score .this aj.frame matches 27 run data modify entity @s Pose.Head set value [-83.25f,0f,0f]
execute if score .this aj.frame matches 28 run data modify entity @s Pose.Head set value [-83f,0f,0f]
execute if score .this aj.frame matches 29 run data modify entity @s Pose.Head set value [-82.75f,0f,0f]
execute if score .this aj.frame matches 30 run data modify entity @s Pose.Head set value [-82.5f,0f,0f]
execute if score .this aj.frame matches 31 run data modify entity @s Pose.Head set value [-82.25f,0f,0f]