#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 56 run data modify entity @s Pose.Head set value [2.7333f,0f,0f]
execute if score .this aj.frame matches 57 run data modify entity @s Pose.Head set value [2.05f,0f,0f]
execute if score .this aj.frame matches 58 run data modify entity @s Pose.Head set value [1.3667f,0f,0f]
execute if score .this aj.frame matches 59 run data modify entity @s Pose.Head set value [0.6833f,0f,0f]
execute if score .this aj.frame matches 60 run data modify entity @s Pose.Head set value [0f,0f,0f]