#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run data modify entity @s Pose.Head set value [8.2f,0f,0f]
execute if score .this aj.frame matches 49 run data modify entity @s Pose.Head set value [7.5167f,0f,0f]
execute if score .this aj.frame matches 50 run data modify entity @s Pose.Head set value [6.8333f,0f,0f]
execute if score .this aj.frame matches 51 run data modify entity @s Pose.Head set value [6.15f,0f,0f]
execute if score .this aj.frame matches 52 run data modify entity @s Pose.Head set value [5.4667f,0f,0f]
execute if score .this aj.frame matches 53 run data modify entity @s Pose.Head set value [4.7833f,0f,0f]
execute if score .this aj.frame matches 54 run data modify entity @s Pose.Head set value [4.1f,0f,0f]
execute if score .this aj.frame matches 55 run data modify entity @s Pose.Head set value [3.4167f,0f,0f]