#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 56 run tp @s ^-0.25 ^-0.939 ^-0.053 ~ ~
execute if score .this aj.frame matches 57 run tp @s ^-0.25 ^-0.894 ^-0.039 ~ ~
execute if score .this aj.frame matches 58 run tp @s ^-0.25 ^-0.848 ^-0.026 ~ ~
execute if score .this aj.frame matches 59 run tp @s ^-0.25 ^-0.8 ^-0.013 ~ ~
execute if score .this aj.frame matches 60 run tp @s ^-0.25 ^-0.75 ^0 ~ ~
execute if score .this aj.frame matches 61 run tp @s ^-0.25 ^-0.75 ^0 ~ ~
execute if score .this aj.frame matches 62 run tp @s ^-0.25 ^-0.75 ^0 ~ ~
execute if score .this aj.frame matches 63 run tp @s ^-0.25 ^-0.75 ^0 ~ ~