#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^-0.812 ^-1.625 ^-1.25 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^-0.812 ^-1.591 ^-1.222 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^-0.812 ^-1.557 ^-1.194 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^-0.812 ^-1.522 ^-1.166 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^-0.812 ^-1.488 ^-1.137 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^-0.812 ^-1.454 ^-1.109 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^-0.812 ^-1.419 ^-1.081 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^-0.812 ^-1.385 ^-1.053 ~ ~