#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [-58f,0f,0f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [-56f,0f,0f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [-54f,0f,0f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [-52f,0f,0f]
execute if score .this aj.frame matches 20 run data modify entity @s Pose.Head set value [-50f,0f,0f]
execute if score .this aj.frame matches 21 run data modify entity @s Pose.Head set value [-49.75f,0f,0f]
execute if score .this aj.frame matches 22 run data modify entity @s Pose.Head set value [-49.5f,0f,0f]
execute if score .this aj.frame matches 23 run data modify entity @s Pose.Head set value [-49.25f,0f,0f]