#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run tp @s ^-0.25 ^-1.789 ^0.156 ~ ~
execute if score .this aj.frame matches 33 run tp @s ^-0.25 ^-1.789 ^0.155 ~ ~
execute if score .this aj.frame matches 34 run tp @s ^-0.25 ^-1.788 ^0.154 ~ ~
execute if score .this aj.frame matches 35 run tp @s ^-0.25 ^-1.787 ^0.152 ~ ~
execute if score .this aj.frame matches 36 run tp @s ^-0.25 ^-1.786 ^0.151 ~ ~
execute if score .this aj.frame matches 37 run tp @s ^-0.25 ^-1.785 ^0.15 ~ ~
execute if score .this aj.frame matches 38 run tp @s ^-0.25 ^-1.785 ^0.149 ~ ~
execute if score .this aj.frame matches 39 run tp @s ^-0.25 ^-1.784 ^0.148 ~ ~