#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^-0.25 ^-1.625 ^-0.375 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^-0.25 ^-1.622 ^-0.375 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^-0.25 ^-1.619 ^-0.375 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^-0.25 ^-1.616 ^-0.375 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^-0.25 ^-1.613 ^-0.375 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^-0.25 ^-1.61 ^-0.375 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^-0.25 ^-1.607 ^-0.375 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^-0.25 ^-1.604 ^-0.375 ~ ~