#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 56 run tp @s ^-0.25 ^-1.455 ^0.035 ~ ~
execute if score .this aj.frame matches 57 run tp @s ^-0.25 ^-1.43 ^-0.002 ~ ~
execute if score .this aj.frame matches 58 run tp @s ^-0.25 ^-1.398 ^-0.041 ~ ~
execute if score .this aj.frame matches 59 run tp @s ^-0.25 ^-1.359 ^-0.083 ~ ~
execute if score .this aj.frame matches 60 run tp @s ^-0.25 ^-1.313 ^-0.125 ~ ~
execute if score .this aj.frame matches 61 run tp @s ^-0.25 ^-1.313 ^-0.125 ~ ~
execute if score .this aj.frame matches 62 run tp @s ^-0.25 ^-1.313 ^-0.125 ~ ~
execute if score .this aj.frame matches 63 run tp @s ^-0.25 ^-1.313 ^-0.125 ~ ~