#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run tp @s ^-0.812 ^-0.925 ^-0.562 ~ ~
execute if score .this aj.frame matches 25 run tp @s ^-0.812 ^-0.922 ^-0.531 ~ ~
execute if score .this aj.frame matches 26 run tp @s ^-0.812 ^-0.919 ^-0.5 ~ ~
execute if score .this aj.frame matches 27 run tp @s ^-0.812 ^-0.916 ^-0.469 ~ ~
execute if score .this aj.frame matches 28 run tp @s ^-0.812 ^-0.913 ^-0.437 ~ ~
execute if score .this aj.frame matches 29 run tp @s ^-0.812 ^-0.91 ^-0.406 ~ ~
execute if score .this aj.frame matches 30 run tp @s ^-0.812 ^-0.907 ^-0.375 ~ ~
execute if score .this aj.frame matches 31 run tp @s ^-0.812 ^-0.904 ^-0.375 ~ ~