#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 56 run tp @s ^-0.812 ^-0.149 ^-0.047 ~ ~
execute if score .this aj.frame matches 57 run tp @s ^-0.812 ^-0.087 ^-0.024 ~ ~
execute if score .this aj.frame matches 58 run tp @s ^-0.812 ^-0.021 ^0.001 ~ ~
execute if score .this aj.frame matches 59 run tp @s ^-0.812 ^0.05 ^0.03 ~ ~
execute if score .this aj.frame matches 60 run tp @s ^-0.812 ^0.125 ^0.063 ~ ~
execute if score .this aj.frame matches 61 run tp @s ^-0.812 ^0.125 ^0.063 ~ ~
execute if score .this aj.frame matches 62 run tp @s ^-0.812 ^0.125 ^0.063 ~ ~
execute if score .this aj.frame matches 63 run tp @s ^-0.812 ^0.125 ^0.063 ~ ~