#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^-0.25 ^-1.808 ^0.181 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^-0.25 ^-1.807 ^0.18 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^-0.25 ^-1.806 ^0.179 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^-0.25 ^-1.805 ^0.178 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^-0.25 ^-1.805 ^0.177 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^-0.25 ^-1.804 ^0.176 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^-0.25 ^-1.803 ^0.175 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^-0.25 ^-1.803 ^0.174 ~ ~