#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run data modify entity @s Pose.Head set value [-32f,0f,0f]
execute if score .this aj.frame matches 49 run data modify entity @s Pose.Head set value [-26f,0f,0f]
execute if score .this aj.frame matches 50 run data modify entity @s Pose.Head set value [-20f,0f,0f]
execute if score .this aj.frame matches 51 run data modify entity @s Pose.Head set value [-18f,0f,0f]
execute if score .this aj.frame matches 52 run data modify entity @s Pose.Head set value [-16f,0f,0f]
execute if score .this aj.frame matches 53 run data modify entity @s Pose.Head set value [-14f,0f,0f]
execute if score .this aj.frame matches 54 run data modify entity @s Pose.Head set value [-12f,0f,0f]
execute if score .this aj.frame matches 55 run data modify entity @s Pose.Head set value [-10f,0f,0f]