#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run data modify entity @s Pose.Head set value [-25f,0f,0f]
execute if score .this aj.frame matches 41 run data modify entity @s Pose.Head set value [-17.95f,0f,0f]
execute if score .this aj.frame matches 42 run data modify entity @s Pose.Head set value [-10.9f,0f,0f]
execute if score .this aj.frame matches 43 run data modify entity @s Pose.Head set value [-3.85f,0f,0f]
execute if score .this aj.frame matches 44 run data modify entity @s Pose.Head set value [3.2f,0f,0f]
execute if score .this aj.frame matches 45 run data modify entity @s Pose.Head set value [10.25f,0f,0f]
execute if score .this aj.frame matches 46 run data modify entity @s Pose.Head set value [9.5667f,0f,0f]
execute if score .this aj.frame matches 47 run data modify entity @s Pose.Head set value [8.8833f,0f,0f]