#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^-0.812 ^-1.35 ^-1.025 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^-0.812 ^-1.316 ^-0.997 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^-0.812 ^-1.282 ^-0.969 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^-0.812 ^-1.247 ^-0.941 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^-0.812 ^-1.213 ^-0.912 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^-0.812 ^-1.179 ^-0.884 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^-0.812 ^-1.144 ^-0.856 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^-0.812 ^-1.11 ^-0.828 ~ ~