#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [-90f,0f,0f]
execute if score .this aj.frame matches 1 run data modify entity @s Pose.Head set value [-88f,0f,0f]
execute if score .this aj.frame matches 2 run data modify entity @s Pose.Head set value [-86f,0f,0f]
execute if score .this aj.frame matches 3 run data modify entity @s Pose.Head set value [-84f,0f,0f]
execute if score .this aj.frame matches 4 run data modify entity @s Pose.Head set value [-82f,0f,0f]
execute if score .this aj.frame matches 5 run data modify entity @s Pose.Head set value [-80f,0f,0f]
execute if score .this aj.frame matches 6 run data modify entity @s Pose.Head set value [-78f,0f,0f]
execute if score .this aj.frame matches 7 run data modify entity @s Pose.Head set value [-76f,0f,0f]