#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^-0.25 ^-1.813 ^0.188 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^-0.25 ^-1.812 ^0.187 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^-0.25 ^-1.812 ^0.186 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^-0.25 ^-1.811 ^0.185 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^-0.25 ^-1.81 ^0.184 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^-0.25 ^-1.81 ^0.183 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^-0.25 ^-1.809 ^0.182 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^-0.25 ^-1.808 ^0.182 ~ ~