#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run tp @s ^-0.812 ^-1.075 ^-0.8 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^-0.812 ^-1.041 ^-0.772 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^-0.812 ^-1.007 ^-0.744 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^-0.812 ^-0.972 ^-0.716 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^-0.812 ^-0.938 ^-0.687 ~ ~
execute if score .this aj.frame matches 21 run tp @s ^-0.812 ^-0.935 ^-0.656 ~ ~
execute if score .this aj.frame matches 22 run tp @s ^-0.812 ^-0.932 ^-0.625 ~ ~
execute if score .this aj.frame matches 23 run tp @s ^-0.812 ^-0.929 ^-0.594 ~ ~