#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run data modify entity @s Pose.Head set value [-43f,0f,0f]
execute if score .this aj.frame matches 33 run data modify entity @s Pose.Head set value [-40.75f,0f,0f]
execute if score .this aj.frame matches 34 run data modify entity @s Pose.Head set value [-38.5f,0f,0f]
execute if score .this aj.frame matches 35 run data modify entity @s Pose.Head set value [-36.25f,0f,0f]
execute if score .this aj.frame matches 36 run data modify entity @s Pose.Head set value [-34f,0f,0f]
execute if score .this aj.frame matches 37 run data modify entity @s Pose.Head set value [-31.75f,0f,0f]
execute if score .this aj.frame matches 38 run data modify entity @s Pose.Head set value [-29.5f,0f,0f]
execute if score .this aj.frame matches 39 run data modify entity @s Pose.Head set value [-27.25f,0f,0f]