#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run tp @s ^-0.25 ^-1.562 ^0.16 ~ ~
execute if score .this aj.frame matches 49 run tp @s ^-0.25 ^-1.523 ^0.164 ~ ~
execute if score .this aj.frame matches 50 run tp @s ^-0.25 ^-1.483 ^0.168 ~ ~
execute if score .this aj.frame matches 51 run tp @s ^-0.25 ^-1.491 ^0.159 ~ ~
execute if score .this aj.frame matches 52 run tp @s ^-0.25 ^-1.494 ^0.144 ~ ~
execute if score .this aj.frame matches 53 run tp @s ^-0.25 ^-1.493 ^0.124 ~ ~
execute if score .this aj.frame matches 54 run tp @s ^-0.25 ^-1.486 ^0.098 ~ ~
execute if score .this aj.frame matches 55 run tp @s ^-0.25 ^-1.474 ^0.069 ~ ~