#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run tp @s ^-0.812 ^-0.875 ^-0.375 ~ ~
execute if score .this aj.frame matches 41 run tp @s ^-0.812 ^-0.854 ^-0.354 ~ ~
execute if score .this aj.frame matches 42 run tp @s ^-0.812 ^-0.826 ^-0.335 ~ ~
execute if score .this aj.frame matches 43 run tp @s ^-0.812 ^-0.793 ^-0.318 ~ ~
execute if score .this aj.frame matches 44 run tp @s ^-0.812 ^-0.754 ^-0.301 ~ ~
execute if score .this aj.frame matches 45 run tp @s ^-0.812 ^-0.709 ^-0.283 ~ ~
execute if score .this aj.frame matches 46 run tp @s ^-0.812 ^-0.659 ^-0.265 ~ ~
execute if score .this aj.frame matches 47 run tp @s ^-0.812 ^-0.603 ^-0.245 ~ ~