#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run data modify entity @s Pose.Head set value [-80f,0f,0f]
execute if score .this aj.frame matches 41 run data modify entity @s Pose.Head set value [-78f,0f,0f]
execute if score .this aj.frame matches 42 run data modify entity @s Pose.Head set value [-76f,0f,0f]
execute if score .this aj.frame matches 43 run data modify entity @s Pose.Head set value [-74f,0f,0f]
execute if score .this aj.frame matches 44 run data modify entity @s Pose.Head set value [-72f,0f,0f]
execute if score .this aj.frame matches 45 run data modify entity @s Pose.Head set value [-70f,0f,0f]
execute if score .this aj.frame matches 46 run data modify entity @s Pose.Head set value [-68f,0f,0f]
execute if score .this aj.frame matches 47 run data modify entity @s Pose.Head set value [-66f,0f,0f]