#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [-67f,0f,0f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [-64.125f,0f,0f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [-61.25f,0f,0f]
execute if score .this aj.frame matches 11 run data modify entity @s Pose.Head set value [-58.375f,0f,0f]
execute if score .this aj.frame matches 12 run data modify entity @s Pose.Head set value [-55.5f,0f,0f]
execute if score .this aj.frame matches 13 run data modify entity @s Pose.Head set value [-52.625f,0f,0f]
execute if score .this aj.frame matches 14 run data modify entity @s Pose.Head set value [-49.75f,0f,0f]
execute if score .this aj.frame matches 15 run data modify entity @s Pose.Head set value [-46.875f,0f,0f]