#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run tp @s ^0 ^-1.325 ^-0.512 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^0 ^-1.307 ^-0.494 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^0 ^-1.288 ^-0.475 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^0 ^-1.269 ^-0.456 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^0 ^-1.25 ^-0.437 ~ ~
execute if score .this aj.frame matches 21 run tp @s ^0 ^-1.241 ^-0.425 ~ ~
execute if score .this aj.frame matches 22 run tp @s ^0 ^-1.232 ^-0.412 ~ ~
execute if score .this aj.frame matches 23 run tp @s ^0 ^-1.222 ^-0.4 ~ ~