#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run tp @s ^0 ^-1.125 ^-0.312 ~ ~
execute if score .this aj.frame matches 41 run tp @s ^0 ^-1.109 ^-0.293 ~ ~
execute if score .this aj.frame matches 42 run tp @s ^0 ^-1.089 ^-0.276 ~ ~
execute if score .this aj.frame matches 43 run tp @s ^0 ^-1.064 ^-0.261 ~ ~
execute if score .this aj.frame matches 44 run tp @s ^0 ^-1.034 ^-0.247 ~ ~
execute if score .this aj.frame matches 45 run tp @s ^0 ^-1 ^-0.235 ~ ~
execute if score .this aj.frame matches 46 run tp @s ^0 ^-0.961 ^-0.223 ~ ~
execute if score .this aj.frame matches 47 run tp @s ^0 ^-0.918 ^-0.211 ~ ~