#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run tp @s ^0 ^-0.87 ^-0.198 ~ ~
execute if score .this aj.frame matches 49 run tp @s ^0 ^-0.817 ^-0.183 ~ ~
execute if score .this aj.frame matches 50 run tp @s ^0 ^-0.761 ^-0.167 ~ ~
execute if score .this aj.frame matches 51 run tp @s ^0 ^-0.736 ^-0.151 ~ ~
execute if score .this aj.frame matches 52 run tp @s ^0 ^-0.708 ^-0.138 ~ ~
execute if score .this aj.frame matches 53 run tp @s ^0 ^-0.674 ^-0.127 ~ ~
execute if score .this aj.frame matches 54 run tp @s ^0 ^-0.637 ^-0.118 ~ ~
execute if score .this aj.frame matches 55 run tp @s ^0 ^-0.594 ^-0.109 ~ ~