#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^0 ^-1.475 ^-0.662 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^0 ^-1.457 ^-0.644 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^0 ^-1.438 ^-0.625 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^0 ^-1.419 ^-0.606 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^0 ^-1.4 ^-0.587 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^0 ^-1.382 ^-0.569 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^0 ^-1.363 ^-0.55 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^0 ^-1.344 ^-0.531 ~ ~