#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^0 ^-1.625 ^-0.812 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^0 ^-1.607 ^-0.794 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^0 ^-1.588 ^-0.775 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^0 ^-1.569 ^-0.756 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^0 ^-1.55 ^-0.737 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^0 ^-1.532 ^-0.719 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^0 ^-1.513 ^-0.7 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^0 ^-1.494 ^-0.681 ~ ~