#Project generated by Animated Java (https://animated-java.dev/)

execute if entity @s[tag=aj.christophe.anim.idle] at @s run function christophe:animations/idle/next_frame
scoreboard players operation @s aj.christophe.animating = .aj.animation aj.christophe.animating