#Project generated by Animated Java (https://animated-java.dev/)

data modify entity @s[tag=aj.christophe.bone.head] Pose.Head set value [0f,0f,0f]
data modify entity @s[tag=aj.christophe.bone.body] Pose.Head set value [0f,0f,0f]
data modify entity @s[tag=aj.christophe.bone.left_arm] Pose.Head set value [0f,0f,0f]
data modify entity @s[tag=aj.christophe.bone.right_arm] Pose.Head set value [0f,0f,0f]
data modify entity @s[tag=aj.christophe.bone.left_leg] Pose.Head set value [0f,0f,0f]
data modify entity @s[tag=aj.christophe.bone.right_leg] Pose.Head set value [0f,0f,0f]
tp @s ~ ~ ~ ~ ~