#Project generated by Animated Java (https://animated-java.dev/)

scoreboard players set # aj.i 1
execute at @s as @e[type=#christophe:bone_entities,tag=aj.christophe.bone] if score @s aj.id = .this aj.id run function christophe:zzz/execute/8