#Project generated by Animated Java (https://animated-java.dev/)

execute if score @s aj.sully_boss.roar.loopMode matches 0 run function sully_boss:animations/roar/stop
execute if score @s aj.sully_boss.roar.loopMode matches 1 run function sully_boss:animations/roar/pause
execute if score @s aj.sully_boss.roar.loopMode matches 2 run function sully_boss:animations/roar/zzz/execute/39