#Project generated by Animated Java (https://animated-java.dev/)

tag @s remove aj.sully_boss.anim.walk
tag @s remove aj.sully_boss.anim.idle
tag @s remove aj.sully_boss.anim.death
tag @s remove aj.sully_boss.anim.attack
tag @s remove aj.sully_boss.anim.ground_stomp
tag @s remove aj.sully_boss.anim.roar
tag @s remove aj.sully_boss.anim.sleep
tag @s remove aj.sully_boss.anim.wake
scoreboard players set @s aj.frame 0
scoreboard players operation .this aj.id = @s aj.id
execute as @e[type=minecraft:area_effect_cloud,tag=aj.sully_boss.bone,distance=..6.947] if score @s aj.id = .this aj.id run function sully_boss:zzz/execute/5
execute as @e[type=minecraft:armor_stand,tag=aj.sully_boss.bone,distance=..6.947] if score @s aj.id = .this aj.id run function sully_boss:zzz/execute/6
scoreboard players set #execute aj.i 1