#Project generated by Animated Java (https://animated-java.dev/)

tp @s ~ ~ ~ ~ ~
scoreboard players operation .this aj.id = @s aj.id
scoreboard players operation .this aj.frame = @s aj.frame
scoreboard players set # aj.i 0
execute if entity @s[tag=aj.sully_boss.anim.walk] run function sully_boss:zzz/execute/7
execute if entity @s[tag=aj.sully_boss.anim.idle] run function sully_boss:zzz/execute/10
execute if entity @s[tag=aj.sully_boss.anim.death] run function sully_boss:zzz/execute/13
execute if entity @s[tag=aj.sully_boss.anim.attack] run function sully_boss:zzz/execute/16
execute if entity @s[tag=aj.sully_boss.anim.ground_stomp] run function sully_boss:zzz/execute/19
execute if entity @s[tag=aj.sully_boss.anim.roar] run function sully_boss:zzz/execute/22
execute if entity @s[tag=aj.sully_boss.anim.sleep] run function sully_boss:zzz/execute/25
execute if entity @s[tag=aj.sully_boss.anim.wake] run function sully_boss:zzz/execute/28
execute if score # aj.i matches 0 run function sully_boss:zzz/execute/31
scoreboard players set #execute aj.i 1