#Project generated by Animated Java (https://animated-java.dev/)

execute if score @s aj.sully_boss.idle.loopMode matches 0 run function sully_boss:animations/idle/stop
execute if score @s aj.sully_boss.idle.loopMode matches 1 run function sully_boss:animations/idle/pause
execute if score @s aj.sully_boss.idle.loopMode matches 2 run function sully_boss:animations/idle/zzz/execute/35