#Project generated by Animated Java (https://animated-java.dev/)

scoreboard players set #execute aj.i 0
execute if entity @s[tag=aj.sully_boss.root] run function sully_boss:animations/idle/zzz/conditional/22
execute if score #execute aj.i matches 0 run function sully_boss:animations/idle/zzz/conditional/23