#Project generated by Animated Java (https://animated-java.dev/)

execute if entity @s[tag=aj.christophe.bone.head] run function christophe:animations/idle/tree/head_display_top
execute if entity @s[tag=aj.christophe.bone.body] run function christophe:animations/idle/tree/body_display_top
execute if entity @s[tag=aj.christophe.bone.left_arm] run function christophe:animations/idle/tree/left_arm_display_top
execute if entity @s[tag=aj.christophe.bone.right_arm] run function christophe:animations/idle/tree/right_arm_display_top
execute if entity @s[tag=aj.christophe.bone.left_leg] run function christophe:animations/idle/tree/left_leg_display_top
execute if entity @s[tag=aj.christophe.bone.right_leg] run function christophe:animations/idle/tree/right_leg_display_top
execute positioned as @s run tp @s ~ ~ ~ ~ ~