#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run data modify entity @s Pose.Head set value [-2f,0f,0f]
execute if score .this aj.frame matches 25 run data modify entity @s Pose.Head set value [-1.875f,0f,0f]
execute if score .this aj.frame matches 26 run data modify entity @s Pose.Head set value [-1.75f,0f,0f]
execute if score .this aj.frame matches 27 run data modify entity @s Pose.Head set value [-1.625f,0f,0f]
execute if score .this aj.frame matches 28 run data modify entity @s Pose.Head set value [-1.5f,0f,0f]
execute if score .this aj.frame matches 29 run data modify entity @s Pose.Head set value [-1.375f,0f,0f]
execute if score .this aj.frame matches 30 run data modify entity @s Pose.Head set value [-1.25f,0f,0f]
execute if score .this aj.frame matches 31 run data modify entity @s Pose.Head set value [-1.125f,0f,0f]