#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 1 run data modify entity @s Pose.Head set value [-0.125f,0f,0f]
execute if score .this aj.frame matches 2 run data modify entity @s Pose.Head set value [-0.25f,0f,0f]
execute if score .this aj.frame matches 3 run data modify entity @s Pose.Head set value [-0.375f,0f,0f]
execute if score .this aj.frame matches 4 run data modify entity @s Pose.Head set value [-0.5f,0f,0f]
execute if score .this aj.frame matches 5 run data modify entity @s Pose.Head set value [-0.625f,0f,0f]
execute if score .this aj.frame matches 6 run data modify entity @s Pose.Head set value [-0.75f,0f,0f]
execute if score .this aj.frame matches 7 run data modify entity @s Pose.Head set value [-0.875f,0f,0f]