#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [2f,0f,-2f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [2.125f,0f,-2.125f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [2.25f,0f,-2.25f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [2.375f,0f,-2.375f]
execute if score .this aj.frame matches 20 run data modify entity @s Pose.Head set value [2.5f,0f,-2.5f]
execute if score .this aj.frame matches 21 run data modify entity @s Pose.Head set value [2.375f,0f,-2.375f]
execute if score .this aj.frame matches 22 run data modify entity @s Pose.Head set value [2.25f,0f,-2.25f]
execute if score .this aj.frame matches 23 run data modify entity @s Pose.Head set value [2.125f,0f,-2.125f]