#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run data modify entity @s Pose.Head set value [1f,0f,-1f]
execute if score .this aj.frame matches 33 run data modify entity @s Pose.Head set value [0.875f,0f,-0.875f]
execute if score .this aj.frame matches 34 run data modify entity @s Pose.Head set value [0.75f,0f,-0.75f]
execute if score .this aj.frame matches 35 run data modify entity @s Pose.Head set value [0.625f,0f,-0.625f]
execute if score .this aj.frame matches 36 run data modify entity @s Pose.Head set value [0.5f,0f,-0.5f]
execute if score .this aj.frame matches 37 run data modify entity @s Pose.Head set value [0.375f,0f,-0.375f]
execute if score .this aj.frame matches 38 run data modify entity @s Pose.Head set value [0.25f,0f,-0.25f]
execute if score .this aj.frame matches 39 run data modify entity @s Pose.Head set value [0.125f,0f,-0.125f]