#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [1f,0f,-1f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [1.125f,0f,-1.125f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [1.25f,0f,-1.25f]
execute if score .this aj.frame matches 11 run data modify entity @s Pose.Head set value [1.375f,0f,-1.375f]
execute if score .this aj.frame matches 12 run data modify entity @s Pose.Head set value [1.5f,0f,-1.5f]
execute if score .this aj.frame matches 13 run data modify entity @s Pose.Head set value [1.625f,0f,-1.625f]
execute if score .this aj.frame matches 14 run data modify entity @s Pose.Head set value [1.75f,0f,-1.75f]
execute if score .this aj.frame matches 15 run data modify entity @s Pose.Head set value [1.875f,0f,-1.875f]