#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^-0.312 ^-0.44 ^0 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^-0.312 ^-0.441 ^0 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^-0.312 ^-0.441 ^0 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^-0.312 ^-0.441 ^0 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^-0.312 ^-0.442 ^0 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^-0.312 ^-0.442 ^0 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^-0.312 ^-0.442 ^0 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^-0.312 ^-0.443 ^0 ~ ~