#Project generated by Animated Java (https://animated-java.dev/)

execute if entity @s[tag=aj.christophe.bone.head] run function christophe:animations/idle/tree/head_root_top
execute if entity @s[tag=aj.christophe.bone.body] run function christophe:animations/idle/tree/body_root_top
execute if entity @s[tag=aj.christophe.bone.left_arm] run function christophe:animations/idle/tree/left_arm_root_top
execute if entity @s[tag=aj.christophe.bone.right_arm] run function christophe:animations/idle/tree/right_arm_root_top
execute if entity @s[tag=aj.christophe.bone.left_leg] run function christophe:animations/idle/tree/left_leg_root_top
execute if entity @s[tag=aj.christophe.bone.right_leg] run function christophe:animations/idle/tree/right_leg_root_top
execute store result entity @s Air short 1 run scoreboard players get .this aj.frame