#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^0 ^0.312 ^0.188 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^0 ^0.304 ^0.196 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^0 ^0.295 ^0.204 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^0 ^0.287 ^0.213 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^0 ^0.279 ^0.221 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^0 ^0.27 ^0.229 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^0 ^0.262 ^0.238 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^0 ^0.254 ^0.246 ~ ~