#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run tp @s ^0 ^0.262 ^0.238 ~ ~
execute if score .this aj.frame matches 25 run tp @s ^0 ^0.27 ^0.229 ~ ~
execute if score .this aj.frame matches 26 run tp @s ^0 ^0.279 ^0.221 ~ ~
execute if score .this aj.frame matches 27 run tp @s ^0 ^0.287 ^0.213 ~ ~
execute if score .this aj.frame matches 28 run tp @s ^0 ^0.295 ^0.204 ~ ~
execute if score .this aj.frame matches 29 run tp @s ^0 ^0.304 ^0.196 ~ ~