#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run tp @s ^0 ^0.195 ^0.304 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^0 ^0.204 ^0.296 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^0 ^0.212 ^0.288 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^0 ^0.22 ^0.279 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^0 ^0.229 ^0.271 ~ ~
execute if score .this aj.frame matches 21 run tp @s ^0 ^0.237 ^0.263 ~ ~
execute if score .this aj.frame matches 22 run tp @s ^0 ^0.245 ^0.254 ~ ~
execute if score .this aj.frame matches 23 run tp @s ^0 ^0.254 ^0.246 ~ ~