#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run data modify entity @s Pose.Head set value [5f,0f,0f]
execute if score .this aj.frame matches 25 run data modify entity @s Pose.Head set value [7.5f,0f,0f]
execute if score .this aj.frame matches 26 run data modify entity @s Pose.Head set value [6f,0f,0f]
execute if score .this aj.frame matches 27 run data modify entity @s Pose.Head set value [4.5f,0f,0f]
execute if score .this aj.frame matches 28 run data modify entity @s Pose.Head set value [3f,0f,0f]
execute if score .this aj.frame matches 29 run data modify entity @s Pose.Head set value [1.5f,0f,0f]