#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^0 ^0.245 ^0.254 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^0 ^0.237 ^0.263 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^0 ^0.229 ^0.271 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^0 ^0.22 ^0.279 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^0 ^0.212 ^0.288 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^0 ^0.204 ^0.296 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^0 ^0.195 ^0.304 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^0 ^0.187 ^0.313 ~ ~