#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run tp @s ^-0.125 ^0.265 ^0.175 ~ ~
execute if score .this aj.frame matches 25 run tp @s ^-0.125 ^0.276 ^0.167 ~ ~
execute if score .this aj.frame matches 26 run tp @s ^-0.125 ^0.282 ^0.158 ~ ~
execute if score .this aj.frame matches 27 run tp @s ^-0.125 ^0.289 ^0.15 ~ ~
execute if score .this aj.frame matches 28 run tp @s ^-0.125 ^0.296 ^0.142 ~ ~
execute if score .this aj.frame matches 29 run tp @s ^-0.125 ^0.303 ^0.133 ~ ~