#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run tp @s ^-0.125 ^0.196 ^0.242 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^-0.125 ^0.202 ^0.233 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^-0.125 ^0.208 ^0.225 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^-0.125 ^0.214 ^0.217 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^-0.125 ^0.221 ^0.209 ~ ~
execute if score .this aj.frame matches 21 run tp @s ^-0.125 ^0.232 ^0.2 ~ ~
execute if score .this aj.frame matches 22 run tp @s ^-0.125 ^0.243 ^0.192 ~ ~
execute if score .this aj.frame matches 23 run tp @s ^-0.125 ^0.254 ^0.183 ~ ~