#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^-0.125 ^0.244 ^0.192 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^-0.125 ^0.234 ^0.2 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^-0.125 ^0.223 ^0.208 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^-0.125 ^0.217 ^0.217 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^-0.125 ^0.21 ^0.225 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^-0.125 ^0.203 ^0.233 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^-0.125 ^0.196 ^0.242 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^-0.125 ^0.19 ^0.25 ~ ~