#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^-0.125 ^0.309 ^0.125 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^-0.125 ^0.303 ^0.133 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^-0.125 ^0.296 ^0.142 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^-0.125 ^0.289 ^0.15 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^-0.125 ^0.282 ^0.158 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^-0.125 ^0.276 ^0.167 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^-0.125 ^0.265 ^0.175 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^-0.125 ^0.255 ^0.183 ~ ~