#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [30f,0f,0f]
execute if score .this aj.frame matches 11 run data modify entity @s Pose.Head set value [31.5f,0f,0f]
execute if score .this aj.frame matches 12 run data modify entity @s Pose.Head set value [33f,0f,0f]
execute if score .this aj.frame matches 13 run data modify entity @s Pose.Head set value [34.5f,0f,0f]
execute if score .this aj.frame matches 14 run data modify entity @s Pose.Head set value [36f,0f,0f]
execute if score .this aj.frame matches 15 run data modify entity @s Pose.Head set value [37.5f,0f,0f]