#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function sully_boss:animations/walk/tree/jaw_root_0-7
execute if score .this aj.frame matches 8..15 run function sully_boss:animations/walk/tree/jaw_root_8-15
execute if score .this aj.frame matches 16..23 run function sully_boss:animations/walk/tree/jaw_root_16-23
execute if score .this aj.frame matches 24..29 run function sully_boss:animations/walk/tree/jaw_root_24-29