#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [-44.5f,0f,0f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [-38.5f,0f,0f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [-32.5f,0f,0f]
execute if score .this aj.frame matches 11 run data modify entity @s Pose.Head set value [-26.5f,0f,0f]
execute if score .this aj.frame matches 12 run data modify entity @s Pose.Head set value [-20.5f,0f,0f]
execute if score .this aj.frame matches 13 run data modify entity @s Pose.Head set value [-14.5f,0f,0f]
execute if score .this aj.frame matches 14 run data modify entity @s Pose.Head set value [-8.5f,0f,0f]
execute if score .this aj.frame matches 15 run data modify entity @s Pose.Head set value [-2.5f,0f,0f]