#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run tp @s ^0.313 ^-1.235 ^-0.095 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^0.313 ^-1.228 ^-0.137 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^0.313 ^-1.217 ^-0.178 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^0.313 ^-1.202 ^-0.218 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^0.313 ^-1.184 ^-0.257 ~ ~
execute if score .this aj.frame matches 21 run tp @s ^0.313 ^-1.163 ^-0.295 ~ ~
execute if score .this aj.frame matches 22 run tp @s ^0.313 ^-1.139 ^-0.331 ~ ~
execute if score .this aj.frame matches 23 run tp @s ^0.313 ^-1.143 ^-0.34 ~ ~