#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [-40.0833f,0f,0f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [-35.25f,0f,0f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [-30.4167f,0f,0f]
execute if score .this aj.frame matches 11 run data modify entity @s Pose.Head set value [-25.5833f,0f,0f]
execute if score .this aj.frame matches 12 run data modify entity @s Pose.Head set value [-20.75f,0f,0f]
execute if score .this aj.frame matches 13 run data modify entity @s Pose.Head set value [-15.9167f,0f,0f]
execute if score .this aj.frame matches 14 run data modify entity @s Pose.Head set value [-11.0833f,0f,0f]
execute if score .this aj.frame matches 15 run data modify entity @s Pose.Head set value [-6.25f,0f,0f]