#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [-1.4167f,0f,0f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [3.4167f,0f,0f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [8.25f,0f,0f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [13.0833f,0f,0f]
execute if score .this aj.frame matches 20 run data modify entity @s Pose.Head set value [17.9167f,0f,0f]
execute if score .this aj.frame matches 21 run data modify entity @s Pose.Head set value [22.75f,0f,0f]
execute if score .this aj.frame matches 22 run data modify entity @s Pose.Head set value [27.5833f,0f,0f]
execute if score .this aj.frame matches 23 run data modify entity @s Pose.Head set value [28f,0f,0f]