#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^0.313 ^-1.313 ^-0.125 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^0.313 ^-1.308 ^-0.07 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^0.313 ^-1.298 ^-0.015 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^0.313 ^-1.283 ^0.037 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^0.313 ^-1.263 ^0.088 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^0.313 ^-1.238 ^0.136 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^0.313 ^-1.208 ^0.181 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^0.313 ^-1.174 ^0.222 ~ ~