#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run tp @s ^0.313 ^-1.177 ^-0.322 ~ ~
execute if score .this aj.frame matches 25 run tp @s ^0.313 ^-1.212 ^-0.299 ~ ~
execute if score .this aj.frame matches 26 run tp @s ^0.313 ^-1.247 ^-0.272 ~ ~
execute if score .this aj.frame matches 27 run tp @s ^0.313 ^-1.275 ^-0.239 ~ ~
execute if score .this aj.frame matches 28 run tp @s ^0.313 ^-1.29 ^-0.202 ~ ~
execute if score .this aj.frame matches 29 run tp @s ^0.313 ^-1.303 ^-0.164 ~ ~