#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^0.313 ^-1.167 ^0.224 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^0.313 ^-1.187 ^0.189 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^0.313 ^-1.204 ^0.151 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^0.313 ^-1.218 ^0.112 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^0.313 ^-1.228 ^0.072 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^0.313 ^-1.235 ^0.031 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^0.313 ^-1.239 ^-0.011 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^0.313 ^-1.239 ^-0.053 ~ ~