#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [24f,0f,0f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [28f,0f,0f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [32f,0f,0f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [36f,0f,0f]
execute if score .this aj.frame matches 20 run data modify entity @s Pose.Head set value [40f,0f,0f]
execute if score .this aj.frame matches 21 run data modify entity @s Pose.Head set value [44f,0f,0f]
execute if score .this aj.frame matches 22 run data modify entity @s Pose.Head set value [48f,0f,0f]
execute if score .this aj.frame matches 23 run data modify entity @s Pose.Head set value [45.6f,0f,0f]