#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 1 run data modify entity @s Pose.Head set value [-5.6667f,0f,0f]
execute if score .this aj.frame matches 2 run data modify entity @s Pose.Head set value [-11.3333f,0f,0f]
execute if score .this aj.frame matches 3 run data modify entity @s Pose.Head set value [-17f,0f,0f]
execute if score .this aj.frame matches 4 run data modify entity @s Pose.Head set value [-22.6667f,0f,0f]
execute if score .this aj.frame matches 5 run data modify entity @s Pose.Head set value [-28.3333f,0f,0f]
execute if score .this aj.frame matches 6 run data modify entity @s Pose.Head set value [-34f,0f,0f]
execute if score .this aj.frame matches 7 run data modify entity @s Pose.Head set value [-39.6667f,0f,0f]