#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run data modify entity @s Pose.Head set value [34f,0f,0f]
execute if score .this aj.frame matches 25 run data modify entity @s Pose.Head set value [28.3333f,0f,0f]
execute if score .this aj.frame matches 26 run data modify entity @s Pose.Head set value [22.6667f,0f,0f]
execute if score .this aj.frame matches 27 run data modify entity @s Pose.Head set value [17f,0f,0f]
execute if score .this aj.frame matches 28 run data modify entity @s Pose.Head set value [11.3333f,0f,0f]
execute if score .this aj.frame matches 29 run data modify entity @s Pose.Head set value [5.6667f,0f,0f]