#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run data modify entity @s Pose.Head set value [36.8f,0f,0f]
execute if score .this aj.frame matches 25 run data modify entity @s Pose.Head set value [28f,0f,0f]
execute if score .this aj.frame matches 26 run data modify entity @s Pose.Head set value [19.2f,0f,0f]
execute if score .this aj.frame matches 27 run data modify entity @s Pose.Head set value [12f,0f,0f]
execute if score .this aj.frame matches 28 run data modify entity @s Pose.Head set value [8f,0f,0f]
execute if score .this aj.frame matches 29 run data modify entity @s Pose.Head set value [4f,0f,0f]