#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run tp @s ^-0.25 ^-1.225 ^0.184 ~ ~
execute if score .this aj.frame matches 25 run tp @s ^-0.25 ^-1.266 ^0.141 ~ ~
execute if score .this aj.frame matches 26 run tp @s ^-0.25 ^-1.302 ^0.096 ~ ~
execute if score .this aj.frame matches 27 run tp @s ^-0.25 ^-1.325 ^0.045 ~ ~
execute if score .this aj.frame matches 28 run tp @s ^-0.25 ^-1.327 ^-0.012 ~ ~
execute if score .this aj.frame matches 29 run tp @s ^-0.25 ^-1.323 ^-0.069 ~ ~