#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^-0.25 ^-1.124 ^-0.312 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^-0.25 ^-1.148 ^-0.279 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^-0.25 ^-1.17 ^-0.243 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^-0.25 ^-1.188 ^-0.206 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^-0.25 ^-1.203 ^-0.168 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^-0.25 ^-1.214 ^-0.129 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^-0.25 ^-1.223 ^-0.089 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^-0.25 ^-1.227 ^-0.048 ~ ~