#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^-0.25 ^-1.313 ^-0.125 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^-0.25 ^-1.293 ^-0.195 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^-0.25 ^-1.264 ^-0.261 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^-0.25 ^-1.227 ^-0.323 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^-0.25 ^-1.183 ^-0.381 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^-0.25 ^-1.156 ^-0.377 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^-0.25 ^-1.136 ^-0.359 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^-0.25 ^-1.118 ^-0.339 ~ ~