#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run tp @s ^-0.25 ^-1.229 ^-0.008 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^-0.25 ^-1.227 ^0.033 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^-0.25 ^-1.221 ^0.073 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^-0.25 ^-1.212 ^0.113 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^-0.25 ^-1.2 ^0.151 ~ ~
execute if score .this aj.frame matches 21 run tp @s ^-0.25 ^-1.184 ^0.188 ~ ~
execute if score .this aj.frame matches 22 run tp @s ^-0.25 ^-1.166 ^0.224 ~ ~
execute if score .this aj.frame matches 23 run tp @s ^-0.25 ^-1.18 ^0.223 ~ ~