#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [2.5f,0f,0f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [-2.5f,0f,0f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [-7.5f,0f,0f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [-12.5f,0f,0f]
execute if score .this aj.frame matches 20 run data modify entity @s Pose.Head set value [-17.5f,0f,0f]
execute if score .this aj.frame matches 21 run data modify entity @s Pose.Head set value [-22.5f,0f,0f]
execute if score .this aj.frame matches 22 run data modify entity @s Pose.Head set value [-27.5f,0f,0f]
execute if score .this aj.frame matches 23 run data modify entity @s Pose.Head set value [-28f,0f,0f]