#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run data modify entity @s Pose.Head set value [-24f,0f,0f]
execute if score .this aj.frame matches 25 run data modify entity @s Pose.Head set value [-20f,0f,0f]
execute if score .this aj.frame matches 26 run data modify entity @s Pose.Head set value [-16f,0f,0f]
execute if score .this aj.frame matches 27 run data modify entity @s Pose.Head set value [-12f,0f,0f]
execute if score .this aj.frame matches 28 run data modify entity @s Pose.Head set value [-8f,0f,0f]
execute if score .this aj.frame matches 29 run data modify entity @s Pose.Head set value [-4f,0f,0f]