#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 1 run data modify entity @s Pose.Head set value [7.2f,0f,0f]
execute if score .this aj.frame matches 2 run data modify entity @s Pose.Head set value [14.4f,0f,0f]
execute if score .this aj.frame matches 3 run data modify entity @s Pose.Head set value [21.6f,0f,0f]
execute if score .this aj.frame matches 4 run data modify entity @s Pose.Head set value [28.8f,0f,0f]
execute if score .this aj.frame matches 5 run data modify entity @s Pose.Head set value [30f,0f,0f]
execute if score .this aj.frame matches 7 run data modify entity @s Pose.Head set value [30f,0f,0f]