#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run data modify entity @s Pose.Head set value [72.5f,0f,0f]
execute if score .this aj.frame matches 25 run data modify entity @s Pose.Head set value [66.25f,0f,0f]
execute if score .this aj.frame matches 26 run data modify entity @s Pose.Head set value [60f,0f,0f]