#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 64 run tp @s ^0 ^0.012 ^0.188 ~ ~
execute if score .this aj.frame matches 65 run tp @s ^0 ^0.062 ^0.188 ~ ~
execute if score .this aj.frame matches 66 run tp @s ^0 ^0.112 ^0.188 ~ ~
execute if score .this aj.frame matches 67 run tp @s ^0 ^0.162 ^0.188 ~ ~
execute if score .this aj.frame matches 68 run tp @s ^0 ^0.212 ^0.188 ~ ~
execute if score .this aj.frame matches 69 run tp @s ^0 ^0.262 ^0.188 ~ ~
execute if score .this aj.frame matches 70 run tp @s ^0 ^0.312 ^0.188 ~ ~
execute if score .this aj.frame matches 71 run tp @s ^0 ^0.312 ^0.188 ~ ~