#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run tp @s ^0 ^0.074 ^0.375 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^0 ^-0.063 ^0.46 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^0 ^-0.21 ^0.537 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^0 ^-0.367 ^0.605 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^0 ^-0.532 ^0.663 ~ ~
execute if score .this aj.frame matches 21 run tp @s ^0 ^-0.704 ^0.709 ~ ~
execute if score .this aj.frame matches 22 run tp @s ^0 ^-0.882 ^0.743 ~ ~
execute if score .this aj.frame matches 23 run tp @s ^0 ^-0.882 ^0.743 ~ ~