#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run tp @s ^0 ^-0.882 ^0.743 ~ ~
execute if score .this aj.frame matches 49 run tp @s ^0 ^-0.882 ^0.743 ~ ~
execute if score .this aj.frame matches 50 run tp @s ^0 ^-0.882 ^0.743 ~ ~
execute if score .this aj.frame matches 51 run tp @s ^0 ^-0.789 ^0.717 ~ ~
execute if score .this aj.frame matches 52 run tp @s ^0 ^-0.7 ^0.683 ~ ~
execute if score .this aj.frame matches 53 run tp @s ^0 ^-0.615 ^0.641 ~ ~
execute if score .this aj.frame matches 54 run tp @s ^0 ^-0.535 ^0.593 ~ ~
execute if score .this aj.frame matches 55 run tp @s ^0 ^-0.46 ^0.537 ~ ~