#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 14 run data modify entity @s Pose.Head set value [12.5f,0f,0f]
execute if score .this aj.frame matches 15 run data modify entity @s Pose.Head set value [20f,0f,0f]