#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..63 run function sully_boss:animations/ground_stomp/tree/jaw_display_0-63
execute if score .this aj.frame matches 71 run data modify entity @s Pose.Head set value [12.5f,0f,0f]