#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 56 run tp @s ^-0.125 ^-0.369 ^0.418 ~ ~
execute if score .this aj.frame matches 57 run tp @s ^-0.125 ^-0.313 ^0.35 ~ ~
execute if score .this aj.frame matches 58 run tp @s ^-0.125 ^-0.264 ^0.278 ~ ~
execute if score .this aj.frame matches 59 run tp @s ^-0.125 ^-0.224 ^0.202 ~ ~
execute if score .this aj.frame matches 60 run tp @s ^-0.125 ^-0.191 ^0.125 ~ ~
execute if score .this aj.frame matches 61 run tp @s ^-0.125 ^-0.141 ^0.125 ~ ~
execute if score .this aj.frame matches 62 run tp @s ^-0.125 ^-0.091 ^0.125 ~ ~
execute if score .this aj.frame matches 63 run tp @s ^-0.125 ^-0.041 ^0.125 ~ ~