#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 64 run tp @s ^-0.125 ^0.009 ^0.125 ~ ~
execute if score .this aj.frame matches 65 run tp @s ^-0.125 ^0.059 ^0.125 ~ ~
execute if score .this aj.frame matches 66 run tp @s ^-0.125 ^0.109 ^0.125 ~ ~
execute if score .this aj.frame matches 67 run tp @s ^-0.125 ^0.159 ^0.125 ~ ~
execute if score .this aj.frame matches 68 run tp @s ^-0.125 ^0.209 ^0.125 ~ ~
execute if score .this aj.frame matches 69 run tp @s ^-0.125 ^0.259 ^0.125 ~ ~
execute if score .this aj.frame matches 70 run tp @s ^-0.125 ^0.309 ^0.125 ~ ~
execute if score .this aj.frame matches 71 run tp @s ^-0.125 ^0.309 ^0.125 ~ ~