#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [12.5f,0f,0f]
execute if score .this aj.frame matches 8..15 run function sully_boss:animations/ground_stomp/tree/jaw_display_8-15
execute if score .this aj.frame matches 16..23 run function sully_boss:animations/ground_stomp/tree/jaw_display_16-23
execute if score .this aj.frame matches 24..31 run function sully_boss:animations/ground_stomp/tree/jaw_display_24-31
execute if score .this aj.frame matches 48..55 run function sully_boss:animations/ground_stomp/tree/jaw_display_48-55
execute if score .this aj.frame matches 56..63 run function sully_boss:animations/ground_stomp/tree/jaw_display_56-63