#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run tp @s ^-0.125 ^-0.823 ^0.722 ~ ~
execute if score .this aj.frame matches 25 run tp @s ^-0.125 ^-0.825 ^0.716 ~ ~
execute if score .this aj.frame matches 26 run tp @s ^-0.125 ^-0.829 ^0.71 ~ ~
execute if score .this aj.frame matches 27 run tp @s ^-0.125 ^-0.829 ^0.71 ~ ~
execute if score .this aj.frame matches 28 run tp @s ^-0.125 ^-0.829 ^0.71 ~ ~
execute if score .this aj.frame matches 29 run tp @s ^-0.125 ^-0.829 ^0.71 ~ ~
execute if score .this aj.frame matches 30 run tp @s ^-0.125 ^-0.829 ^0.71 ~ ~
execute if score .this aj.frame matches 31 run tp @s ^-0.125 ^-0.829 ^0.71 ~ ~