#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [27.5f,0f,0f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [35f,0f,0f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [42.5f,0f,0f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [50f,0f,0f]
execute if score .this aj.frame matches 20 run data modify entity @s Pose.Head set value [57.5f,0f,0f]
execute if score .this aj.frame matches 21 run data modify entity @s Pose.Head set value [65f,0f,0f]
execute if score .this aj.frame matches 22 run data modify entity @s Pose.Head set value [76.6667f,0f,0f]
execute if score .this aj.frame matches 23 run data modify entity @s Pose.Head set value [80.8333f,0f,0f]