#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run tp @s ^-0.125 ^-0.829 ^0.71 ~ ~
execute if score .this aj.frame matches 49 run tp @s ^-0.125 ^-0.829 ^0.71 ~ ~
execute if score .this aj.frame matches 50 run tp @s ^-0.125 ^-0.829 ^0.71 ~ ~
execute if score .this aj.frame matches 51 run tp @s ^-0.125 ^-0.74 ^0.678 ~ ~
execute if score .this aj.frame matches 52 run tp @s ^-0.125 ^-0.656 ^0.639 ~ ~
execute if score .this aj.frame matches 53 run tp @s ^-0.125 ^-0.576 ^0.593 ~ ~
execute if score .this aj.frame matches 54 run tp @s ^-0.125 ^-0.501 ^0.54 ~ ~
execute if score .this aj.frame matches 55 run tp @s ^-0.125 ^-0.431 ^0.482 ~ ~