#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run tp @s ^-0.125 ^0.087 ^0.314 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^-0.125 ^-0.042 ^0.401 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^-0.125 ^-0.181 ^0.482 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^-0.125 ^-0.331 ^0.554 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^-0.125 ^-0.49 ^0.617 ~ ~
execute if score .this aj.frame matches 21 run tp @s ^-0.125 ^-0.656 ^0.669 ~ ~
execute if score .this aj.frame matches 22 run tp @s ^-0.125 ^-0.827 ^0.714 ~ ~
execute if score .this aj.frame matches 23 run tp @s ^-0.125 ^-0.824 ^0.718 ~ ~