#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 64 run tp @s ^0.313 ^-1.462 ^-0.049 ~ ~
execute if score .this aj.frame matches 65 run tp @s ^0.313 ^-1.431 ^-0.071 ~ ~
execute if score .this aj.frame matches 66 run tp @s ^0.313 ^-1.404 ^-0.09 ~ ~
execute if score .this aj.frame matches 67 run tp @s ^0.313 ^-1.378 ^-0.105 ~ ~
execute if score .this aj.frame matches 68 run tp @s ^0.313 ^-1.355 ^-0.116 ~ ~
execute if score .this aj.frame matches 69 run tp @s ^0.313 ^-1.334 ^-0.123 ~ ~
execute if score .this aj.frame matches 70 run tp @s ^0.313 ^-1.313 ^-0.125 ~ ~
execute if score .this aj.frame matches 71 run tp @s ^0.313 ^-1.313 ^-0.125 ~ ~