#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run data modify entity @s Pose.Head set value [89.6637f,0f,0f]
execute if score .this aj.frame matches 41 run data modify entity @s Pose.Head set value [89.645f,0f,0f]
execute if score .this aj.frame matches 42 run data modify entity @s Pose.Head set value [89.6263f,0f,0f]
execute if score .this aj.frame matches 43 run data modify entity @s Pose.Head set value [89.6076f,0f,0f]
execute if score .this aj.frame matches 44 run data modify entity @s Pose.Head set value [89.5889f,0f,0f]
execute if score .this aj.frame matches 45 run data modify entity @s Pose.Head set value [89.5703f,0f,0f]
execute if score .this aj.frame matches 46 run data modify entity @s Pose.Head set value [89.5516f,0f,0f]
execute if score .this aj.frame matches 47 run data modify entity @s Pose.Head set value [89.5329f,0f,0f]