#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 8..15 run function sully_boss:animations/ground_stomp/tree/left_leg_down_display_8-15
execute if score .this aj.frame matches 16..23 run function sully_boss:animations/ground_stomp/tree/left_leg_down_display_16-23
execute if score .this aj.frame matches 24..31 run function sully_boss:animations/ground_stomp/tree/left_leg_down_display_24-31
execute if score .this aj.frame matches 32..39 run function sully_boss:animations/ground_stomp/tree/left_leg_down_display_32-39
execute if score .this aj.frame matches 40..47 run function sully_boss:animations/ground_stomp/tree/left_leg_down_display_40-47
execute if score .this aj.frame matches 48..55 run function sully_boss:animations/ground_stomp/tree/left_leg_down_display_48-55
execute if score .this aj.frame matches 56..63 run function sully_boss:animations/ground_stomp/tree/left_leg_down_display_56-63