#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [-165f,0f,0f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [-157.5f,0f,0f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [-150f,0f,0f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [-123.75f,0f,0f]
execute if score .this aj.frame matches 20 run data modify entity @s Pose.Head set value [-97.5f,0f,0f]
execute if score .this aj.frame matches 21 run data modify entity @s Pose.Head set value [-71.25f,0f,0f]
execute if score .this aj.frame matches 22 run data modify entity @s Pose.Head set value [-45f,0f,0f]
execute if score .this aj.frame matches 23 run data modify entity @s Pose.Head set value [-37.5f,0f,0f]