#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run tp @s ^0.688 ^-0.867 ^0.518 ~ ~
execute if score .this aj.frame matches 49 run tp @s ^0.688 ^-0.867 ^0.518 ~ ~
execute if score .this aj.frame matches 50 run tp @s ^0.688 ^-0.867 ^0.518 ~ ~
execute if score .this aj.frame matches 51 run tp @s ^0.688 ^-0.799 ^0.492 ~ ~
execute if score .this aj.frame matches 52 run tp @s ^0.688 ^-0.733 ^0.46 ~ ~
execute if score .this aj.frame matches 53 run tp @s ^0.688 ^-0.671 ^0.423 ~ ~
execute if score .this aj.frame matches 54 run tp @s ^0.688 ^-0.613 ^0.381 ~ ~
execute if score .this aj.frame matches 55 run tp @s ^0.688 ^-0.56 ^0.335 ~ ~