#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run tp @s ^0.688 ^-0.075 ^0.206 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^0.688 ^-0.188 ^0.273 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^0.688 ^-0.31 ^0.335 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^0.688 ^-0.44 ^0.392 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^0.688 ^-0.577 ^0.442 ~ ~
execute if score .this aj.frame matches 21 run tp @s ^0.688 ^-0.719 ^0.484 ~ ~
execute if score .this aj.frame matches 22 run tp @s ^0.688 ^-0.867 ^0.518 ~ ~
execute if score .this aj.frame matches 23 run tp @s ^0.688 ^-0.867 ^0.518 ~ ~