#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run tp @s ^0.306 ^-0.904 ^-0.081 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^0.306 ^-0.973 ^-0.12 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^0.306 ^-1.037 ^-0.156 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^0.306 ^-1.096 ^-0.19 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^0.306 ^-1.151 ^-0.221 ~ ~
execute if score .this aj.frame matches 21 run tp @s ^0.306 ^-1.202 ^-0.248 ~ ~
execute if score .this aj.frame matches 22 run tp @s ^0.306 ^-1.25 ^-0.271 ~ ~
execute if score .this aj.frame matches 23 run tp @s ^0.306 ^-1.25 ^-0.271 ~ ~