#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 64 run tp @s ^0.306 ^-1.05 ^0 ~ ~
execute if score .this aj.frame matches 65 run tp @s ^0.306 ^-1 ^0 ~ ~
execute if score .this aj.frame matches 66 run tp @s ^0.306 ^-0.95 ^0 ~ ~
execute if score .this aj.frame matches 67 run tp @s ^0.306 ^-0.9 ^0 ~ ~
execute if score .this aj.frame matches 68 run tp @s ^0.306 ^-0.85 ^0 ~ ~
execute if score .this aj.frame matches 69 run tp @s ^0.306 ^-0.8 ^0 ~ ~
execute if score .this aj.frame matches 70 run tp @s ^0.306 ^-0.75 ^0 ~ ~
execute if score .this aj.frame matches 71 run tp @s ^0.306 ^-0.75 ^0 ~ ~