#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run data modify entity @s Pose.Head set value [89.8132f,0f,0f]
execute if score .this aj.frame matches 33 run data modify entity @s Pose.Head set value [89.7945f,0f,0f]
execute if score .this aj.frame matches 34 run data modify entity @s Pose.Head set value [89.7758f,0f,0f]
execute if score .this aj.frame matches 35 run data modify entity @s Pose.Head set value [89.7571f,0f,0f]
execute if score .this aj.frame matches 36 run data modify entity @s Pose.Head set value [89.7384f,0f,0f]
execute if score .this aj.frame matches 37 run data modify entity @s Pose.Head set value [89.7197f,0f,0f]
execute if score .this aj.frame matches 38 run data modify entity @s Pose.Head set value [89.7011f,0f,0f]
execute if score .this aj.frame matches 39 run data modify entity @s Pose.Head set value [89.6824f,0f,0f]