#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run tp @s ^0.313 ^-1.626 ^-0.21 ~ ~
execute if score .this aj.frame matches 49 run tp @s ^0.313 ^-1.626 ^-0.21 ~ ~
execute if score .this aj.frame matches 50 run tp @s ^0.313 ^-1.626 ^-0.21 ~ ~
execute if score .this aj.frame matches 51 run tp @s ^0.313 ^-1.637 ^-0.192 ~ ~
execute if score .this aj.frame matches 52 run tp @s ^0.313 ^-1.647 ^-0.172 ~ ~
execute if score .this aj.frame matches 53 run tp @s ^0.313 ^-1.655 ^-0.148 ~ ~
execute if score .this aj.frame matches 54 run tp @s ^0.313 ^-1.66 ^-0.123 ~ ~
execute if score .this aj.frame matches 55 run tp @s ^0.313 ^-1.662 ^-0.096 ~ ~