#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run data modify entity @s Pose.Head set value [89.9626f,0f,0f]
execute if score .this aj.frame matches 25 run data modify entity @s Pose.Head set value [89.9439f,0f,0f]
execute if score .this aj.frame matches 26 run data modify entity @s Pose.Head set value [89.9253f,0f,0f]
execute if score .this aj.frame matches 27 run data modify entity @s Pose.Head set value [89.9066f,0f,0f]
execute if score .this aj.frame matches 28 run data modify entity @s Pose.Head set value [89.8879f,0f,0f]
execute if score .this aj.frame matches 29 run data modify entity @s Pose.Head set value [89.8692f,0f,0f]
execute if score .this aj.frame matches 30 run data modify entity @s Pose.Head set value [89.8505f,0f,0f]
execute if score .this aj.frame matches 31 run data modify entity @s Pose.Head set value [89.8318f,0f,0f]