#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 56 run data modify entity @s Pose.Head set value [89.3647f,0f,0f]
execute if score .this aj.frame matches 57 run data modify entity @s Pose.Head set value [89.3461f,0f,0f]
execute if score .this aj.frame matches 58 run data modify entity @s Pose.Head set value [89.3274f,0f,0f]
execute if score .this aj.frame matches 59 run data modify entity @s Pose.Head set value [89.3087f,0f,0f]
execute if score .this aj.frame matches 60 run data modify entity @s Pose.Head set value [89.29f,0f,0f]
execute if score .this aj.frame matches 61 run data modify entity @s Pose.Head set value [80.361f,0f,0f]
execute if score .this aj.frame matches 62 run data modify entity @s Pose.Head set value [71.432f,0f,0f]
execute if score .this aj.frame matches 63 run data modify entity @s Pose.Head set value [62.503f,0f,0f]