#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 50 run data modify entity @s Pose.Head set value [-40f,0f,0f]
execute if score .this aj.frame matches 51 run data modify entity @s Pose.Head set value [-33.5f,0f,0f]
execute if score .this aj.frame matches 52 run data modify entity @s Pose.Head set value [-27f,0f,0f]
execute if score .this aj.frame matches 53 run data modify entity @s Pose.Head set value [-23.625f,0f,0f]
execute if score .this aj.frame matches 54 run data modify entity @s Pose.Head set value [-20.25f,0f,0f]
execute if score .this aj.frame matches 55 run data modify entity @s Pose.Head set value [-16.875f,0f,0f]