#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..63 run function sully_boss:animations/ground_stomp/tree/left_leg_down_display_0-63
execute if score .this aj.frame matches 64..71 run function sully_boss:animations/ground_stomp/tree/left_leg_down_display_64-71