#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run tp @s ^0.313 ^-1.395 ^-0.192 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^0.313 ^-1.431 ^-0.213 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^0.313 ^-1.467 ^-0.226 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^0.313 ^-1.503 ^-0.232 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^0.313 ^-1.54 ^-0.23 ~ ~
execute if score .this aj.frame matches 21 run tp @s ^0.313 ^-1.581 ^-0.222 ~ ~
execute if score .this aj.frame matches 22 run tp @s ^0.313 ^-1.625 ^-0.208 ~ ~
execute if score .this aj.frame matches 23 run tp @s ^0.313 ^-1.625 ^-0.208 ~ ~