#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run data modify entity @s Pose.Head set value [-30f,0f,0f]
execute if score .this aj.frame matches 25 run data modify entity @s Pose.Head set value [-33.3333f,0f,0f]
execute if score .this aj.frame matches 26 run data modify entity @s Pose.Head set value [-36.6667f,0f,0f]
execute if score .this aj.frame matches 27 run data modify entity @s Pose.Head set value [-40f,0f,0f]