#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run data modify entity @s Pose.Head set value [89.5142f,0f,0f]
execute if score .this aj.frame matches 49 run data modify entity @s Pose.Head set value [89.4955f,0f,0f]
execute if score .this aj.frame matches 50 run data modify entity @s Pose.Head set value [89.4768f,0f,0f]
execute if score .this aj.frame matches 51 run data modify entity @s Pose.Head set value [89.4582f,0f,0f]
execute if score .this aj.frame matches 52 run data modify entity @s Pose.Head set value [89.4395f,0f,0f]
execute if score .this aj.frame matches 53 run data modify entity @s Pose.Head set value [89.4208f,0f,0f]
execute if score .this aj.frame matches 54 run data modify entity @s Pose.Head set value [89.4021f,0f,0f]
execute if score .this aj.frame matches 55 run data modify entity @s Pose.Head set value [89.3834f,0f,0f]