#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..63 run function sully_boss:animations/ground_stomp/tree/left_arm_display_0-63
execute if score .this aj.frame matches 71 run data modify entity @s Pose.Head set value [0f,0f,0f]