#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 56 run tp @s ^0.313 ^-1.661 ^-0.067 ~ ~
execute if score .this aj.frame matches 57 run tp @s ^0.313 ^-1.657 ^-0.036 ~ ~
execute if score .this aj.frame matches 58 run tp @s ^0.313 ^-1.65 ^-0.005 ~ ~
execute if score .this aj.frame matches 59 run tp @s ^0.313 ^-1.639 ^0.028 ~ ~
execute if score .this aj.frame matches 60 run tp @s ^0.313 ^-1.626 ^0.06 ~ ~
execute if score .this aj.frame matches 61 run tp @s ^0.313 ^-1.578 ^0.031 ~ ~
execute if score .this aj.frame matches 62 run tp @s ^0.313 ^-1.535 ^0.003 ~ ~
execute if score .this aj.frame matches 63 run tp @s ^0.313 ^-1.497 ^-0.024 ~ ~