#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run tp @s ^0.306 ^-1.25 ^-0.271 ~ ~
execute if score .this aj.frame matches 49 run tp @s ^0.306 ^-1.25 ^-0.271 ~ ~
execute if score .this aj.frame matches 50 run tp @s ^0.306 ^-1.25 ^-0.271 ~ ~
execute if score .this aj.frame matches 51 run tp @s ^0.306 ^-1.262 ^-0.253 ~ ~
execute if score .this aj.frame matches 52 run tp @s ^0.306 ^-1.272 ^-0.232 ~ ~
execute if score .this aj.frame matches 53 run tp @s ^0.306 ^-1.28 ^-0.209 ~ ~
execute if score .this aj.frame matches 54 run tp @s ^0.306 ^-1.285 ^-0.184 ~ ~
execute if score .this aj.frame matches 55 run tp @s ^0.306 ^-1.287 ^-0.156 ~ ~