#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 64 run data modify entity @s Pose.Head set value [-1.95f,0f,0f]
execute if score .this aj.frame matches 65 run data modify entity @s Pose.Head set value [-1.625f,0f,0f]
execute if score .this aj.frame matches 66 run data modify entity @s Pose.Head set value [-1.3f,0f,0f]
execute if score .this aj.frame matches 67 run data modify entity @s Pose.Head set value [-0.975f,0f,0f]
execute if score .this aj.frame matches 68 run data modify entity @s Pose.Head set value [-0.65f,0f,0f]
execute if score .this aj.frame matches 69 run data modify entity @s Pose.Head set value [-0.325f,0f,0f]
execute if score .this aj.frame matches 70 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 71 run data modify entity @s Pose.Head set value [0f,0f,0f]