#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run tp @s ^-0.25 ^-1.311 ^0.108 ~ ~
execute if score .this aj.frame matches 49 run tp @s ^-0.25 ^-1.311 ^0.108 ~ ~
execute if score .this aj.frame matches 50 run tp @s ^-0.25 ^-1.311 ^0.108 ~ ~
execute if score .this aj.frame matches 51 run tp @s ^-0.25 ^-1.323 ^0.126 ~ ~
execute if score .this aj.frame matches 52 run tp @s ^-0.25 ^-1.332 ^0.147 ~ ~
execute if score .this aj.frame matches 53 run tp @s ^-0.25 ^-1.34 ^0.17 ~ ~
execute if score .this aj.frame matches 54 run tp @s ^-0.25 ^-1.345 ^0.195 ~ ~
execute if score .this aj.frame matches 55 run tp @s ^-0.25 ^-1.347 ^0.223 ~ ~