#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 56 run tp @s ^-0.812 ^-0.512 ^0.286 ~ ~
execute if score .this aj.frame matches 57 run tp @s ^-0.812 ^-0.469 ^0.233 ~ ~
execute if score .this aj.frame matches 58 run tp @s ^-0.812 ^-0.432 ^0.178 ~ ~
execute if score .this aj.frame matches 59 run tp @s ^-0.812 ^-0.401 ^0.121 ~ ~
execute if score .this aj.frame matches 60 run tp @s ^-0.812 ^-0.375 ^0.063 ~ ~
execute if score .this aj.frame matches 61 run tp @s ^-0.812 ^-0.325 ^0.063 ~ ~
execute if score .this aj.frame matches 62 run tp @s ^-0.812 ^-0.275 ^0.063 ~ ~
execute if score .this aj.frame matches 63 run tp @s ^-0.812 ^-0.226 ^0.063 ~ ~