#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 50 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 51 run data modify entity @s Pose.Head set value [-0.325f,0f,0f]
execute if score .this aj.frame matches 52 run data modify entity @s Pose.Head set value [-0.65f,0f,0f]
execute if score .this aj.frame matches 53 run data modify entity @s Pose.Head set value [-0.975f,0f,0f]
execute if score .this aj.frame matches 54 run data modify entity @s Pose.Head set value [-1.3f,0f,0f]
execute if score .this aj.frame matches 55 run data modify entity @s Pose.Head set value [-1.625f,0f,0f]