#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run data modify entity @s Pose.Head set value [-36.087f,0f,0f]
execute if score .this aj.frame matches 41 run data modify entity @s Pose.Head set value [-35.9783f,0f,0f]
execute if score .this aj.frame matches 42 run data modify entity @s Pose.Head set value [-35.8696f,0f,0f]
execute if score .this aj.frame matches 43 run data modify entity @s Pose.Head set value [-35.7609f,0f,0f]
execute if score .this aj.frame matches 44 run data modify entity @s Pose.Head set value [-35.6522f,0f,0f]
execute if score .this aj.frame matches 45 run data modify entity @s Pose.Head set value [-35.5435f,0f,0f]
execute if score .this aj.frame matches 46 run data modify entity @s Pose.Head set value [-35.4348f,0f,0f]
execute if score .this aj.frame matches 47 run data modify entity @s Pose.Head set value [-35.3261f,0f,0f]