#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run tp @s ^-0.25 ^-1.417 ^-0.017 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^-0.25 ^-1.438 ^0.029 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^-0.25 ^-1.44 ^0.066 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^-0.25 ^-1.425 ^0.094 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^-0.25 ^-1.397 ^0.111 ~ ~
execute if score .this aj.frame matches 21 run tp @s ^-0.25 ^-1.358 ^0.116 ~ ~
execute if score .this aj.frame matches 22 run tp @s ^-0.25 ^-1.311 ^0.108 ~ ~
execute if score .this aj.frame matches 23 run tp @s ^-0.25 ^-1.311 ^0.108 ~ ~