#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 14 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 15 run data modify entity @s Pose.Head set value [-10f,0f,0f]