#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run data modify entity @s Pose.Head set value [-36.9565f,0f,0f]
execute if score .this aj.frame matches 33 run data modify entity @s Pose.Head set value [-36.8478f,0f,0f]
execute if score .this aj.frame matches 34 run data modify entity @s Pose.Head set value [-36.7391f,0f,0f]
execute if score .this aj.frame matches 35 run data modify entity @s Pose.Head set value [-36.6304f,0f,0f]
execute if score .this aj.frame matches 36 run data modify entity @s Pose.Head set value [-36.5217f,0f,0f]
execute if score .this aj.frame matches 37 run data modify entity @s Pose.Head set value [-36.413f,0f,0f]
execute if score .this aj.frame matches 38 run data modify entity @s Pose.Head set value [-36.3043f,0f,0f]
execute if score .this aj.frame matches 39 run data modify entity @s Pose.Head set value [-36.1957f,0f,0f]