#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 56 run tp @s ^-0.25 ^-1.346 ^0.252 ~ ~
execute if score .this aj.frame matches 57 run tp @s ^-0.25 ^-1.342 ^0.282 ~ ~
execute if score .this aj.frame matches 58 run tp @s ^-0.25 ^-1.334 ^0.314 ~ ~
execute if score .this aj.frame matches 59 run tp @s ^-0.25 ^-1.324 ^0.346 ~ ~
execute if score .this aj.frame matches 60 run tp @s ^-0.25 ^-1.309 ^0.379 ~ ~
execute if score .this aj.frame matches 61 run tp @s ^-0.25 ^-1.335 ^0.368 ~ ~
execute if score .this aj.frame matches 62 run tp @s ^-0.25 ^-1.359 ^0.346 ~ ~
execute if score .this aj.frame matches 63 run tp @s ^-0.25 ^-1.379 ^0.314 ~ ~