#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [-144f,0f,0f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [-162f,0f,0f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [-180f,0f,0f]
execute if score .this aj.frame matches 14 run data modify entity @s Pose.Head set value [-180f,0f,0f]
execute if score .this aj.frame matches 15 run data modify entity @s Pose.Head set value [-172.5f,0f,0f]