#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run data modify entity @s Pose.Head set value [-27.5f,0f,0f]
execute if score .this aj.frame matches 25 run data modify entity @s Pose.Head set value [-30.8333f,0f,0f]
execute if score .this aj.frame matches 26 run data modify entity @s Pose.Head set value [-34.1667f,0f,0f]
execute if score .this aj.frame matches 27 run data modify entity @s Pose.Head set value [-37.5f,0f,0f]
execute if score .this aj.frame matches 28 run data modify entity @s Pose.Head set value [-37.3913f,0f,0f]
execute if score .this aj.frame matches 29 run data modify entity @s Pose.Head set value [-37.2826f,0f,0f]
execute if score .this aj.frame matches 30 run data modify entity @s Pose.Head set value [-37.1739f,0f,0f]
execute if score .this aj.frame matches 31 run data modify entity @s Pose.Head set value [-37.0652f,0f,0f]