#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 8..15 run function sully_boss:animations/ground_stomp/tree/right_leg_display_8-15
execute if score .this aj.frame matches 16..23 run function sully_boss:animations/ground_stomp/tree/right_leg_display_16-23
execute if score .this aj.frame matches 56..63 run function sully_boss:animations/ground_stomp/tree/right_leg_display_56-63