#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 56 run tp @s ^-0.25 ^-1.286 ^-0.127 ~ ~
execute if score .this aj.frame matches 57 run tp @s ^-0.25 ^-1.282 ^-0.097 ~ ~
execute if score .this aj.frame matches 58 run tp @s ^-0.25 ^-1.275 ^-0.065 ~ ~
execute if score .this aj.frame matches 59 run tp @s ^-0.25 ^-1.264 ^-0.033 ~ ~
execute if score .this aj.frame matches 60 run tp @s ^-0.25 ^-1.25 ^0 ~ ~
execute if score .this aj.frame matches 61 run tp @s ^-0.25 ^-1.2 ^0 ~ ~
execute if score .this aj.frame matches 62 run tp @s ^-0.25 ^-1.15 ^0 ~ ~
execute if score .this aj.frame matches 63 run tp @s ^-0.25 ^-1.1 ^0 ~ ~