#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run data modify entity @s Pose.Head set value [-35.2174f,0f,0f]
execute if score .this aj.frame matches 49 run data modify entity @s Pose.Head set value [-35.1087f,0f,0f]
execute if score .this aj.frame matches 50 run data modify entity @s Pose.Head set value [-35f,0f,0f]
execute if score .this aj.frame matches 51 run data modify entity @s Pose.Head set value [-28.5f,0f,0f]
execute if score .this aj.frame matches 52 run data modify entity @s Pose.Head set value [-19.5f,0f,0f]
execute if score .this aj.frame matches 53 run data modify entity @s Pose.Head set value [-16.75f,0f,0f]
execute if score .this aj.frame matches 54 run data modify entity @s Pose.Head set value [-14f,0f,0f]
execute if score .this aj.frame matches 55 run data modify entity @s Pose.Head set value [-11.25f,0f,0f]