#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 48..55 run function sully_boss:animations/ground_stomp/tree/right_leg_down_display_48-55
execute if score .this aj.frame matches 56..63 run function sully_boss:animations/ground_stomp/tree/right_leg_down_display_56-63