#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 56 run data modify entity @s Pose.Head set value [-1.95f,0f,0f]
execute if score .this aj.frame matches 57 run data modify entity @s Pose.Head set value [-2.275f,0f,0f]
execute if score .this aj.frame matches 58 run data modify entity @s Pose.Head set value [-2.6f,0f,0f]
execute if score .this aj.frame matches 59 run data modify entity @s Pose.Head set value [-2.925f,0f,0f]
execute if score .this aj.frame matches 60 run data modify entity @s Pose.Head set value [-3.25f,0f,0f]
execute if score .this aj.frame matches 61 run data modify entity @s Pose.Head set value [-2.925f,0f,0f]
execute if score .this aj.frame matches 62 run data modify entity @s Pose.Head set value [-2.6f,0f,0f]
execute if score .this aj.frame matches 63 run data modify entity @s Pose.Head set value [-2.275f,0f,0f]