#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 64 run tp @s ^-0.25 ^-1.394 ^0.273 ~ ~
execute if score .this aj.frame matches 65 run tp @s ^-0.25 ^-1.403 ^0.222 ~ ~
execute if score .this aj.frame matches 66 run tp @s ^-0.25 ^-1.404 ^0.164 ~ ~
execute if score .this aj.frame matches 67 run tp @s ^-0.25 ^-1.396 ^0.099 ~ ~
execute if score .this aj.frame matches 68 run tp @s ^-0.25 ^-1.379 ^0.028 ~ ~
execute if score .this aj.frame matches 69 run tp @s ^-0.25 ^-1.351 ^-0.047 ~ ~
execute if score .this aj.frame matches 70 run tp @s ^-0.25 ^-1.313 ^-0.125 ~ ~
execute if score .this aj.frame matches 71 run tp @s ^-0.25 ^-1.313 ^-0.125 ~ ~