#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 60 run data modify entity @s Pose.Head set value [-80f,0f,0f]
execute if score .this aj.frame matches 61 run data modify entity @s Pose.Head set value [-72f,0f,0f]
execute if score .this aj.frame matches 62 run data modify entity @s Pose.Head set value [-64f,0f,0f]
execute if score .this aj.frame matches 63 run data modify entity @s Pose.Head set value [-56f,0f,0f]