#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 64 run data modify entity @s Pose.Head set value [-48f,0f,0f]
execute if score .this aj.frame matches 65 run data modify entity @s Pose.Head set value [-40f,0f,0f]
execute if score .this aj.frame matches 66 run data modify entity @s Pose.Head set value [-32f,0f,0f]
execute if score .this aj.frame matches 67 run data modify entity @s Pose.Head set value [-24f,0f,0f]
execute if score .this aj.frame matches 68 run data modify entity @s Pose.Head set value [-16f,0f,0f]
execute if score .this aj.frame matches 69 run data modify entity @s Pose.Head set value [-8f,0f,0f]
execute if score .this aj.frame matches 70 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 71 run data modify entity @s Pose.Head set value [0f,0f,0f]