#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 56 run tp @s ^0 ^-0.861 ^-0.006 ~ ~
execute if score .this aj.frame matches 57 run tp @s ^0 ^-0.847 ^-0.021 ~ ~
execute if score .this aj.frame matches 58 run tp @s ^0 ^-0.834 ^-0.035 ~ ~
execute if score .this aj.frame matches 59 run tp @s ^0 ^-0.823 ^-0.049 ~ ~
execute if score .this aj.frame matches 60 run tp @s ^0 ^-0.813 ^-0.062 ~ ~
execute if score .this aj.frame matches 61 run tp @s ^0 ^-0.763 ^-0.062 ~ ~
execute if score .this aj.frame matches 62 run tp @s ^0 ^-0.713 ^-0.062 ~ ~
execute if score .this aj.frame matches 63 run tp @s ^0 ^-0.663 ^-0.062 ~ ~