#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [15f,0f,0f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [22.5f,0f,0f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [30f,0f,0f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [37.5f,0f,0f]
execute if score .this aj.frame matches 20 run data modify entity @s Pose.Head set value [45f,0f,0f]
execute if score .this aj.frame matches 21 run data modify entity @s Pose.Head set value [52.5f,0f,0f]
execute if score .this aj.frame matches 22 run data modify entity @s Pose.Head set value [60f,0f,0f]