#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run tp @s ^0 ^-0.978 ^0.077 ~ ~
execute if score .this aj.frame matches 49 run tp @s ^0 ^-0.978 ^0.077 ~ ~
execute if score .this aj.frame matches 50 run tp @s ^0 ^-0.978 ^0.077 ~ ~
execute if score .this aj.frame matches 51 run tp @s ^0 ^-0.955 ^0.064 ~ ~
execute if score .this aj.frame matches 52 run tp @s ^0 ^-0.933 ^0.051 ~ ~
execute if score .this aj.frame matches 53 run tp @s ^0 ^-0.913 ^0.037 ~ ~
execute if score .this aj.frame matches 54 run tp @s ^0 ^-0.894 ^0.023 ~ ~
execute if score .this aj.frame matches 55 run tp @s ^0 ^-0.877 ^0.008 ~ ~