#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 50 run data modify entity @s Pose.Head set value [60f,0f,0f]
execute if score .this aj.frame matches 51 run data modify entity @s Pose.Head set value [54f,0f,0f]
execute if score .this aj.frame matches 52 run data modify entity @s Pose.Head set value [48f,0f,0f]
execute if score .this aj.frame matches 53 run data modify entity @s Pose.Head set value [42f,0f,0f]
execute if score .this aj.frame matches 54 run data modify entity @s Pose.Head set value [36f,0f,0f]
execute if score .this aj.frame matches 55 run data modify entity @s Pose.Head set value [30f,0f,0f]