#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run tp @s ^0 ^-0.465 ^-0.028 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^0 ^-0.545 ^-0.01 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^0 ^-0.627 ^0.008 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^0 ^-0.711 ^0.027 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^0 ^-0.798 ^0.044 ~ ~
execute if score .this aj.frame matches 21 run tp @s ^0 ^-0.887 ^0.061 ~ ~
execute if score .this aj.frame matches 22 run tp @s ^0 ^-0.978 ^0.077 ~ ~
execute if score .this aj.frame matches 23 run tp @s ^0 ^-0.978 ^0.077 ~ ~