#Project generated by Animated Java (https://animated-java.dev/)

execute if score @s aj.sully_boss.wake.loopMode matches 0 run function sully_boss:animations/wake/stop
execute if score @s aj.sully_boss.wake.loopMode matches 1 run function sully_boss:animations/wake/pause
execute if score @s aj.sully_boss.wake.loopMode matches 2 run function sully_boss:animations/wake/zzz/execute/41