#Project generated by Animated Java (https://animated-java.dev/)

summon minecraft:marker ~ ~ ~ {Tags:['new','aj.christophe','aj.christophe.root']}
execute as @e[type=minecraft:marker,tag=aj.christophe.root,tag=new,distance=..1,limit=1] rotated ~ 0 run function christophe:summon/zzz/execute/2
function christophe:assert_animation_flags