#Project generated by Animated Java (https://animated-java.dev/)

tag @s add aj.christophe.anim.idle
execute if score .aj.anim_loop aj.christophe.animating matches 0 run function christophe:animation_loop
scoreboard players set #execute aj.i 1