#Project generated by Animated Java (https://animated-java.dev/)

scoreboard players set #execute aj.i 0
execute if score @s aj.frame matches ..1 run function sully_boss:animations/ground_stomp/zzz/conditional/54
execute if score #execute aj.i matches 0 run function sully_boss:animations/ground_stomp/zzz/conditional/55