#Project generated by Animated Java (https://animated-java.dev/)

tp @s ~ ~ ~ ~ ~
execute store result score @s aj.id run scoreboard players add .aj.last_id aj.i 1
execute at @s run function sully_boss:summon/zzz/execute/3
tag @s remove new
scoreboard players set @s aj.sully_boss.walk.loopMode 2
scoreboard players set @s aj.sully_boss.idle.loopMode 2
scoreboard players set @s aj.sully_boss.death.loopMode 1
scoreboard players set @s aj.sully_boss.attack.loopMode 0
scoreboard players set @s aj.sully_boss.ground_stomp.loopMode 0
scoreboard players set @s aj.sully_boss.roar.loopMode 0
scoreboard players set @s aj.sully_boss.sleep.loopMode 2
scoreboard players set @s aj.sully_boss.wake.loopMode 0
scoreboard players set @s aj.frame 0
scoreboard players set @s aj.sully_boss.animating 0