#Project generated by Animated Java (https://animated-java.dev/)

summon minecraft:marker ~ ~ ~ {Tags:['new','aj.sully_boss','aj.sully_boss.root']}
execute as @e[type=minecraft:marker,tag=aj.sully_boss.root,tag=new,distance=..1,limit=1] rotated ~ 0 run function sully_boss:summon/zzz/execute/2
function sully_boss:assert_animation_flags